{
  "name": "TransferMarket",
  "compatibilityLevel": 1567,
  "model": {
    "culture": "en-GB",
    "defaultPowerBIDataSourceVersion": "powerBI_V3",
    "tables": [
      {
        "name": "Transfers",
        "columns": [
          {
            "name": "record_id",
            "dataType": "string",
            "sourceColumn": "record_id",
            "summarizeBy": "none"
          },
          {
            "name": "player_name",
            "dataType": "string",
            "sourceColumn": "player_name",
            "summarizeBy": "none"
          },
          {
            "name": "from_club",
            "dataType": "string",
            "sourceColumn": "from_club",
            "summarizeBy": "none"
          },
          {
            "name": "to_club",
            "dataType": "string",
            "sourceColumn": "to_club",
            "summarizeBy": "none"
          },
          {
            "name": "announcement_date",
            "dataType": "dateTime",
            "sourceColumn": "announcement_date",
            "summarizeBy": "none",
            "formatString": "dd MMM yyyy"
          },
          {
            "name": "transfer_type",
            "dataType": "string",
            "sourceColumn": "transfer_type",
            "summarizeBy": "none"
          },
          {
            "name": "fee_status",
            "dataType": "string",
            "sourceColumn": "fee_status",
            "summarizeBy": "none"
          },
          {
            "name": "quoted_fee_gbp",
            "dataType": "double",
            "sourceColumn": "quoted_fee_gbp",
            "summarizeBy": "none"
          },
          {
            "name": "quote_basis",
            "dataType": "string",
            "sourceColumn": "quote_basis",
            "summarizeBy": "none"
          },
          {
            "name": "from_league",
            "dataType": "string",
            "sourceColumn": "from_league",
            "summarizeBy": "none"
          },
          {
            "name": "to_league",
            "dataType": "string",
            "sourceColumn": "to_league",
            "summarizeBy": "none"
          },
          {
            "name": "position",
            "dataType": "string",
            "sourceColumn": "position",
            "summarizeBy": "none"
          },
          {
            "name": "source_url",
            "dataType": "string",
            "sourceColumn": "source_url",
            "summarizeBy": "none"
          },
          {
            "name": "has_reported_fee",
            "dataType": "int64",
            "sourceColumn": "has_reported_fee",
            "summarizeBy": "none"
          },
          {
            "name": "is_permanent_fee",
            "dataType": "int64",
            "sourceColumn": "is_permanent_fee",
            "summarizeBy": "none"
          },
          {
            "name": "announcement_month",
            "dataType": "string",
            "sourceColumn": "announcement_month",
            "summarizeBy": "none"
          }
        ],
        "partitions": [
          {
            "name": "Transfers",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": "let\n    Snapshot = Table.FromRecords(Json.Document(Binary.Decompress(Binary.FromText(\"7L3bchvJliX4K27nudlHpERdup4A8CaSIFkEk5rMeTi2ATgBFzzCcTwiQAFt81DfUB8wk1ZtNqUuyzl2Ks2OtbXlG35stoOkBITvAIJQOBkBej1UVokSCQQW92Wtvdf+P//7nzTvKN39i+j+6b+xP7V23m69evVq+0//hf1pKGHM9V9CCLj50rHqh6wVq5BH5qs3WgV/6cikbb7WhLDT51HMNWuIeGy+HqtvX/0Y4hfMn0EYqiTs8ICH8V+6EM++784r8zPfbb1+NftnGsLoBn9sPB7OvnygOZ/9PM7/EsUQJ9HDn7KHv2u+/NdExbz7F/O3eu0h/pUwkfLhz//Shkh8/3f4/33/x//EVNzH191RURyxUMVM86HmEb5E3v32RiWHXjJ7PReaBwL//undn9y90+9fbnEtOKvNnp+KRCxUaP54j9/wsHv3UiOV6A7/S6Kl+Uo/jofRf/vzn29vb/8rvpBeArorIPyvHRX8+UapuA1S/jnsbQnzEKETixH/s3lkf4748M+vtv+MzzLaengzW7ci7KrbrSgJAvz/Zo8W//1Wl4OMtsw72eKJVkOO/0QNt27wm23dvfbZZ9qH6C/47pW+f5Tm9c0+FRH9Zch1AKH54Oa/sPCJBiqM+3Mf6Z/+r//CaHztEPiqhRBF7BfQ+HjGFsJO8W2mYHUBIcR9EYIYqGgFvHa3dnZoeFHourx/Buzm7qsWuP608/aV+Z8/2QhrzT5dNvvTf5pB7c/Q7W6pEBHHITavjSVhNOQdcSNIhJ0K/D/YtgWt8ySORBeRq4bMfHLsz/iNII4Bf/W6acB9EmGvinDbzoLb9iq47WbD7TUBt49RANO/SbYn8BUrC2974jM+yEXAXalEqiTia2OtZKFsJaAW4DcHy5ce2ZZA7S0BtVOOv/21Mb4BbuHs4zC6FZ0+u1K3abjtqbAD0erUiXijU+dPYVdEHami75FsEXpzf+ERwDtT+AX8EESHRXPB7vG58kUENCcoe0+hLBkA20vwY7FAdqRu8Je0z0VgpVD8zW0rHa6G2PtyQqye4G9VJEUPLHgtfmkeS03RxdwrfdR6wNMHAk91IUGyfclO+rPvGtll/ykXncyqvxUncdwDHa+s/O/ajaJKs+0379zVZo9LmZuJwPVLtOyOYJvqOGtafMYfELMmGdWWpM4WthKJuivrlkDvbcHQu2sK3CBvvb7zUIEccD58WTh7m40zqhU4TUTEWiIUJpRpsIBWx8cW8kAl+DMWcdbQyYQLvQpnbzLJjfVwtrvzbDh7ETXb+sh7k428N2QTGmHNppKgLWzYXfOQTwSkQ5t5qfhcnzi0bb977w5zc8FrfbC9zJS6JNTtEoBr9JOBsJB2ia+cXeN7gK6SoptC3Ceu8aGyujYvYDXsNpH72MxCbv1WYgnqKAKknrSBtSDEbmD61UafCtJBbl/ix7Aaaq+LjHCvPzx9gDsFdkqAqrqcmpNA9o6A1DEMkjY7gUCEERHRPil5E7UT3UsXbNgU9MKnhtYbh7mzqED28mq1JYij+LULiLELHbBPwrz23Ihb5N6eEHTvK0CDeNDNgY4i4Q5VOAGp2LXA4swG3Z7Av6jYL9DTvL1GDt3d2vlQPOZKALmMxFrlas2FMrpD0W77AX7/hEu2H/Be3+5LW/gmo7Yikmufy4jDE3emO9vPoMXbLMk8zA6UvkX0vCSMZce1HXrYoztml6rNdRzd6eyLwgK+Vj1USqYQdqXiGJMpBOxIxdEwWSWNzsBfhXZ0Beu2HG7VbRdcdKA7FMV7rEKI2HkghQ22utJJFAlgzek/zBhb2JPQbWNeSYGvjh+wXBdwZRZKH0WzVVlRcAI3itetSRFhXDOcR6xs3XSew50D2BkMlRRrh7Q1id3XDkWrxxVtGRqWbxLm0EaRujVp8ig71NP/FbaBD2yGjYf3U7vzjSkED+3qE8LNpXSVVaxtJnvrBF4Ue1uTfBBB2AXNWjGEAzUixPgG/pfVddLr8RTO8kx/Fx7UPjgkcwsJah55KeRRJO8ehPiM2AXXPJ7YdZv5uyFrJqGwarWWEeshGMYqh2JVKPRczoD4Gs4R+Ci+9wTLjsisuyDCMOx1bwkm5JpdCp7WSxvQkwL02oXcs7cKhQS4ynIgTpoEits1A7vRhF0ozds2tubKswVSd8R1hOVejrrtbaEZ9c2zhDVfuuWF2N2EWQpiv0BXDdjPykzw2hCrfTxJUxxa9Pq5cmah4NrZ3i1LubacafOt6BzgKO3gEqb/W7JjEUy/htwu2Q4SiVVZCnSflAlq99Ua+wSGysQgtxqDGdJVtajdRxVuPqnOA5ASFi4hCpKIHU3/12eJucNC4Nym8k+hiK3iLS8HV+x8yOvnG+jdtPLNSaijJIU9FY65lKwJktuiQs20DneyfQphD+Nuy2X5gvOrQ4nU4+uHZfjXlIZwP+EmboWyBz9qGvMNpOVRbCXiVbsIu1uv6FW+tRsDh7VbkbmzuiqpE8hRQkKTaylCdjn9R1/atZvmgupIsXZb3TG8K7odfff6WfrR5e3By+xJs7f6XlNywsMc5S/QpjYRRGD7fGgRsYPG6qKsOnNFhVgvvEy4LSnTKA3hBOuPgNUkfG7zHildXSIK6tj8sRbICRHhZjoD/sZjoBskUZ4VmGKXSksjZfk53lwopMSEFiRdVmt3Z/yHsNtSYgfmwfFoOdTeFAk1l6MgmSswm2Yr4wRTlH5wgoUIhOxKi+FQEBsJZ/zW+MdITjMda9NuGe3DBtNu1QWjC97tDaU0nImBkhCxa3ybcdTph6JHcG8inLB71VMtz79rMb/li3pFKfa+1EthkBIfGhpEjx2A/mvSJ5ZlGnqMsJDsAiR00lNKddAhX2VVsynj5D74rQ88SnT4GEGHnYrugy6/uKMFOkBMdOM04paNnW9I+Cuqv3iBbPESCFJqRBOzLrtUsT1sftBgV7cmUKTw95jF1EIBt/3K4SxJUYirbtRzAjlKoNhHVLFjUAkhf1E8HtWPLIXddqGmSSXi85azyH46MwU+Sqo4xg/nMNGia3PINQmj6dc0+lp89CDGrgW6klV4cwvOm7747KSMo5SJJmh8/KzFQx7ZsMp2gXv8VmpFQOa3UosDHLnfwEMRsaMk4iI0HxuxVvPdr2ZhTBN6GxPJPEXiCHGUDnGmTJg6gQAIn8s7obUF+BS2Ds0rEWlf1dNxjtngYsu21w7HS7IWBr0mkQdflCaBKXQkQnag8YHr+7WstZbtsUXAD7I+G0h5AZFuExtRF0Ftl9IeWhCrqC/YFYQwsMPaAb4qTBtsb/pHFGGCUPom3Rt0+qblYndq6hMGtwpI+1VOqy7C3i6lPJyYBfuY7WPE699fU1hc5uI67sNcOPuR8ZJiIejS19dj0BEGKRHiCIIJmBkTLgdYyAUEL8JqfZk+01DHppdLFa7fT/yQ70gJcJdBmXjNYR5xlOZwwkWUYNo8VLF9QKtmihbJO/207jU/R7wcb8UamG873LHxOpcLzJFbEQmE7GNPcuwhbK3rkMdwk2ZLcjO/GXgrWRfxSObX9w8LmKK0BHOfDd+7YnVhiNwOPqXYgpblgj+/AxFy3ROcNVQct5PVI3QVQVpRzJyH4AIEKemh1ReKHSSDpEudn8lHmZyAlpFOchjnF5tZHcqqRSHQ59V5AFJSxH44wfiH755LW/raS8IB139N0pkVm1a4HyzZhHj34i2mnYQ7SoY4TkKhNKt1IUhsvo5eNHwMSVdofHPoo78WI+yD2Ty8SBVCIFa4ZIea95QWZh7dzqrGLbPbTtMhtaQX5etO6TtHFTPv2kCUuQhibynZoQnmLCVnJxpM2xCYJ2xPnS9zKXyEm1dZ4fbivLucwIvSFI6hH4BgLREMIxVuXSQRH1vomrOzIU7w5r12VFZwrZg/8qJpTnhRcsEBtLHlPNRJm1odTPDJP8SlOUDNb3BVElF+PNwJwCh1oBZ29fQrxi85sjmNb8eJHulek4mssvWSWSzty6AtnICMkgPOpRybKwv4q0jdkSH9BlsxH/EQejnyIu3y9uxRzFsKusIYJQ8YEzes8hV1Z/LshH2MYp32bphbQVgOsI1wgPbKUx5oUbT/LzxU7BpCtsdDVlcUT3GpxiBZLYxvuR6mYPa4IclqrC77Cs0J+ijO3+y7sEbSwWL/Xh9f3D34fs5vwa0BjOdlV4scC3wuTsc8i9PgxoU4F1zsW4rqP8D30BEROw/HnBjOpaYf12TIaLCdKghttJk/NUibBSTzx54eK3Hwojj+MwV99omLKOpDMrTnNTJUpAU3hkrWZkVp4lX1bHOBsHcUv481V1+FY3ZqXp5d+RvlO71kXDOPdO2yv9qlWMbSVJW32Z1AjXQuwk9EhMSt5XM5DoYCBiqNtNyXOoqtwba3S+MWs6nbxy4qs3eUAnAC079J7DqTLtyTsYsBTlgmWfnWP6sR3B65++mz5RyaKLof4aLk9D/ZLxAKJe19gEOQEEMEGtIq5U9dEeLn9MSR7E1p9k/82dvViCOPLGtl1jpbEPYephAXEHfK2RGM9NrrABmG9VWJY5vGWDiJZBTffyCVxjfOjriUZrLClpVacRLHPdDp1aZDzZPZh3cw/UPHq438MiBWWsrixRwZdYI1SgC4+gwRq/MeYf1yAdryBG9BMOwadK4LrWdnL7JswD11sS6sKGZ/RrryqKNYw1i9EEslTSHBcnfhnU6OMqzY01QOt0eysOZPUuWAFcXlf4wirLdUgpCafs1bb10ab4QcnFjFyy3fNq6EFEXjf4wAOlhqQWxL33OnpRbOawdtLbq9/DaiJSXyi5zi8Tj7jrP3FJlfxzp+tuNLzyMun6N+lOb9rhJxbD292yuTKahRZP6DboSQM9+IyJPhuroRja3n7Rd9RlwfPhQt3+L4IcSGgPgEMhkIfis69iXtK+wCQ2W1h1GU3JOvawWp8lGpj6zhq0tvuSji31NE/WUCBKM1h5z5uBTL6ddYYB/ZFCEX+qmR9Xr76ZH1QqwtnOCNoukPBeB7NkyEnP6nBbyGKVHSNNeBxkccqjybazTcnr22L0QB8tVWCl4UW9/iZnw6kQSDuv3+7St68fYRt08qUs/7sWkniKM4++vpb51YYaPYTyK7um9Mf+2KSQpv39bdnjB3lsZbduOUSCepkzTlCfD7J1waqA1ubaeUxTC24GIRxVrgc8f/YnpNVkNvk5XI6iLNSUyjmH3jZaFYTUPQBq3tPTfSWPES34FmFxLyWEAVGttcqkaFbO5WF3JOghvJ/Lc19EUA7EThY6T0JAOvoVIyDbvHsLEbcax44zKoi7j2gaL9f8FvodhPoT2P2ELsiUnCWlsXiYysCztrH+fMQtya1FpZirjN3FZyEew+0GY+oWJGXTpSmmga8Pc/mf7fPES4/REaFSoFxwvAx9u+vyzwhPCrgGV2dYOgE/BRikKjDwNgVxqUnv67hT1qEugCdCwmYHbLZU8j+NbF3bMTcYWwvJWdDHKSZ0mznxsVRoo1leaCuCz2sDjyQ2dPio1suw4XmbIk0ewoVlVV1EkMo1SEB9KtmUz/rmw59DyCKLF0hIUO4gnB9fqNy6N1Gf3p8n24yoYwJwgjr7+aPMhqkg+oQ5ytZHbPBMJuCmOFpcrn5dqKHEarckfgJGNS3O6R4dki/L0/ViGxXp6NNx7PWgGV9NZuRp+9KvNoc4g2it+9UkEAWKA1lIbJhLoxYZxi0/nzWnR4OMmxbFLGiOY3TYoGFsXiYm+pJY+MiVlfJTGxhknskR/wMQ+V0jn42w9F1mW7DvmMrJr/xcQyB4Xa9iuK090DY1nADhPzFuxIpnmU3su85CLIMV1bDa2gEKBVlzVzENm2X1GU7Z4KRCj+is/6iOObtXvOOXf1+dhGXxteK8qVDHlej3cCPoqybSJCFDOb6ERvMBNA6zwW1hoBdgWdHOVaoUnV5V3NQrR4n1RTgCOnwmEywrq8BcRy1JxBy6L5rPFmFKaCB9bQINRobew9e0daSLfgLQ9SSKOY3Asu8UHrHhhMbTU7e2ZNKrY10Stlrur0IWBHKo6GSVoTRcTdSj5mV+p2ffGgZBm2SF7EZ9kFKFKz44cmZIWhYHtwcwOEbnWcjPCnJFaeHXEp79evntArweEwyIsPf04SLSUzrMTcPLjmMDcPxaWY23lVJOZKM0WesSPjMZfCHKU1HKpw+v+CVOxc4suiBPo6D29Ex/Z6z2fdUax4WhqH0YwN5uomVieAo+SGmuRRBGFXK3aWhBNB+vPRbUVN88lkdWbdoU+8boDkUOWI5qRyo2SHYxEE461jGJuRox6x0Ewfr/jEo5jV8e/dik6f1WRb5DG0dTDR+yxHLF7GzJuLILdN6RAN3jUx4aNpUy38ZdDAC1jUmEQQjea1rBvvytbA+uvDDiLgNiVPmOM9XLLTpC0Gdg8xd8V6HnIikmDuFQ/UbTUzrDcndQQx2iBey5n4ZeNLG9eG9GLWYyLa7tYOfVyxhBuBa58hrjLK1k+ju9koo5SHplCsDp1BHxJb6rIgteAS8v3CzxMibXvHISey1r0oD7MUzCjZoYkVP2DC3ANTy1ATcIkOeaCSOG0WcrfUgM9h7RMFz65ueatJR2mTUhWODb07YK2O8QchjqtfIgrq+IGyFsgJUaVhsAvjm9XTcbtF3/Zx2Zr62z7Ooh3F+DamX2fN6YkYUlbN3wbi5mD3cRjNWJEceuru1qtikffOA6+CwKOY30Y/aQOrDYYqsLuGz/ClPKB7V5FoV1kqxAXmdigi7qM0m1tNUxwT6faU82405xW+oDV8a2OXAO/d1qtqzGeuqPKWw6zKTcT6pd27bKSRdxpBGxOHC4EVXti796bPZVpTpPKwUe1EdXOqi4Zih+LhLlWb65h9gl5IxLesQ8dj/OeK7WG86ObRFwrlSBzWc0UxwH4qOIU8ipv7OP07DAS74PhfmzGZKRDK2hq8AHzofRGCuD9b+4TAK70xXJXTrBPYUVzdfcA7lBBPuLSAdwQBJW4peRPl4IOLhty2Q/f7ooLdC+whlkCOIu2axsbBGEm3NYwGRLBLdCh5+jAMOaO+HHtvKtFKFNnAVjnkOanxSPcR+CICjvgbEnQdsUJ9ZkbqcmTXasCtkJ1Wj7MUzihi+AJ/TzVnTfx++HrC+1/XRTNC0CJiLcBnsXVoXo9IK6/3vcXJWIw8AjchzTqBH0UP7wnVU+aEZGSn2GsRT383ruX4uA8TYY5M/htPqxQtfApRW+Uq8zKQt+YihENLr0LG0n1Dm8IfaTotxzzCYi2JQtvkfHXgw6zbGfuQ50MeDbnXFGd8xEMt2IlKuirCR2ShLmNWs6aN/QSwOv5O8xv8vV4NO1oe24yBTU8TLwAtwzMC3//tbBW/Z8Fs1Tr1Bb5odg1y9ZBTBs42SpWocjJ1AjiKHT6Gjmqzlrn/YcsSdS16fft68xW+b3yjnF2qUZ6TpxlgK1su9YqYM+RRBPGZgj7bAz26P+22aJ0ZJ3HcA512AduXBnFtnqd1qFgq3czrDE7gRJG/910BBHB/pm0RT52+IZbYnZtJ6hJ9kofzLWnCLKo28xPBc/iiyN3ZOrRZc+D4vy18ZQj4j9CzNhxfPoalMEYRu7P9hul/SNZIRARhx45jR1zHfTBn6aVFbDzcpF+Os2LdbBzqpp5Qc0CovaYI3QN8DwPB2flAaRUObu3wto9Vl90H7KmwAw/rEWuhboM7AE+qzcOO4nHPREdJiPBpBzD9/zAs2HyHVmNLPchpaFMRyGURuBnxzOuji8B6Q7r+ghZJNGGtGGQARHfZhF6XU+Xa4+wcaIQ9e8nmjwI6whpF2J5yLGnOh4Lwll6293wehdDW0z86g3VhVloew7cFP4IxiqPd40EbWIt3bJOQK6Vtm8HHnzMqayjz9z+KxhfJxELfHKg/U5KY0806T5//nGnVAthmmjQ4QRNFxNYk/6zY9fSrFHZOXKVg1qEvVhuQF0tivHvv3dwqR2S8oTjaYxVCn50kkdiqRUA0lLODpSFrJuG96DRvRZNIxOVq7L0rEnsurxktCXF+Wzk/0CiiFmPcFzD6rukxb25svgyfAD6Afsxm3NpNYgmZLQB91wDk6TRpzJU2g76MsOYko5JOvAK/v5HKu6DticeM2bPLT2w/ynOTeaPB5Wv/OWxl3v7DHqvZqem4n9gzQGf81pD8ktP2Cz8rPWANEeeYqK0GIeungFzhb5fy/fgFBuxY9cOI8GHIvJ/7w6B7dmLDo8wZyihF4EpAT7ELbkwAgTXwMaiIODupdBJFAlhz+o8Qn3TYk9Btg9UpmCVylYzE9N91Dmptk9OrJ0RS4MuY6e6PI7bHY3w+bU5cyaJkziYYCBp1PWekK7Qv3dl2acKQoXku70qrWsq5aEp3KZngROnQuImLKCCOKZzyTp9dqEkIaS3qmod8kod1KxZhDpmPQq4SebzN4Y0ieus8/AyBCFkDf28h6vTt3vSjeQasKfCvpUB3Afjqnhhyr8t+CKvKaqgT2FEkL8KOHarujb5z8ljkQmLAdiG2bmCB+VXOMTNEewRuwEEi3yMs4IridE8hmkgz3x0S55p/CvFB0mO3J7UaO8Qfvy66nr0X9bMcjlCWOWvLzsMxpwyK5l3D55dUlLkbqcc5O4GS4uyHrE09uFLgosjcbzciLyFQdhBb7Y3QFBJWKwavC71O+vaVy+PzGa1mRgFWWS3KRfX1luJrzXTH3VHIQy0CkF2CRjP/AH+NR1wPksgafazFcvo1Fh3FmtDVYrUnQrFw2/7g0DN8SSqdc57cjMLMCeQo8na2KHyCVQfXbWqam7aSzJDg10Faabna7Em16sLKRbJ8S9GyF9xwE5fcvHKbk81cGN5LRL6NzqqByQ9trA0v2lhjJNghyOmvNhd7HkGUWJ7LDS5jYNeit/pyclZKLJmWnuW2vHG50AmqqFHtWhgl7ABim2rNcvJu4h911kdU+Yz2MkFFb8x5Gn8OUhSNfwFRByRrxToRn+0NkyWnV+btgZ6ygn//fOe3/W2pR6CN9kjW2PldgOQRvh0LbRkE/twl+OVHfjIubK/pbuDyvFQWre8Rlv++z1uKx79UXYxLil1O/2ePICd4eCM6aXzljGSZAHt2brVIr/eqZkwXF6TeUhz+xygwV2hbINrUQPZF65rt47vrG9Y+DbT0AspThrPXpbmWl01cVLaxdBLfKJK/CViP1UUX82cytMC36jDt6Xj9KLduM1Aa2HmToFywe0cS/7P1AHaBn8ONIgizT7NZRZneRa8lX8yxgucJdR5ylYEcRfwf85sbtj/oQ6zsvZRDHqp0GXecGJ08WTXoUzTatt9sP32f4BXMHKiieP8jPVKfOWsFSnZEx8LV6tXNhtLJqj3hwiFWgQNlvjddwB4lCpzBBDuGMbtMovEj9p1OQA8hHrPT0cpjPdnAK5k24J0RHLWs7yjd4FCoEX47wfbg5gYI4m0+dT5yTLvoWLdbnmxa5f0mJ0GNNHzRAZfGa0rC1omKO32w29Jrrm1pKvfiScbp9jXtXkrTjmaA7iXm0WwV4R2lIlxCFCQRO9ECm87wfsbskWXcQYNhFxZ/HsuHjPuEGpbLGOfrOSc4pLSGBgjFZseh/kocYfwuvc8TIp/hyxODzSUBV8gBMo+0BaSRewNy+usIwYYdhAj7tq7V4LojOavrpNdL35l9lhGQ0lNwHnQLoKOkBixQeoLVZCwCQfQMl/gWsO6LhXXg07xeEa49I7kuSbL75unHjl7MipQL1L2nlIZWzG8gNBdkr7X4bKFutlNstan4yPsiBDFQq9c8KzI96Rc/C5+pfE/JDA05/ToLAKfG8YXw56A2VuY1/e8jJeuwJM87EF5IWHuJIMsmSd5TqsMefpxnXNgGy5mkb76l9RfJ91Y5jTpBHKU1XKo21yao3YJ5D9Eg/8x4o4/xrKfYgchjcJXBzpUMf4UEuhcoNCxJppTQcC7x1Wj2qY9FdUI44xK2VvONQ6w6A/PKWQNf0Mpd95Lm1CJDXZUVCCehjlIg9uO+uXaB5bKWhCtMlq3CUdLFFBLNUsm6TcOzT/76vOowwtEbDHE8Zj/jt7MPtGcWc0VAzQe1jcUZpS20YggxmrGzSBGlW+ZdlrRTUSXXGfzO+48nStJJ3hwxvrPvuFT4o2wdwfxxuhuAnhT3iw7VK8YeOfHxMlPgEhhRusCB6k6/spZRzi0APVwhnq/qRYU3qwoROD2qFlH1geL9r/rT37XQ7Hj6O5bzITvisgeUL/wp73TSGme+WaLKsGU+av0YviievzYQITvA/4c4cH1kVqYIQqKu5A8suD978PJnBlyV7B8okn8/nChWB60xGOEjJNbbI0QTuxb3ibM4EWldxXzn+awUXkwCdTGI+4Fi/D+OlGYXWN4TZ3yyAlxea+SiPR+rAbsqExUu5jU+UJS/GbCdbN1xsE0uOv1Y2xzsVT9J78J/2+B7QuC9djgh5C3gXSCO4vuPYNzl2CBAZxASfD8+w67kUVurpJe+3bM/4jqX0cdOoXn2rUNDrCK9P14m/JbkWYqZPUbcsXoSP/D8iwTa94S6wP/Ppd8nBN7riuDuZSbaJbij2NurPj5A4wKvsMMQdndxDZKHHbHemlU28kpGjWQNcmzcNpUTYoSic4+xcPtJtwXhrZz3JN73dau6Bgwbnf4tF6vnv7fLqBh4j9zi+ZKdVxQj10TIzZy0RqqtukRA+x651jJrKzSVulxo8WaAP5wyd15RjNwJCEI8b+hkwoVOr+Y1VKDY9odX79ZF1vPGrRe+fOwgXe68omi206QDrBXzIaZDUp4yE5BDpWQ6buXREjKx5bWEzUUZxaq1BOZFfP0DLu1LPtk6QqvPb2YdPPvEuyGPurB2y+kRt7mIo1i1jxFAh7UCEdt9wPKx7TroMLqfvPVI80ibRxo1QmsyaMQaagjE+agLwIfXVjotF+yHZhuZ4z+L43Yej7+SYs23ly5gRl70nMGszmWsqSssB0KZxQBhrT9dzlZYLiTEOXxLy9gJFLI57PE1jy+Kjz1OpOAh20vwvYywFrMdYL7RZ3v4CoPEWgvI58ZcGRpj2fk72oSjsiBzwmBQ5Oye4D1ldpvsJmD5Wnpj+rvuqvbavP+zJ8pCNjb9MYPv+Nqmpm6bEPfHEdvjMT6fNuF+sLz0z+UtVNI0uaLq37CDUk4QRbH603+R/AtrANZPGkY2q98ABJOU09+tCj8aQji+4802JCM+0qmKvotXVcS5yJHbFMt/Ov2q2AUmQ63s+LUv8VmnkFabrWnyTn/VTdjKq+KeulgfahT534Ig4ZJ9EnBDGT52udVN5hlzLDqk7Ti0F/Vjji7CGiUB7MFIdNlF0pkMcht2PwfaSmTYXd0I5gRVFM1/yrFkx86QNVQYiZ4UNgVL3Vb5Htsq2UwWQolVeUrRSYbMuPAZi1Cxc/w19NDypddawKLo/LoGEbHm9Cs+p4kFrJkZbUt1MI2ARYUpmQTtJGINzW83KDl6T1oXSZOi+vcgFMxclp3+hq/HRl+Wk96ewO+g2C/Q07zte80NIDWchDuK+D9NBvicVaevov5ISJv/P0s0D9rcOvGJ0U71wrWly3U3TT6UpeXcRIcgF4Fuh5IDzDJnB3sD0G0V2pijzbdz3YiqWPW2cQ2mi8C1Q/H/JxDhkwnYeWJ+RYm7AeRdlDqPxCCGted61gxbbx2GLX8bpfiYRdL/iekLBOVGdcjje6K2yDn/CrUCnn/Nhyty0B8SMyDGaqbI4rZ1+6nCZxum74qdic76tVfZKv2MCLaBV62dpEeK1b+EG7PzdsB1CKZQtWH1MEo2T5EBdp6xCCo6afHCM6ETbJGnOOWNCiPF9qOhoMw9YazYNb4Z3rn3/lxwAupgS84a5v/dlPDlRfHCYUdR/ucxsJ8hgEDFNuiwHeiLW2CXfBxZO3GXdXbKxXCSY1e84PN05WcrqpxNHVgB7exQosBS6C2iaxF254EYA6vhY/u8tgnVZvgUVBlnLqwKdjIEgHDMzhBpEbGyhK/JuvOafOF65fmcDZ5l9AP/q5MpxftfT3/rxEobH1HsO6e/WmjL0ppmCqip7qCrpFh1ZqIyVsj+cFPRNdxrivifKZwX0686S1unDr0+GnIvqG94mWl1CeooreAY/2uWT9rYmVqwy/Ksbc3ecMiu1O3a23Ol3jzx/en6KKMEgjMw5rT4y8jq+h4ziysC39zLjPw5uEl0mtStm+8XsmYS3rukLcfc60Jruh2HGtULu7Tjoop7TWkHD0zcBe9qmBDWZkauwv4A0ozIKUxEDpY3A2EVSaReXM+DK0o9aEy/dk2C+YVH4n5+anEpOOlF7cSaCZqdq2N1Nc6hrxcbvJ5n3fyFZFAn4YwSFs4U9DGWRT9gEXr5ie1HGCnWBeCzTwoVBTc/+TgHNkpOuNt7amBHGRInVOgA9wv0JG9jUjlN2nkOHxYa5HyMq1qMo6SEnyL8/qwlgjYMFDFve/lpr4kNBAa7e0u+hYXiHFdUiobdjud6KwQ5SlWo8zAUxjN7+g+qmMuyQsMHG+PHwXJPetOw8/LVcwPNSUqlLd47aqhYU2hiHvfSvvlai0FCGOcY665GI+qnvH8AUW9I3yDVx/+ry84T05GC6tn8batxyWoytluBfLZnhebK7dKsp2Qky+pCzkW2fEOJBXdWaCfKNJl2G5qhip6Ow147hzNtGVNkITqUX1pPQYtcIeCzi+iUTWgT34PSHWuzc/ZSxUixU1OI6WT69/Wz5Xox7d270sQ02riqytBzEtUopeBOnGK1wfQrgb1l3nsHPMT2APp59g3eFAq8ipzv9Dl1AX2UnoAd6GcIRGjuNoWxFMRFu48HJ+xw+o+YYyeapt1a+Ayitrrn454QgmUv56rclToBH6UqnOCnM2YXIAOC/Mia/jhN4tyzHzTknl1J8JexHZZ3lKJwZF66VKyZ4Ic87BOepHqMX5EGi9BJL199wtIGE3TclzwWnXVRtzkTR5XldZ3gjZISrlRgBsVZA6IIwi7hg7Wwg7xgpiDxxeUYAClpaPNmWMUjjFIODnjXfBwIsb4IeRwTR+4yEIY9RaxGOXrVMoaxQuDlBfg5cJHWQw8WkXXQCr+lJNTQzOsph0m7nWeCzQewl4KxXXLfgIcTLtleEtzgA7e34Cmnodm6wfdjF8vxtVtku7n97hk8bjNYteqCy0VjuUspBXWYqAR/BGCfmGiCWDtSN/gQ+1wEKYid8dsORLHk7KdQ3GexJ8TZ/bjkk88SLT80XNWE6QRvFIe7LwWf4ONr4p+GxCHrVjI7OADWAahLHoY8x9zQ28oEs/WOqlS2pXQCMYqoPcVWkrNLTJV2rmyCCCfsPhLZY0J70z/MzFpX6Zt1kbYZo0JV1qOcFGYUKXsuhTl/2Lon+/MM37auDTBz5EoaXM9e8/shWyfoopjYq7EWf8UMcMgRX/YFlUafy4inW8p9BGSu0+nFpsn3zydz+nosN8oo/vVQILoEa/RhMOIxdCc20j5BfKN0uh77qSuwHsuhp5c0kr344zxOAhlFwP4ComtGhqgjF8ZDzWwK9HppKem7H+kTBjKXvqOFzAlVN286iWgUJVuT/F5KYqcq7FHe3E0hIb0pcAFaRKyF/UG8dWheY57dqAzwVWSkO6PD9LX/IsrekkPdAlPThF0IPkhidRsNbJQdQw9zg0QApqu0x8wCVQNihUwCeeClgEcRtj8rzDl7amts9tQtzNW16PXvG4AFJbPX5e1ceKNJ2s0ZyahqR+AEYNSA9wGXYshZa/qrmai1La5anb75NWX3suRcVDNyecRO8W3kuVFWRqB5esMJzCgh4AA6+LAVqxt3b9sx/kAmATaYYZTuCxYd1p6wN3hfnkFaujeocjPqojt4S4kDx9iM4gdTw++hwrGdPxMdSp4epK2b+Y0HDmQ55N4VyqvtOuTVHoc5T7Plhh0lFTQhgK5K2J5QQwt0hwgv1bYuGeT2xS1Y8iwL5DawS3CCN0o8qBvTNGPiB30R2K3pfal20EhB7pSzJr5535VuQGxzUslREsI/J8JsQ0Wd/pgdgY4DIHaOyby6Hw0hHN+dOlgnrT5vs/DCCV0n+KL0gxYEbUydrdmcmi0h0LelLrkIcsSxjHKtZHGskKNAlR0ccgI0SjnA4KXH7FCD3Recct6N5gYd52mPPr+Z9V3sE++GPOpCDg+FMsYzv/jkCGzvKAFhdoqx0YfO9Hc7XWZZJvyIoXyhnanDo0Av+ma2iwbhHSUjXI6TUEXJgLMWEPeADhrsSg3G6VMtiDcedkQOdpdGW8WmPjaQaHMS3ygZ4QREbGzUJklM+KjNOdwutp9HMMpDeVSjbnvx/ghO0EYeoOWYYQ6V5vFkYMPNukkwz7JFxiTh+uEm8hLYvd/aqQbs1t5eeZlQe58NNdIHZiaxs/2uPSnZVOYc1WnSliId2tYzwapKzfbCqRAnVRslI+zjK45UaDcMVyqRKrHE0o/D6BZDXk4PmPdFom3njUPtKosQWR7eKtuUOsEXJRscQlub4z9NFXXMWruFs4wpybU4XRpu5Ty/7TuBfKCi9IFL6CZsT+OLiQQVueKYh30I2JGKo2GS3mRfdE+oHqJWsGreVjkPrChZwGwUSMnZngrViJKc5oc2SL427956BWHlydq1sZatDHwSMlI20A4SieHLojIWBYO1Kq+S9ZUvchPPBcbeU4KAOajIDkF3pr8RhNmin8ua85CFFvivHR5VydIAfOeYB10k3w9RkESsATqKzVStHcbmTqTM02OHB+vi6tnJfn83xVH4ovj+muRfwPwSsrPpH21uT3QvI2HrPBKDGJ46hO3ulv8cmR93TIGPdBXqdsfsRCXQFYSWmeW/11ThpKJdpb/S8yPxi1wMSCKECGsFIrYvd86TWvNcF+aEMI8HQjXq+0ImL3yyTIGNXgfQHaMEYf1DHLzmIZ9YO8NXJoblMAutUrR6ESM9TkBFzvxDBJqdU9t0Z/sNdiY+B7xnz1wIKdePYGuu0pXHZmOzZv6dFFwUp38eINRaGL8GeXNlgyd5jiSWMXwVkhc9yTqPKYrQP+EjLMCa0z8wIBFHTjg+asqHdnEfvZJExeNi1mJnuSm9ohOY0f5AmDnYngGbPcGzSo28wPI5l79eoZM7bytyRazKtb+L1PmB4vmPYZC02Yk5JUa5BtE0bJ2HN6Lz1BNj2y7P1xVFkPlabQ5wFPU//VczzMOa+JwSPiEuOnEZA7sWvfS0v33qaTn2PlSa5VguX3oGbQFn5GVYlWBirRup3MJYasr6R9fnaKQ9ex3nfaocwY3i/A+hbY5xGvsgja83sUkPYd2nm9sVriTAMscT/epILhxRxH8DX2gSZA33fMJ6nx1hP0Du/j7CGKgaybFIUyDPeMxDj5IBWiBFn51POtT4otJJFAlge/jagsS6h5JfMq8G8vywhiPgkVdesUgTkfFBi/ptu1qjTjuteVeYBt/mzM76vmABbJRW0OL4sbZintikbu0zfEmB6/FnxTLi25prS68qYrlX5TjnhPqgJIULfH74kTX6oCVxOTGj91w8AYufTYSP6duB9aVg3H5VJBhdnrgrEotV1h2cYJHUHdoqacMA7oys+oq4hoF9BnEzqonvUOkc5G8G+Lyl8sYl2tevKGXhEN+1TDrADoHHlFVaA3pSgBYpgNVikBDmUecLTbXbrxxuEDxyQNJn0xS+KCGhJvnnu8MqhyrgETtIdAzEkvBsJeUX0NBTkzTdOzfcVkkGrpCzUT6WLWCNXCeIYyExV04wNNkiaeZR4gvVwyDRmnQmGBrWbk89N/JCkEfpCscqRtwJObKV0jOFqAx7ZjzkQJlJkBT6zuU4GAoYqLVZuc0hRjz7Ow802khojB/rJR+HSnbt5vTTrO2UaVE+5x3sghvR8ngH0UpXdTOqk+qNvFYcDUCzT+pzhxjabeBbVyNr6eAT12ajr67NC3hqJm73bUkwlz1w6WG3ADtKaqjJNj4sdqmhjz+IOEUwBOwi2IWeSzkFNQvrTluWJthltA+VTa1OQEdJDidjydkxNoFDe5fvCIukb2TuPM0mul3Jo7ZWSa+/bn599v7Ul3CuSjhKX2goxFkDgmGbS2LjfYWEvy9HXEdtnucsY6ERzuWZ4yW9anYereqwm5OARokHP4Ug2OH094A4yFiL+5LHGBrMMe0UxHJfaS/WGub96ye3hvHEbi50bVPCwSUEZqCDaw2x3YjOpnY1fjzplb68J9qLbQu2nx5bG+j+6ARbpGigRTxhNdmFiJI8L6GDsZ+Zg2Tw0Eml3a3OR/hx5Vh9LyOl5j0VHNRi25RicAZxHz/TPVOQxXaSNOCSvNNPc7aLUsITcmrbbxy6DxVFcFQZeU5CHKUYNEELxQ6FtBWDU5iINIPbxL+4mkwrFmz3ZFoptHZPmi0gipIGWiIA1koiwswKXxD+JrO96R9RhL+YSt+k4FVLetHDFNGThjMfzSqHPUonOOBSfGFNLiLChWEeXPMm3TQqK8mg+YE1JyUbrQ08eEa2On0JPQJwlwiDumFsWyAnBPIep1CVFXPeAMQR6ihxYF8KiMyhMcKk9Kp1Pbth/EDKLrAdoVp7BnfdpFqaY+xeisqBNkoiuOoL6Cl2/pl3Cau/LGrtsdc9yxrYPP3hIqpRCsH0XzCZsgsef0FAKeoGe46jsvlM2rJiXMmmJgvBnq/i5pG3Q6kH9/RH1uWC5QTvJ9Gd8Ft2qrqTJ86tZT9hXF3kucitO5S28G2NuZloDeOtTCW+0ecy4ulod3LNTvCFa/F5sC72Nmdet7pwcxLoKIXhSgUBRIpdJm1BbFdl+sw3EKag88jwpURZIe7NlW0UnKCLUhEuBI+1YhcixAhmz0lSSkJ+YJVSGy0EWL45SGGL0hNOTWSaYORS5Ayuj1w+MeaFFyUZHArA96zY7KwBga8LwBfgoeWT4lJkZSgEUXS3c3whxWRyv7ye415Ga/pHNxY6xyHizcWXlwNSEKPkgDq+hy7GLqWTycRG13Eywp+RRCl41UamSgtXT6VtLrp8YlzAFkX+PyTGA4hFB7DC8vDyhf26AKNY/wdKAiuvOKNxzCzuPcZ8gkxh7DV5sIBrHowxQYY9YsCRi86iP9qPuKdtk0BbVzzfKc2A7WaexnbB87+meP6m+bEhO/qcSPxBXQuErZmwGaYnNmqxnH7FxKvmLmc/If7uTRPKgD+/wJIPfBTr3xpxrTk7Gw8JTZ2IcAt28/h2JWudrIu8zZGXqgw1J5mWPGmAj9Oomfh+wF5cryVfDBLTPNr3e0FrxbayDW1kXDjYRA8OJ7ii6P8j0CJiV9CGgRqJjoWsTDs1cvr2CVPom9flvz9VWRLXSQal5IFTlQTsqtMH/IZ2B1FPdCh5OnU2lOFF9Pg5GofKeID7xmEOeZR80OKia2Z8wI55tGpwzbUKc0xAlrFc86Ru8dmUEgwuuCn3D3jXfCj2GNB3V4T55QGlQzFgv0BbT9au1TZjmruqQcsJvijRoK6hy7CslyK0zTisvLhwjUpEsZI/ljJL1g8U2YN6tjeFPkpR+DmJkhtWG/QhwIhgd6GrLiSf8rG5DnSe79BeKROpP+PoBm9vKHWhpuN+olktju3WYM69an7ZeEHQesq+oEQmClXm01yU/28o3eAnPVDs44QT0FpmmtaY/toVOdZRNrlKqyyr4SRwUbrAMY+wrtnj1Lljet9kXqbyWbGKkcsJuCgl4Aw7SwnmWRMTHd820QsjLspW9fvhDhdAo6SBC0ikYjVq8rGpQut8T1N1+fowe/bUWAiufPCaw1QG3y8i1oQblRCV12GCzw+CodU34r8Icxy2KCm0Cjlj4auueWxRjP7PEEXYFLITY+VIjaMZYxdLJD/lPQinX3Oga6cS+TFLJfcjGT+CN4rsr4W9JGKHSWjP/qy6BtXCutzcIGD7oOP+XxMY5Ljbk2XEXTIAelrWIQ4pUeDkM5eSfZr+j/gzt6G46tLAQYPhb3v8eSzl/fzk8ij4ukjazKWJlb+M54hOIy8Yh13NxzMrF0UoUyTnMTcgmfOee7Hg23U5y7EiCvoD7o+B3C6lDhzNrt2xOu9rTqihmYNr+U1wC0Wby4Ptax1Wqe44hxOIUSLBAYgBxrQBEOajdfzdFcOJsDYL8sHrzdZOBrxKVs6tha0qB7D167Y32eiiVIJTmXRYAzABErZU+9EQwrFKmz/OTUSu06w+OxXix4QK7gh2KYmggaUFdpgtKToDwjj54zC6FZ0+u1K3YRpfoMMoF8Do6LU5OpRvPVNAoySCn/F7YYo84Vi+2zGsFSdx3AOdZj9ypsi3WSlyBif+JTblS/f50OYzY25Yvc2GFaUSNECORMjq+CYH3Ox12rTGBeAjbCudDmA5sbW7tZNxemwTyq/qlvbrQ2w3G2KUWHCpulr0FLsUbS6I42NZe8O54fWuyObR5bJTUQcGKitQrd9OLsEcJRgcAo8hVGYAFj/8UNioozdPrpTO48VRKSPHDZxddFJ1ZWwBfMZP71AnxN2AOoa1fqzSeXGRr1i3tC9B1bWixveVV25oUTz+NcjZ/LQ5BDABIi9+j0XzWVFu1USOEzvVYLy8RZUDtL2lKPxr/EW2J2QP9fR/Bpah8SNG+18V7BX0vizFl7+amAdp5Klho26zFuAb3WrCFxEIu6U8vZeR5sf9+6Cl2WpiB41NCW+FDAh5CnYOcBS5X+chO9GQ9CGxtcm6iWQ3SluzGCAHQue4OLHp5KvPnimIUSx/bXbVCRIZkWM/iQ55oJK4nwJZcxYubu9Fp5eNM0/yp3BGkfy1MFZmrvYQi48JScZSbnpziDvXcuajnGv5vCJTjn6TrnDsUUrAVV/pHsaVI9ON2u6ONVP2SjPvnYLcQy23CQVbIesDvmCbQxolCDTxiXLFWkPsMDud6b9bWPtonkA6l5p5x1GOpacyJlJ/p6JwYJFrAt/vVDTMMwipvU3qDEpr+KAFvFBs+Zg1By1KCDhW+Oz6+InWoiE7xndFNQLmX5gziOG9ZcscwrLOvj7lEPb2s4zFetfjfKijNIK7gwKs1uVShNwC3JVWY54m0o4geI6Za5eHXB/tRuvBtQiud5QksC8FmHtOHcI+j0ySCCwe8i7H6i3PwbCNTZZVRpeLhPmOkgHqMIxFFPO7m9MBaGEL6DMJtGMNYVzUznN4tVejoyyEvPCASwGOkgGaKsEPfNjH8kpE0fQrQZ2BNFhMoe0RJxA3NqL51nIeXaQCgN8JNNuXxqVFJYRRCz7DGJ8w25v+EUX4y6r0TQppBxofeajynAmoRnArRFL3wS0FP0oYOIaOGpoLdpOJeNzp4B5WeXfnOjcntnkk5UMSRfMbiSkUynAQ+KDsyv+M33YgiiWf2xRfw5WRXorbHDnTE2ZzOKMtgsKQtczpJWIrjuD3jQMoq+uk18uRHt9UIj16/zwXYKOI/9NkAOw6iejDOqvMsufnuNfC3ZqbJm/LaorhpxwXEEfpAcYBzTw/0Crp2AUZyczmNterRnjLomUzZPHqgspJGKPo/lPVN1lzDyHFY4qTFdH9dOy856yIp79rAQwzymEiAtDTf8thcZYBsue3LfCmesWj7T25EjD9rRMrzRBXQGw31SSM7s0aF5Ry0DEMWFNFHXX71Blz5507kakIora6Mc5F4nxP6QLTf5EjTJrMbAVPf8OXNLGQty/x2aZrtMUh2ycE3c62w43gLNQtr88qS9c6QRklBuxBKGRfYSrlg75dnv0U4pNkda6lSG9vnsJErF4ArkiJtmQsY+MWnJzkTUoKOOBSiiFnx9AZWMhqqECx7Q+v3qXpDfyFVmEulYmGVjmZ2BeSHZ1gi3T5wcci2BXWrjwAwmqxFpmzXtdCygIsPgtNk693y8pmVLkZcJIwM6b/A4hYkyehIBjbU0RcuiRrJbOVgFxWxruVSJdZveemsmVOwholBjT6xoeFNWGgosjWnE4TE9UIj7xa8oVrnSNnZuCrfFbZhWyYVBdxTuIZpQiYHRNhmqs2vk9iC6ABMYQPthsLF8/n6rcnxJzL4ewXP6bhBHWUKvAxCmD6H5KdmG0BYgRtPxiqOzDOQe44MceEkxyULY24Z6dsC8FXZTkNJ0mUVAf4rYjYnmq3CUeN7MagZTgzCIa5BM5CY9qH5+sIXsb0o4u49oE8AABaj9knEQ7slvSUi85d30kcQ88/f7bJsa3KudNFePtACQNNiJRx2uM8vFXKXkBvgo440YYe8JDrNvQ7T90mvHZ5Z6IQGdQHtnnQUTpBravF9NeQXYhOXgX0godgfpvX5deel8h94TKnk2hGiQRHSkMsEtZUsqtG8Ggjl/1xMozwtb9glPnJxxTOKMGgKTp9kKw1QLzZtdlJrcYO8YekwJXPsqVQeaA8/MaGubY4SZWUQmAcECKGnUCX0AcyF1Dq+HmunSpLyN+++AViJ3ijXYIgZmaOg0vWgKF+3N6TEXlyGGyUMXn6jc7CMye9M9ABtiew/Or1iPsA1I5KbWRGP3LcByh47NGHs2qFM0oaOOV3xlRXWkURabCnTciyrtDxSAxiWFscWDeF7jocevTcrSvgUbLBvhxg3qpjlFOxvVSw5EBdU0h5C3m8a0vK3RaJM095zAHtzStKJDiX4tY87l/Gd+5nOfWpdfdXaNBtzoaxpz9SmKNEg2uB3wcTTh0fDLEyRY2tNfCBqFEet8eShrVCpAEfzxawRWoD079hpWZWNrt250kh65SPIIxzyFBv6VKtItOQGYaOHlELiKJEgY8RQIe1Ov1AdIlgxXk3ol03fsZX0GN1Nc6RFzPAtWYf4JC29eWZoz7gzStKKdgTvGdsX4ZDJXPfspvfOX5K2D1j++lnbvMgjLYW6urp14gdgu5MfyP09Mwe4JDHcLN24ix1ze+zZR44UQLAlQiwYJl+5eyCB+3pV0kM1C7uoCx6bRzBKM/qQBUxtWkhygmmSNJfjbRiv4xUCJrb25vLHNz3I0wwElgtgK7SOdpHGljP3j4u2Ql+May/E7xRrP+h6ibmoNOJGoMUQ5UQVb91CvHkGv++jrX4nOM+XRnD18seXnQCLorZ/6jNwKwKhD3484vQ1mnzb5ZUm0BOFDLz40PYIsq2KVrfnNesq/ZEEBdPmiDCCbtrBuaPnYzxHyu2h59fl+fYOim0d/zwLFdOXoR5qItOcpu+Icy/mJuu0kLcEueWg4ZhN4zRY+8HQFeyOOerNUehjmL8z8RAQsQuxuN+LKb/w24PlFQ9a9asNf2jGwutcgjlZSzWXvwIkBN4UfT/seLsU1/MfQp5Tbc1v90YWckfr3YIO4r4N3eeItYCIGbOkl70cCxsDm9nEPVHRuBkrbWZ/+cNai+9UnMCLorzb4oBl8vMHC+5WU9RHayoIR3X5hbsnlJccrgekLX45I8g5oNYxrngvolgB1zrh/mKxewJhKvGeTQUMUgex4od4L/rCMAfF6/N225AkeYnylJooxSChgqVZo0+DCVhs7FkXNb2QfDVmmd0s8FHyQW1RE//HcuuGn4vwpJ7Hx8Avv9+PItog5tEpzc7G8p4Cenxj2Fw3aENh4sqSwq6TXXnc5JgKR3hBLRke/i/7gzd8w6lFec4Wq2YtxxvPskuIm6HXBUIQLMrDUoTMx0/dcWDUfIc2j5BfKN0DoyVVHb3DsrFQ4uSDu7GHJsQdcwTsMDVGvKJdXD4SulcW52VaUMLca2qciRzkTt3KMngE2jNQ3YC+GOIo7BXKpEqsYJZE2Qw/Qc7ONiUNsHvpBQf3SgJ4Rc+EKzBpbBn1y5VkI5r+Z1Fq4GyR96D9XhawBNpHwRfRMDZfhRP/31kM2v1RIeSp00dL+tY+4rhRPRWA+tdkSlz553DtYDH5czFfnQzUOckaZKLApJ/AfOMzC7UraL6ziMOOk4PRs6PG60Du2dvAorCWJVLMyexjdINLiBhp9Pfh1miVJ3HIo2wgwar4RvWeea7M0JbyXKmt+JzgTdKObgCLQasmfTB3HqiDhG3IIoSDHcp0KU5tifMqK/fOFzwzCrXPGH7CKRRMsGlagsz+R1x4kRUpidayzhFDji72w5dB2Tl1EA3sRRzErQo7v8I/9vNpGKzPLcPeajWzpDl3E3J6CH9ANB3AL2mqPyHpd9GwkPCQ7sO+NCksg0a89/ZKTThOZQosyqtjWMnXOS51xSXfwJYoYbsk5CRsmcxGn0uI54G1qXq9Lsgc4zLljE6eU8MZ8GLYu8voC0Vu4AesUJ3qvDX1rLOzm+IUWjY2t55//S3JrxT9mpUUST9GTfxin3iYkhYZWfszLXiRAfsUMOkmpGrqIlrPyQ2Dy/SyAe/15jVQhF9Hti+xWcqxt6v14eA4aPkkTUhdjeyMxs73hSOq8isWdXo5gR+FHl/yfF3PGRHPBrcKUOp6PZtKIw6BzZboFu7NltXNnq+O3TZ3ERl45yTNErx98eJxAKM/QzUKOxSpxaJXUNU0Q6gqDzqq/8FgFGE/aFZJ9k65fjrfgmhsluAutJJFAlgzek/TFgLexK6bbAA19hjV+YKncjjYVZSadLXby5gR7L30FWRhFvWhM+8M7CHxpoqhE5aJLqAG5VjkKeMIa2Q4TAvQaagRbH5x6qPH2nTXDYP2sS5HM0Fse6b8mV8wsrs/ioYVZp9DPHlYURidwVZxJRmQ/wbYSxAImRikP/EIgQvfshDZR5q9LiotlyF9JuZi3B7Q3H/F/j8NN/an0WBAaslbfzCGMIe0RbQQtLe7KWLkWKnwBqYbqd/X3tDc11qzeFM2SMttCubO50gjj4SLAbsDG61ohJng8v4buzi0ccOi204y37ssLrNgROkUdLAMf43YnUOXUnMxdJu2XWhg3vuLd/+ZRmrNX/DxF3R9oaSC37G74VRbT/scdnHh2BfBlgQy+enFefqueVAe19keHvrkE97/JCPr9RSGCM9gLSZzjBkGj6AoGOnziN1gymhz0WQwtgJiIhr7FcTfEQ5bPVopG0Gp1bZ+sxJLKPEgQYPB+x8MoAO2MrnNUhufFhSCLvS0J5gh5fr2nmhgWx79+mngV4IieskslEqweyM6yWM8IdISXJpE2sQFoJhV+k8J8DKGM38JnnxsYySB07GEt83Z3uKIDQynPPqSt63BUtx9aqMhb/3zHMALPoi60hE7JJ/6bd5Bz7nxdYnJW+iHOX+m627TfXSj214b+MfAd2bTNDtknPakg8iYHsQfIaQ3E66xFKpFYNmdS57GrpprnYmubNTPuJ6kEQrLbZ3tu5McMsndRa1hfkC24GdbNDRdG3MP7MTNSK6AQpO83pn65rt4zvvG0ez1Ql1u8i+4M3ObulvCFSZWnPRHOxSJO5Hc8A1a7lpBQBrLfyXpl/Ngb4yWob6QSIXBd0uOfCtpv8hWS2afiUGcpdOqtGGjk9Jgbx6+/o5Yp3nc3MjjvRt4bonAnatPo8UMR2ZJRjMWes9JcYcKuwvxhLICbQoCvdASDFkTdCdPr6LiJDZT3mnk24OGvhMsKt4yZTaC2wHlkCL4mprgdDsEtMgPgBqozPTuiD/NdcqoctfpcsHJYqcxc4yFmBWnGLCpp04qnkBEl9TDpPPMiLIT9C6wBU1nN3i+PEgskLF9niEX5ytM1kAm0PTwjwGPu5Q5VlwKiPKXrxrrBOUUQrAFYS9ZMzO8M1PiJvALT56GMaeT4IP87Nrle4l4/4zD+Vs2sCiC0y9JYexIZ5NYdf5/YLSog7OZRufW8iptcy8p4E/kNCqGJ+fgTAft1IYy+Dz+4InrAE3oG2qa94cY+GcHD6XHPCiI9ezw6uQ4suL4nPQIuetEyxyGjqxzTpPeQ/C+zNx82aw018l9HIQDnTUqlKplbEu4jE1hymKl2/0MR7F7GMIip0nEqZ/s8CVGj6cL+YXyIh1ILbu9kh51kcyavwqMxQueNS3FI+6x0MxYec3xFDiMknIHGOKdNJfXel71bGUAHMS3Uh/DDX9N8UOVUDwE5+UHHHdh2BoVns/zczWuU6n0Mcs/t7dcSrOd9jhDsnjYpzfA34UErOcr//KTg3aCEugTFb/ny8uV8MuY7CnZHSGn8kuPuZR9Kyh/ccYz3Q/0ZG9KLfcfeoMX/N9SFwXd8/ejPp7rK7gRvG0pxBFIuSshcFrrIjhnlryxVggpICW2yQ0K7qtuZf5fqcsHqGVhZaLnPkuYx77s2It0J2MkbHsycTWzDMj7LFD8Xn6e3VjmV/LdBDH3lG87WzFvDNg+13zCGzAZW7/1vbOGTay7Ahg9ZZ5Bs42oyH1IJsHGcXgnsAYU+UIP9ZzjFyS22MZ10qau+ZpkH0cRrei02dX6nbtYLZ2H7pdiTa0yuqUk5RK0b1NoQeK7UthD8Rm9qB1LNVWYq6UEoJvOYsPa9SodS0wHcC+ZOcJTCYQEnSuhl4aVzUjzazWPDNYtUqJUxvWATgBFikQzC6VN1TYtQ2mZpwsNpYgU7havFxYPWxlzv3QEmeV854TIFFCQAO0xFYSC/xvgvACmPaNFhC1ubVRvgc6wM+6u3rpKIv9LxkN6zfKHcGOZP3706+K4SO94LpDDGHT3Fh9Nl5b0eDlx7AdYIvi+Q8TIfEXP+DsgOvQyJe2xpl5xLcx/V13VXttkD07MeZv9rrAGUnwG/eoltDExKxtfLdwYmI+pW6CglmUKYbvKOdB956i/lsC/z2b/W+7mcxYCV+8UX6aTPKYMW468e9DXAptFPd/zDUPxqzWayPcbmzun9iVO4YeVr8S/36OHFpG0t+PbBeNLIrwr7W7iWQHEMOtvcN0ykUncxLjGRn/+2Ng5af8qwo/F3T/e4ruv4S+CFhN4ouIILQ5tFl/cD7CTyq9p1mfnaF7+pnHsmhN3hwjD+ZIMUDiB8CanTN8wcSkY4JgTKubPys9yHcOoJSchz8H4DCrUrLAUdJTrIUfhrRrNXPgBNi16KUj2ikfmSW7akLskZqAJ2dTKKI0gTtx6XD6e8Dtjbqsq0tzgDrCN9GpKk1bBH1W1fLLCcIo+r8muam7ulqxOj4AYowxc+iiqbo8T/lVUvqikMkLH8VSGKNkgD0I8RmxAyHtkZ5rHvKJdUyiNjJnAMLVPj+l5C28D1nhsKJY/5nF3VCxPRHF/AbCR4Su/WCo5OqJsY0OXR5gcwD7QDL8QzHgrK5FbMuWy3eUWklsdjJ/CsV9jKleEPMdo0O0UQz/foDfP8E82WzzoG1nyrt1pBbgg9g6NC9GWGbreReWsk6vlkzMfOS2UnWJLycYo8jW6b9iO6jZLxC0NZUwm4igtuWhcYSfb07uq6QJ0++SOwQaxbBeQBxhAtyDgR3IlmpKRwjNPLcwK3Icxx8pcYE4inBtgoSwZ1Yx7dFZQhw/4ypgrfV3e0uGs0Kkcp9AF1BGDmmrNrCuoVvxU7dwdshjuEmPytbk1klfSaVWNwKvCnWg2n5X8ruYVSVnXeiUH0hy1hyTVuwgkT1BDJkRYW0GNpCcf14bbJsY2XzNlkIbRdNO/0XyL5hACZaWuhWBCVcqnUddoku1DeBoPaxSsKJo2k8Cu8dTCAdRnxMH5K5UHPOwDwE7UnE0TNLNJz7jruRRW6uk11+7LSh8yuxjiC8Qi3V2lzgjpjQb4t8IYwES0ROD/CcWIY7x8x4q83wjAoXeB8hNOt19RfG5sztye0INLRCSIz+PG28sFHjvHZ40X4G55eRHdVsEJyijeNxaGKtQhKwOGgY20rIkqdpQccnOBNZFeea1abg9O9Hm02rxaXX3FTm2HXbxF56dS3xR2u4NarHhQ2ILZVEnl/DpS7aXgi1KJjhNRE+wBnQ6MCJWTfDjMhYa1k5wznnsYq/8OrxKWMg4ti/L5tFGaQXL0TaHqvndpgQ/jlYMbX+rsIrYchLJaPv2QLDawJRigsiS+5g7731k5zfPoSdFHkepOziXnkJbUfFv4HkAJ/ii9IBDkeBbGnLWNK5SPcq0LOuKbwNBGec54/uqpBd1fD3mAmWUDnDHzB6LYPo1JBYB6rOTYIFK4vQZisdcPynjHYr1Ild1SQoniKK4/lODi4litQA/0k7HzoyZPEXW1skTCpsuL+tkXvndvC0mJwU+rQBEXRUg1oizEnR5f5D7BOt9Wi1X2Hox5+xdxKttirq/FNgd6q66u2gvsNayI9Y8ZuawdC06GOpyxKhqnFz1hrHFI46k8dtdlUh81Gf4DnKDrTV82GZaXmx5+v4FwYu0WecjEbIGfkcYTf/Twhe9FpcXXa8rlBM94bU2rijqvgVBwiVHZA2VTIbEiL+6T4Zr4IqmuzYAVz4fLgCLYukPhRqZ+yNsT7BL0zvmjFkXIuTx2ou8m5ERPbwW4EWP7+uOYntcYuzCEGUeowUwagrxx+C1AaGrqkPUTpBFUfRzDhctLkfUIHVWNZ8TXHfK04bGLl9yzQOMYucfuNRDRSiMWdA6xD+P8oBrc4suj6x5ZFEsfQMiHghN7el+cx/47jEwP7pqngxrCgjWnvUqG+9V5Ki0ZyhS4Mu0V2F1IdviM+VGgE+vrSxL9T380zFr4IvIsy5eDej5eyRuYLdDDum39cwRtiGiiLrVe6USqZLIKtX2G+yXW4Xtw7qoe/ZyrZBNN59U5wFGEft1c4rESEn0za4LwJ+fAlftulVZVHkCo3hYUYS+uWnPDag6nb7dBswKsnTIgq4aveT1SY+qBVRRdH5toDSrdSGwHchafGTOC6ZANUfCPuG+2vYbhwtrWV4DfuA+B6hoc55EsjPz7i1Q/fPFZTr3fb//tgm1fCFXUb2fXQplWYy+ca+4Bnti9RrwI7JnCw95qFaFrrdZ8vazV1ov/HrD+sB6mw0sitA3lRa7At3jcWwh64zfdiCKJaeJsUdY2dEoK1s8e6Hb3E6iGEXuN8UAxsLcRxpTt2nCkFvOYgk+83w3Bcs4p+OdxIoHFsXtnynzA1gdjAwU29hqqBH+ED2mTBI/zah/mUP2LmPv6E1PXOGMovFPQJv7Wl0+5oFd79eVTqJIANvDVxckYTpf1u+KuDxnHjLy5ZoN5fv37hrKJXx+xppHVYcsXLSUrynWvmaiPatF+F4k9Gy5aAFH891lLKdfY9Exg/1dLXJ4pVejLHvkMSTfUKYwRk7k60CE7IJ3IsIK0bigDJWSKXxdta7ZEei4uvWY9+F3CDOKyH84K3IpQpAERUYJRA2IIdeZ3TIirBAu30MrBS2KzW/0tYhiFbGriZLCpvQb+F9W10mvZ5kIa0w1IJ+4Cnv9xl/ZrV59RlH+/wdgfmStTh+rM26bcF7W8cGK4UT00mSGimN8tsaeE1stbDs3pUBb0gP48w+PghvF/dck/3w3cn0I2gzzE0dQ+1xG3PanM3eTrh+Ezeol0x/iY6saxpzgiqL+sZTHDIoIqXNzYMsuzj7hL3TIanFfcuwq01Xad8itA6yKCUw+jD0KbiT5n2DiC/Dj3oOAsK4+Ujc3POxzkXYO/qTkTZTvjE2h9dobh2aIfgjWUblGiQOzCY3zgQq39sOeUTNt8LXG3ZCP76+9zQe5maFKjnmNQpH3oSx9QvYJJQ+8FPAotWBfis/QZz8NoztXxEdZ9eduUqtxU8lL64Vl1zeUZvAzJk7QrKmivyb4Ti24pXqBBUufePq7FsAwLBwm5rtM/+3uDa1jcffsdV2RFK/H3QLuKB3hBLrYI/yM3673CMzVwpB3Vo8NZbhIlbop9fvm68KL0g9+mX4dCoxooWKXvIvfq+sAZWV0vfNzHa5glmH0wy606sTK7g2y8dXqa35rWtNxvrM225sONK9bpbBGjnKLTh84dqQSBqLXtofV6sYr9kbp9PjQp9YhuxJareoJ3m7dTZVsMNBeXt7MHut+Q3G7l8qctGcHIEaaQFimx3XeBZVX2XIB419iUzV3Swu1jEWUKnMaTqIXxeKe33IjGIzAZjSyUbVneKTVoNqmw1bFqAzfYa6POIq+Peb4vMfmFjk+9TAmjtpo0evbh0cec+vy7dYObTv1Y7MeTihcn0d/hMLNzqO7FK12rKb/Idk1l3FARTwaeWajgB3dncBcArr3W69oDs0HvDJibv2A9z4bcxSlNhtsM7L7t3NKOWY9HnVfNaMRLTt36+c98ibSXYpLa+ALTQJ2gQW+fTpi2YZUA4K2Ft3e/Bpo9QxCfRRzhjaKUvsYAXRYUymi/1y6jodvDd+jZ219O5pCGTWKe+f8X9dJaPcFLYiiRN0tds7rndDNsetZxnFIf1DCBawojralYmBnMIAgIbT0FoQ32thnsyOhVdQX1grLKX4JRjl4tFKeUy3E1sWLTvMgo720oftZsDpWVzbGZrbt6dBF+XEsD2MZN1XXZDVeOdxgybJK2NzJWxdzaLsUZ1sLzXh3wi5VxwbafjSEcGztejbxzSndyTHfXUZL7ayN4RdBjjkJYBQzeykezsiFPSA89Wa3LcP0FtS3mznVg5U3pSoeWNTg7McBBvy6pi7Y/9QVIbcMiz/BN8F8HVQ9O/HlTwAUjau3pB12V4soAnaYcMKAir5fX5Nbe0KLMazSkN5nHubdYDq/yvWXC0L/LUXoH+B76PCoo1jDrD517SKMOsbUFBJWU/mvMsb/y6dbPvKOb2WjmYuy/i1tkv1FBELie2f3Pv9qdLemudhJPuBoPqj9wmpyEMDdHt46DMVmpMyXGb6W4Iy0zTY3v4Riv3DdFrYeeWaOY4oUwA5y3xwvlqJ4s1OaAFbV9tFJ/KK4+wNoC3OlMFLSLsaulBZhmv9qgB7muMG0yUW+7x4XcEUPWA+AfcJXa6bFbkVsO2a3On0zqM5evUkB7FDzZFZLH0z/0PGqir+kLIVfLncENtJEAx9nANhTNjFgxYRWRJNgj7DOzsiPJWsqvZ2GQ+CRhzKTDrCTz1zrJOjBfafkqTJPlT0eXhS3f5qIiB1hYCt3vf/aobPxI+v9KkctJzU/xew/9JLX0CG0yOPEzIUl6SMAWPYjiKK1sbUBUzs+YM0h6x1pmh0gStiZka0tXGUZGh8dn7AjLjFyDdZuKzdn4NC3lgsgo5j8n/HtjVkD2hBOpr/bXNgldLDWZy0IY3h4lHN4u8S3iKFPSuhiCq1uDebHK4oGG8Xvz3LlnfHnjMMnjNphItIc2bfjmJVE1iNrLh+yFlBEsffH0FFDxQ6xQCes/r8diZu3+dcPa5bVy4deFXKBK4q9P8UP8wRm79RC1QWYDbYW4EPYOjQvRFgC5KNPlbjYz33aSdaMcyVVRpuLvvEdxenvgZjwEMHCiemJBpe2P/GjFiKLRde2yznpIonWynaVTnBH0ft1LLzMed+usI2hmqAjLqRMM6xHEOSzK64Gs58VzjbTHNZJ/qT4++MEK6KGTmx18jyCKLGOe816x/MRBoW1S7PSIauINtK3AAtQo7j8Bmjs2NgB1+H0V3xWNuRm4GqpDqIL0rZjjwIenUefva0sBGmVzZZOgEax+3MTiZ+m/2gTRuvYNXQj+pr04lDGOpdYyxbfVpCz2QnUx7R5qL2n6P5TpXk4MYflOh1hM/61GKQhYVMY28PvjT+hn+PyEj1X/eyRzBMcLhBGcf2zAYt9LTlBcGQeK6mbb4G/8COuBwkGhqfuPN89y82STYxkLlrM9yTNr0NI2BUPiRXKmeuwxg9o/fVcGl8bsJ7rzYZT4Mpg/wfmxNfHyV8TLEW6xOk4PcZPWrILTJjWDlJDw63kOe2ts0JZtaoyj8EfwSClFDTx6fX5LWuoLxb6sryu66BDnqNKK2N08wBzCDBKHGioUOlZjMJfensONq0EpJ066/iXZ3+hJttC5Yhz1WDX/GiQMxBSSsHMGPtQqS5lFLs0yeZ0x/ax7qXBjJIN6grbBXYS8gm57JvhedeACPDN5yBwPe3xggBGiQVnqs0la2K4t01iZ1JAncciPaF9CWM1G2zkndUoe7u1ncHfrkd67Lic5cjoVDNmOaqbJ104qr+nNILjJIpFaI4NHgHBeBxAAFJ0pv9m23ZKHnbEasYjyxGjZOXZI00WNw1vLuLZB0oomJmvKNbgemSPP5rJIWDXopdG26XChCnMPwvxIay+uJThqF420PnB7YKPL32glIP9nhLxhDWT6d+VrbXXJIymX60dp+nvuqvaq8IbIo02mdoAQvclBrMlyKK0gmMsXQ5Bd6a/2VOQ9NhQI5FxghEMOzQV8mhtfG1kJHuZDcESzFESwvX0N3MXc9n40Km5BxaneY2cFdvbgleCt0vTDVQZXi76gQ+UOnAMI8EuIBCckD/nEDQHrHMt+gmXOYD1gmKZz54LUKN0gk88MmJmC6Z/s1WCU3yXKZzV5Farb/rRlT1nVZJmxii3H4Ncu+WkpIATmODj04KdUI5AJ2MVK7Mi3CNHvOencNc58rtu1nxdlpWVjaM6nKRS8lImhIo1VRhxbQwz7M6TWLqbD3ef4cvaqCtbpPPtgYOkSvK5Kpp+ZYcaepw4lZNxXaKe6J6KVqbVUkqeHlrF59G3r8jjq9AZsCPQWkTEHcwlqwRn/Jbthz0JYZdd8pGSSZxrsIM+x/rs4qe/+OsIdBR5e5xEyQ07hIlo8x6psTeUVL3Q8tUT3QnC7lR1J+sCbTNsQ6tbqDnBGE3jmpzZAimooe+si0zTXyX0ckx8l/Ew5ovR0Z1giKJlD8VNzM51m5g2y9xOqQWYMvH1VhNDRQUoT2DMY4viZA8T/BhHZqJH39Osi0PbPLwRnTR7kfOuV4ZQXr59p0KOfVUWaw7Wn96+okjZUwi1GrMmPlYREpyFKVfTxOwR55qHI55nv66MkczzsIWHMYqHXbbBSS1qziFsP+S6h7/QDRXH7SQHU1FGmPmK3gnUSDcXhU+vjx/rXmI+KBtvD3cA2KH4fO8cOq9ofp/deMLs6fLaVyGcf1XJCifJk2L8r1QQQGQKtTBMOphBLdwdCGOUgMhLl2s1PRG9MNdOQBljWyELAX7jJIUx0tTFFCuSXaqunv6G/6c9/nPQYD/F32w1FgT0b6OOTxjWdhxOAPmwVnBY26aI/5PPXErWwmeqh9zOpT+F+CBZK946FFIqYZ04eZz1I33fcE3svX9bFuwtd36scuRzAkNKCjiPp7+OCHOh/Sg2vAirBdBVOp1Y94VZGcBgyMzqweAm0Tn22AsF4ev3uyUBoTeGyQk/WiXg7BCSjl3U1aIYP7KZOUwKfKci7CgZ5jwtRqPObxSXAWYu6rttSkg4GIfhLNfiGyU210mxE4tBYMeNaiLM6wguoEXpCD/1FLuEXl8lpBck4Z1cT3Qo+dqha82E+cbh8GMhXG+Vx4Wc5EtKSZj+a9QBzS44fjI2/4bvMGqre1/u+QUp/C9WctOvWuSxUyvpNfRCUFbVvtRJPCMFBTX9W8TOsSclrhBkHK87HeeZPCtjnsyi2Oaw5tNhFnwokaDW1cYauc5D3h13JjCwMHQB+BJSADrBTy4YwsrVzcK7SIfqwMu+iegkI5JHXO9Nkr91inkCVivXqCzN2D57HiwEWNXlJpyEMkoUuATNI/ZRCnti40xYDmdNCGM1euHVVZVreBe42qGY/yPQI24ubOr4VovenaK0ONyIn+U3emsOY4daBFE7r1VtGestz3w5BBs96i+FYnvT34BwaVm+K9fio4ec+oQl2YfSWBtUN0W6KL52KPr+cvo1GLNTaHNItk7BcBO2ox61dZ584Vrn8AMt41hG5u1D3zOuRhHFzh8lPcVaSqrJ9Nf2nRPBAoAOeQw36XrroMFq+I61Xh2gsqwY/T7vCwAcxdnvgZZmTrEuoWsrj5kOoLlHst9u7bygFfLq5kkHC+RvdyjavmaeD/tZSQJutKfZx7bIsWny6gVFNs/cz4GMYu6NcR4+zNNE2PuWtbgvMaJ1mJGC0uQr1stRHtPZatwE8DGteLjR6wADEbL9yUBwwgHoEjomw7bMgbqHB7lgBfprV6xeIn+1seYYnrxIQYzi9vcgENNfQ4Zo6WDpZYc1sjPIaTObia6NDGi+L0jhjfT5MT6NDYhibQ/EFhTQaFeMjYScz6HzgHtNuv9wTFkfRzwyhyVUYoEu8zbi98C3HG6l5M9eCg3rBEYUyV+TQiVsT/CwZ1f+cqvWl2klKf+liUesLeEfMgjwe8WuIVTIipJPiSloUQz/x7ZZQ8IiDJ8spSBlt5V5M2JJpyx81eUCYhT9v2+4sSzH/+UIy1vol1EK9wBzATCK7q+JADTbS6Z/hzbHR/c4lBGuBi8UbL4SW4AaRfT/FIJgl/jaiA6SPopz31cecK3VahP2zQWXl8nnsUXx+0cQTIDVuWkJbRkp446EYTPwX/xA4NpIbsKjbR5tFL2/JwIRa6Ei1oohgBgGhKz0Q9rlxoYyz+2n8EVx+40+F50Ba6iwO/1qRzMe8okVzOrGyiyPIV41TpX4g78uwEYR+y0IB338ZmxPAMZ9uwG40mrM06VZU0hYH2xrGvs4NFfJGlzM8PWsbrnvYv71DcXf7w9AhBnT1SsEo1qgNG8/aOe+MKs86FwEszcU2z+z/DxRkquob3eZc+4Cc2i7wJYhYgc53CzoaPbsdOwjGX96FNuPkM1BizRcxx9gBi6y2NjM0dgGmAGN6d9XOy2+pGDmG4EU5mh21lxePRRRQB1Xyh7Gnn7VnUTy1c6Ld45Am9ho+to/hS+Kkr07RGKmYlkDYpDT/8cCWcY1kha0octljtOYL2iQzBdoC4ijiNo9CAW75H9NeGgHtMyRnrkD08vBtgEzPT5wpWBEMrCgki6wPZUEbUqzJOWksxP2MYrzLMWV1YfAJ0YH+KIY2EMRIn5YS2mt8CHmL71yDh9uV3tfxIeufNCi+NYGaIwQGLpiZXsiNriMgV2LnkrzrXmvv237DLhpMNql6NUmhEn28GEmjvJWUpuAI1+OL6CI4kv3sWIZAKsnnxFJdhm1ZPTrcbM5L2nn2zOpc6Cj5qYvoC0Vu8SXRJBac846C5dE8Ft38kzqvCSk+USZQhvF29/XW6fYKWp8p3kHdfZFG1YfSn1Fp8mNRJufC5uHGkXXG/UxYmfT/z39O1GTZUwh5gNaKU+G+yDmAlmkSYrknyHsasWaHD/Q+0u7j3Gsq3WgO/0amK9fi4gnqxH3gvxTPAZTGKSo+0Mh2XEC4ZCgw2BsjhBKyTv3FwUXqIvfo1j9gBq5kZDz+ncKcvSgNe9hPMPS31x6s0MevTViuNljmH7NYUVWjWFYX74V7US2S5H+x4pLdtYFwiu9CYZni/ABUN7DDa47krO6Tnq9HNRaScfIivQf9hzIHNYoFaDOA2AtQYjg+/JecFog28amrPsMXeir++MjywPbCyreXiLNmx3Z3tJigY6nv4XsgmMLAZqavaBZkJr5uxE75PGXVeOLb7N61I0E3csLcEsgRykLLQjM2egGSHJ0cfkCQB00DEB2c2Cu2kK6D3Tro46SFmajjHWQbbtZOBDmGk4srBjXihMdsEMNqw1Zit1n2nZ4dvCFH8JxseX0llIXWjG/gZCd4w/v2WHuTMXGHqMPAcP2C/uHFPTO5TgYChio1dxIRVpVf8TEXSPxltQcuMI0mhD3VQ/4mIdKaet2SZzEcQ/ynCUvNtztvHcX74q6S17Vus5JwKOUiAff2QsxAU04ufzUFSGGh3QfkXThC/sYgxT3BPE6wCvnPUzPwq0NMNKqPQmxUmPNWwiJjJp5x/eUsyMY5bmbU5ka7pHHdHy1toAtSk+4EDzWijVUkEwmj2gRrpQWmxa2Ns7ZwEmEonSCfQ1j1pj+A1+4fZ8wY8rjxxBUtio/i87wmMqDKUoPaIoBl6wWGHZfg7BncfejODGPJrasWOpKql6YYzWg0MT37l1ZivkM0FV5psNFQnxHCQOHPAwBM2INHy8+RUpkn4PXfLmFyWcywde2GnZl3Mn0tXzRUe0dJQJcik4H37tiF9C77/sWZQBlnbtvmKyzdjB7dhHd+5a5wBZF9TfhCxZanJ1CRyvxxcJWQ4/xY5cIPQnWRfJGn8uIr4bZ64xtgvVy5u7OK3dJcwXzan95Myo0J6mSZPqx9hLQU1lHcOg8+RDhnhBlOx8+vH9yXSmjCKtsinQCK/reahiO2ccAe8rHhbBPmn/pQ/DEZf/u80UwL12ujzyKyb8aS3zYB5p3sa6JlN1yzg09/hSKmKeFpFNIInw9q1uAjPj27MWaB5yzio32/hEDwY4g6gs1IKh9CSMB7ELPfRjfk6tOogi/2pz+w4Ay7EnotvGDWBd7z9t+FqVWetAtgI6i/C9hjJ9pHYI2ZaCH0StNp51yhoFv9UBGKYH1YiQjJ/ihyP4m/lr2RcRqbSlCe/PpjGJk/3/23qa3cSXbFvwrgTd5o0Qf2/mJN9KHP9K2bF/Lx8Y5s5AYFsMKMlRBUk55VqP3Dxo97IN66H6Ji9ONegVcFC5qpv5hvUO2MynGpkzTDJuUAri4B5XOtCVqeX+svfbaPRnS4dNkf8Vl/9b7ujCyOWhzzUAabNgUYD+BT3wqta+LgbQ9GlDBh/O/ZffrUJFZI+ux56FsNaPhOLRlvH1Gb6zqtHTBwyF2QPpnFCsjs6grxp6ZIRsbs6xgCD+wyqLofje9q+8vTfUasAGmn/PvJed1T05L02NrMEFy9dcSvDCa/5xCbCLauZ/FJqyO2dAgxvrzf3kxL+JKtb7AcmErjSuMzm/BTw1IV04Hs7HZGJpzyaIqi0Zhat1YeyvowVj7B1Op3Wgy/xMJSj88FrO2BD+tWVaDKMdWqoad4TM9GRsLLRs94GeMlu/R2J9F5AKejhaCmTkvfa9mqZh62tOnaUW5K6bKYwtj4O8Nynp86N9b7D/d7z3P2qKWya8ScDU2blnBFka0Q9ya/6nRpTX0z9DWp85ZNg9bTlz/EhhhfLs+LEP69E6GclqMRShouZ9XU9VMWp+HKOdxXQRRGKl+xJmCgrYtb7lZTF3qrxmOADSKEikKTHDq6JJeiXre5bsUrL5g3PmpEFyT4QqqcUQ8k1KYpkVbPBgI5smnfaxrCa0qBTNuQJMBGUauH8rIXxh/Gfi6YlEMZbkMbqGaJy0x4PegKjWraUZq3OwhtBXM4cL6B7Mw/adFF/yvaHz9YDVRBmpvzkC4vQ0b8MKI9x6NdDWWqCiWtwa6DuBzxCw2+z67XjxbcsU8wJ93L5fe7BTqYlkabBhPv8c8/aFIck6ndCSQU4H42sYLw1lJov6jRXF9JQGuyY5MNgj8LzkEPkuiO3LFWcwiROjcWSBRcaM3YMM7vfCx2UnUMRpLCMNo/CN412SPx3fvDnlgwKt1Q79loFXQfaLiseOHTzXRozqHgGJYw2j90yTSP4B0OcXdAR4WM7rw8oIkzO4InVFVZAGyUuA9GM1ZAd7yLkYRlDlHuRTC8hT2XB+rjLkBrxNuyrtoMPEgnjU3Tbppd/VpEiP+DxPtNkja8FY806jpqcj1mEbXgTlbEbUcwVEedp9+wQYD987njPQSoSMbU2ZYSw+Ylkbhj8Oo5vEaTrZaObiwgUAP+kZJejymN2bhL959BcD5NBvK9lkoGwqrSgp9lyuXcIWR/rvw7RdR65yaRf4JnUiRpSvOeNRQTFUSqppa1ltBFCqwD+P5P0IIVn0upgjvysJrPjRV9nrRI5BJ/NRm/+fc27s1FElXudjY3GBWvqP8nA89jPWHCoz07wLp8aG51vh1Ei1G5hfyNjsw7zI1mJEOvIz4qelSLvzcdOnNcVY+xK3AWY4X/vxP+GDPpafmf8JLMo8+d5iINbcxMoTV8z88/vTFmVomUHdz10YSxZj+A6am8+/kSF5fm13kMQuzzhO/QsINST9+t68PpvLoKe1PTcNYJQxZk4eVVkIYRu8fsSkPSWs8kaMkMKu0AwAeC312P2ZKAW1PwZMO5ZPmX/llWnMoMtdVFkEX6pQ/0Msd8Cm0xjyMaBhwRFD2VT+FDLx68uHEffNi1zNXQjYzDa7AEcbk35tkXjExYENzW7ut+MiPDflrMY/fqvvINzTIXN03Nract9E2buFXcgPqyURfJR1RNf9epOBq66W2AlKxqmG288UizvLKr/V1XLKCMYy/P6Gxf++5FHkU8cnJ0792FL0VbPaDtWheXnS7I/aS5hZG6V/IIICkSWNsPSknZx4zPrx3/H3E4GYDbfNY/hUgw1j+IxnCR6n3umVEjmQi4MnTMTdp1ysprqOBebevgEF+1blz6/1WXaj+tWstrSRSjOO/P5h1ySLkSGQr9gWLIVJ09B8s460l4K3O/yyAue1G8BaOi7UR6jC2/wT+FmSwXjKGR2VWbqiZdA9+4oTpTWHVzGRaCRPrsmgKWujN23to/c6CRJnh7CUbl7lxrJ4kmZPAlgcW7n4/8SnkydNwxjyO7SLBf1PuTil87cLDgWfjx2QPHsT4OnnyYHx+zixXp9XnxGT+BYYmZ04rtRrq6cMDPZWUvrms9EJbqIaFNzcDKAYibAZwyQS/o+rdV8FnlMD/Z6Y/VM5mZUdC+VxkntQkLLlZ+AsQto3x/1dcCBaQfZYMBkyYFEaO8eYPD+pXTI3vd16f/V83pygb6W8b4/yP4MEFpCXozYCN5JQPDWS19d8nx2zK1DiBWJVB2GEyhVeRPHWTqGqQbX/4+MEtUtYTZ7iG/17ET44hDejDuPci6gw1JmgYU/yg3716rM2U4AWGTHVMllWV9Y0NalaSJUb8X1IB30T7RLWpGpqqnj68yWggTcK/sCyj0li2897Ny+se0zCa/5yGHhXkSApJegkNTRXsfVXWp/Ao3u3rl8Nrkj53tj+4Iq2WQMPY/ZZHA9KlIx9xVDmHj7mthRl9Ku6QGeaySvYVIba1tbVTe4rM1W0p6GHsP3xUgs0WLit78AUzlerXBQ8x23dK+FUPS5OyTSrUcrw8m4osK0UaRv9r5p7sy/Bu/odAlpMyJ2nSJitsyoUoXaS9vcXK867SOHosAyaMxT9OxjQiB1KFfMgwFTYdZUn8E3Y7pFEsWKrfXI2nnWoJjNpMkFa3Ak3Gn5U0ifr4L0nNqGJxRE2Sdp+F4wwKUaefzYThGjIeNvC3g40H9pjg30hbP1hlwG43iqEcE9kSbfak03/lXWdtsLZ2N+etIA0bGEC/KRPdDhxQgV7qYvDAhTEmKDwyr1RNa3MU5cS01QMOmxzou3BEaxUBQSNkRTNXpdGVQgYPxo3NEzc6038LvcMONi3oAkqgbSCXdEqjSCKWeK2YLiZTGYCdUQGv7Snr4nXGV2MLMyvgwmYErQGkS/1HOH32xHB92aGlTFvwtiBbMUh3N+OKQAqbBuxDdQU9ZkAROTYq9P+3s/NmwqcSgb/LgRlMrRD5Hyx+9/CdzNQueZmJeQ5rUXJj6b9gNf3LF5ZeZGLggJYBGsb6X8KHJfgNVB7eHSI2S4/Dn3/08plh7Ef/KB7iWU4TubDsR/B2nPpnmyuyzm0EXwIdjOM/Y3r3ex+qqWFk1ujnbfi15JM7nh1FXuphkYKmXpQOUiUH4J+23kKhuIZjJCtcA+rKL+d/k6Q3/0Nxk2jIiU3L/EPziix3JvwFgeo9Rsb/Roc8ZOSCw5uRiRmqOj5VgimZXQV5tPB5xRj18fPHmhCkOYz8WmbGF4St9xgnr1UUVEiyT9XwwT6goJZiLxE+LaAMqxR0O+8tHkHKU1c4A7LiGMNo+A7ELHKeRP4t/HxTu5/ncyd1zlSzgpY976uE2bZNjeuLOkVXi2UAh9Hynfn3iCpyRqHe59IUU9QsqN0n0jrFNJc6MyhDrXogZb5rhZ6afye6vezHbMQQ+gv+GhPSmDEWOMSVG9bWwCe9yYHMSjuA8fXz/0PdwGd6MhM09AxkpdSsaeexJTajVNJsiBdUvurLgSsDLoy4X/SS0Kd34NFHt0yYgpwLmQiZGBY9PydFDYxdOXOhtVN1WYERRsvvc0nO2SzEbtA/CFR78/8IIQeEI0G9AWSDDJ6Wdypfs8y3WHitolkdX1EIbRiT3/ID+ERbAw/iAPWRE5T6savHdJn2fZolkwhedFmIvfnuh7uBZCuqYXT+MYOKXXmSdJhCZF05hP6+YqEciAK2KU2i8x20ykLrA8bxX8iAHMsEHp55vRk5DH7WOj16ZUJiy6LYfqOdN22kyQ8Yrb8nHiaLkhwn8z9NCqydqFCwrB1/9ojgK9ZiWx8tOllUudTmyrQM/jDK/5xeQ9nPzYUinLNo3XtdCBnycQHRfS0byypIMZc808BC/Xn4MJaKXFL4BZyw+d+RVckV7P4z9BaVLhPZnJXnAW/tRBhWghdG7B/5VHBBWjOKVP5P+/J0k3DM1F+SAl1ALQPZJhdoVuIYxuyfMU9JondvJ+ZqR053ea7FQSN9xyumj7/CjaQy8hpNt9hRBE4Yl9/VVH5IfpPh6NYkYlOWOmkXCyg2dLH/In1F3UZFVQQvh7clvGGkf0vwgAac7Es1y0mRhqFwa+DTH6drGhm3XGqsGlsoxS9YFEGCg/zYZfrSrsfi2CzE9lkos31kR0eGAsV9Hesux75Wji6M2N+nSexrdueAcVOs02PxXTZN8iI26NVyYRbVhxvtUGejhfyIcfyXgnqkz8XULMbO6Pz/lhGBj2CPKcW4MoNY8c3tOgayZyIMr/mbijAbcewjxvD3pE/1KLxPBTU11cfwUtVEyqxz04WigzsZFhuEf2hEye/m4rZghxH7v9Eo4or8TgccIcdQD4Fn0haf3t3b5NUsquUKx/D4tYFI+pSPJIzJP6MDIck5Deb/MOuw3WhCw5kRvp7PgOEx7O07yecZuTpGYglOGGn/a0g52RUjdkcHiLfcMZsCaMxjgAO6NomwkgmkQ9oS0jDqfsmw9eJOCvQw+KmYBRNOxzKbDg+0434xzjUHdyXFrr80RGDRZPG+lQYTI/x7uhwRZD+J+fw7tJGmC/oJnUiR3RPHTMNeE4M2LYPzCLT8NZHmBjsrOMOI/kMogSY+OZHhyJxTHskhZYI/dpNpnEGeKnDCoRmJdePdCKykVoz6P2JTHhKtvUbOhaSMnJakY+zurgBThkNtDSh/B6wMsDDW/5wx+ByumBiaXNkuJEPTfqCtqKdN615WqtUsklXJlTU3edpA3SdsCtClU+6RVjhmiH8rNr/8nQl2F/LhwrwAXsP0qcD2qeLJ0/vXL882g6AtX7Dl02qfUJP9JBKQvXpUQH86jcazYpPz4oOBj00Jdi67lo5zH/Mxhw0FDpKRJJ2EhUNz3InLNJo94XymfnEzMbQiV2LjgH1410LfaziXEeLRiccsaBeip1Pklqv91wpZKzIiNhnYpwN41IKRMxZFUmDHdtEgBbXyU1KyT+/u7xOuI7YaW2pZARY2CLiQQUAjSc54rIcBhVB1zKdShQViVh1n4C5m2YAWRu8f60W1O23LORJcP4RC4GpBWRUk6umo9cvndUXXJrISK7CFUfp9Dv+ekQ4V06K58JJ6T4es7SaV6s6r7iWwwrj7XU8uDFN68PcLwmo/GQx4AYprbWssF63SsPqMcagpl7pbA1THjHlR6ghzCltX8NaoKHC4oY7NYZU8/WbWW/nsw2eMNb3wISnG/vw7I8fy3UWir/YZaFtS7iw5VQt48FFcRI/4cc3RtpmpcgXaML60pYY+12dwlUKUY214aCELZBJnjRKv+AgQ0Yp9weL7C0hlwPbm4lc3hbSGNoxZvWIR0XZPJtKydk9LB0X4cBHSCs6/caiV3X97M/P9jdjktSEe+4wxr4eJ5vRJf/6Htn81JYq4GVQm/r0m7rYsIq+cE39z45sVlGE0bMeHLBpz7ZM+/6ca0QfSeglpLaUXw7PrJCnlzyuKYD9Z1GFv7BVKK2hDz53CfyNyoej140nT5QVyGj70AlinkO1XXzG2vf/FnbRpCOww0rbzGONOlbwbmrOmPXhZVLA7Sjq7X/cysEuB8k2wZ1H075w9LQIRdWcJPfhotC02ix72S5YzraZOwjhb1J0k8OgH7NUt/r/UXNDo6rslxGHa7d8g6nWgGzCD3o8DE114ZUFieP53ZCDJ1pf7+UHzeLkVJyTWztzTBhvyBZsn3K+Y7CWQTZEpVVsKOTJOdT0DRzV1Lnvmpd4N1P6sgBE2MOje8IHigvSlOZXCaY0fA9BXLLx2LOr5n+k77IqrDKrQS6k/qIw9Nf/X0I8xI4OhcSLiHDDQ1sOpPhV3g0J3lGrqi+HkGjYCWI7eeqjTWp/Gi1URs6PUCxh0ZPrGphcxS8Wymu2JPK+FzAlvDnMZzGHzgC4PeKy9YbXYH76rQKafrWQUPYawZ1/BqTZ5vs11ONc+lgcdNh7YZ1KNyK4KpKBsauDtjMLjG0iVHYC2BIPXFUJz2dJPvvQ5nNq2kBsx6rQS2tCxAIsgBbV5xG8TA2Pa9Jq0VTIaZSu3pePQr0iLfdqpCyW7Zv6fVsIaNhBY+J2dzP9z/ndksL68YJmeeKZ89ZpHiDnXvJeELZzNHzHB5383y/9zGWQZjO7iVfKpJPDAO1Il878XiFt11Ne6AyQvARJG0h/SKSc9qYZcCBNMrVjMv8d8KPG7XLtaP/vK1f2WxQz4zDjlqLElgH3+BePt9W7bjLTpDN4CclcQHXGXtByo47rJEwqLHGQ5ViKDLFT7PxPwYE/DGQ1HZujC3aH6Prte/M6SK+aFLPJoAY0sjqu60WFu98Qi/tBtAAHPiPT0nfHYvAidvw1wwm71K9az8bCIRLuBYW1DuDArUMNI/11B2lxQQS7g+cy/I3UaKt45o+pJK4yaAswNvl8AIYzD34P3sKjjFx7YiUQmR9Uc4K0jmjZo5m0FUKiLCh0znysJMSngMxqZ9Gnrhn7LlvNqBh+zIGcQr4qc52pG6VWlmNVlwyXkYZx9X4bhjLTEjbx+BMJzWsrzxYfr06As/N5cbeGqL2t4Q73UkxDyH+lC+iO7Ax4MTMztwkOAZ+DHROfZ8XWiDPXF0Nc9PblPzqWiXjnC7G2m4c68vyDgMHZ/nwtywqYM2TFn4TUfmjpXrX4tnU7fPJ49L3/mQ8vVbRlwYYz/qWK6yg9HmFXG8cygzPZZTK9LY6tRx98cfpbxs4UR+n06/389meAKaniD0UCaMrATfcQrWi8QuTKrPLAwPv8Q3gg5uGEqnv/zXZf6pob6Av5HNP9nBlvPOMxVaWG11ZTDXE0OazZqri2Mzf/hNtyBb2MuGC0zYGmOlalkxEvzYm9eezlvWBvxDSPxFyrqxYWQCb2TpqIV32F7Ib7qyeK71FkeWhgXuzhYw8glU9hqd+fejDh7U7A//5cXc/WkqPDTu50th631wVaukefnLYxt7QCkSJ8i3hXopcpz6KvIXufpeIVjqm7UvkuPNmIYxrK2Bh4TPg24B2hDr9Tn1mC7s2RS4AJSbiBzoFsb0K0IbhjTeurNoojRiFwKeIjS44E0SdcTdjukUQy9ATpPSq2Nr7bDzs+ihH2LdR7y3i6dOqFiJSDDGNeLWQif4YUvg0l0T68usxoyhg8fIh85kHE0SbI3eZ/rAvUJnk6VPMf7uvrebd6uUT7wtlHtdeip+XdyCvAzqf6nxuTFLwuudPqvf2hzHgUvCHjbGJN7Bk8bPo/FCQBkiLnaa/Hfzs6fxNsWHuDWRxPrYJaBGeq6IqEkO6dBxGYGxlpRDGnoEvHzQdNtmehWt65hYz1krQAOY3CP9Z3L/SR8uBjxrCquDb2r/uqVlE8XcCtaBRff1hJuqMJW0SmPyAFTIZJFn+hK95UMdX38lAEG/N8OCrY3n0y5haaX4i33HPTnbYzpbXEPcmbfZ76p5c67oXMGrUXs85DysXxK35Eb10o2pttv54y9MeCz0qti9G+bheRcDniIUSS5nmZFtR+NKeLcKoG1FIvxvx0q2ID8xhULxzNz4nAC3yS6mf9f0EUgJsVT+Plq9hbSo+0dJz2qcejLn3xtY/zwOeNRRM6TKGLwirssDM1+9sn2QhuQSgEhdMpUQ4WWLufaG7nuYPzwbzSE/qKXRAlFgl+++9kxm2o979Mo26406Fk88lSJ91ljl5BtRLodjBje9UZUkZYY0vnfuWl/lsJV2tERMSFqpJn7BtkLWQlhGAe8x0PBtL+QGigpxwakVpxK3KNizNXY5UoHtAzQMO63p7dABGklav6nOUw9jWiUGLqkHoc37s2/F6jH8ExZT9cEB66XgAsz55j/VbBvBOqHB6wsYWsxxFJQyGTPILYTNXqSdKu69XwD+71n4c0VYWmwYWOFM5qQDh1QbKiQi7Vd+A0OowIlf87JzZrRbJsNNStxDZsofL2FTNWTakRNTrettbyPtziXBlc8iAazHxVbI7eqqizPHMzSMMNmB3t0mMCLJ+1EhjTUTBmCNj7yTT/Igg62DewAXFNZDE/YVKBLZeJRfSxYYm57fW3qSIOJCadjpp0VCpRkdXRpfyYH9nMr3uFrBb4wwv8rPNGA7DGlqG+SYFCCZSmwMx41d8O4Ev+Epmq9bWDqPcbl9+jIh4qetMaCy+Qhqy3LbiE5DrOHJc6ovuvUp/B83u3r18gLFF3VHjjf/myxpcwzgFm/6GWjf3yPkfh9eFjkdDKR4Qgps2QQ0Im8GVNl0GEXMhEyKdJEVstYWDymWUnObGyBbwVyGMvfpxGUs8mYDw3E7SXiwcoxhbQs678abZ+rRNuXum5LudiWARpGxPaoopFPjpJgkAjEH+3cvK5zTmeSXMIbZEMaNvRKhbur85JyDCNZT/hQivkfkUbGYmf9GevsLUGnhYZG1WrKLBqFbgy+rAQqVKst2Dco3E9FwDzTmWPpPGHJazo1vTTtbsm9JFRh7Ok59dgYQBEzUz7x1JIwFBWeYNFAyWTkv3KltfWGi+kbs+xkJaDhnGvItTEtH0tBb9htNDYz5o97JmkVTwcagzumStMW9ay83ISoNLpQCw6f05EkLRFQz6zqnzhzeA7vRJEzQYtIXqsNcZ+2ay63cF3lMvo+YNzsIZ3l7zblT5N6MrxrqPHj83ixnDM8jvNP4QqjxU4k9clJJPFUifH66avA0HgGkvxOR4oNysa1t28H3HCpYqBh4tdD6ocaaz2qxgy5E2zswi2d3KQDOoDU+67l37tFNhJoVTYEDm8pvGE07CKw9QY0GJjFWlv/TfgYoCYbJxEzJBgScsn9nnAZnL1t2lxxUGcNJ5ZW4ISRsVBfjLiuwPRJYCR4QRrc+vJQR6WQ1CL7VNBvBZZ7c4r+molena2oDcBh7OxvSZRckyNIfB62WdlKRtHAPJJyzm/YuEDB/6VZkculxrLQwtjaHoVXBlW7oHfUdKFavjKXwtZREsXwmG9o4YK/pmqyqoDm4lgGbKtIWSo8bIKZc3Y6fW+geZHsmZenHY4yOMLoV+gbuSRdGcz/DOEFmZvfiyn5kBvG7t+GTET8SQfampbzbsuoanR9RG2O/QCyUZ97fICo9S9ZyO4MZF3yeP4PxSmBj2E/4QFV878VOVC3tjMkNyhfwhkmfG3fUDXmZPEfilH5ONSK3tmpb83lGkcbEEOFrhz+PTzqaAhPzZTw58WyiJyxiKrS6sP1QJjrHVPowmj8XSE4pKJ+rGTiGeDq3cz/hxCDLH//jPOaeDlfVrbfEIu75iZOG/Pvjxidf6HYVPr6HoCQA2TlreNDlc/Mq+YpXvYVgbf94dOb6cpymkyHsSWMYRy/9maPSJePkLSZfwyg1PpbpWj7/HYmxjkjJQe2JbBh/H6XhfyO/M54LJBTAAfyGp6gz3h2LemMwmMdyAJaxVoeOFlBvS5/ydEXeWDCDx8m5IgGVJmz7lzXdXilUaCFY2WRVDo3NkNy3dRWwEoEQ5n9O6aP0p2xmyEP5RRZrLyS4hqbUvbjJI5HVD0tsagYelu12eNdw2hnBXjYKOCITXlIOlQJ7NImH2atLwoPk2qZMvPkiTl1fmPhYyNZfsK4/jakSajXJ3IsyQk8gplZ7e/TYAAxDcr6mKqItK7hc8rW/QsRWUh6SciHr51D60Ns5MexJpO1NkLZJ2weoK2e4MmQU3iB7y7oCBErdqSQDx3p0i2woZ8EZWH35mRtVRIMF+3SCMPGAWc0VvyO672kCBNg7LNQGgtxCh5x+DA9aF7GdPKLl8EI4/0vqfAU1+kOPrhrM0od8eGYQao81bzFgN5nxCWXRH1UZMDue4FSqbJmUtiNr/etYA/j/s9lCOgjLUXn/3lT3KngWO9cTmSBoXkto1ie8mddR0lW4ITR/FBzSUX6UFYFiADjqStJVyyKyQF8+aeZwSsW/h8a4lfgyLMUCDH6f58n8JYmTF+DYIKbUa0/QWQaL2UySqLO4jCzki3f5gY9K3hDJwQz+Cbkd5lwM+R9fbxGvTzVDJ7eI6lre/nMDsCVYGn4YFx/S8V+onQPmdCxedq3r6tbhVy4PJLhjEaTAurrhlT9VSbJ5oYtK7jDqP7DREDYao24UuyOwtvGnFd8wWKICfrYYAZ+53QIhQjp6w2TxyfdyID2TMuyJttF2cDWZ9RSRTdyh/BX538glipsimh9diOoawQlrYB6UpXOj3ULahtv42MFcxjf3xKLBXKyJ6RCbifhqNuHN/7gOeXQ5iIcjjaM+9/ncgrfjpO2DK8hBxZevzymETmjIqBPrzPVkjtz60zVAwybCpwmkf4BpMtloAsshMWAF8bDrADoRMb6TzXLtqcDYQEh0FaVhMbOe4umeG4zwBaz8RmbDvR9RvVegBJYQs11xvtp+v+auPulNsIN5/T/LORhg4Q9LviEHM7/Q430YUuzicCXUvrw3qOBTIqMQnH01ftqHL4S4Aq2DKKwqYA+aBkuulIfNfrsqBl8sELXZtSQOe5OdWtRYDEAB1X/lk5MUD3+6WujaHV4coRtGkkY39+91ccqSW94wrgwcJSCSnq6ZKBr3XHU1DGlFRihvL8+Kt5L1MSfGSA6YbdDGsWC4b7+R5RHTEWCJnERa/UmpjrXTpZHG8b2d/l0ITEb0MDk+VN3JDCL2OVCf7Oh5tJjCmlf0B0AeHsx6d7wQD+1orRYS7zrcsVn9NV35t7gsNKGBDcb3eIXjPo/l4MBPOhfFcKSAaiSKBvRfs4CXpGh+GARac+8dImPNhsb26wADWP97xfjVlnlLd/wSs/L4e2R0yl/OAjWvCxayWypucHMSv7ESNevkT//Tvo0SBi81n7A46KWLJr6j0gHXkgBO6BaYsw1BdaghrGs53q0RLr8G8KH4TzGFbwpeHelM2fN5uUOb9bwhnGwe3SYwIsnPeY93FXNtKEqYlCYGQuZyE2JV6zbtr5YFGnnraDnLzU1F2dWyjSMoe34ikcxvHVIhkpRz+xCL5kyt5oOE30nJykgzKhj7qxE7t/YFsBKDMNo24NkJMnx/B8TzCdbd5UKfvNFBll7HdKCd6yK6BrriC1nlV05tjCSdp+p+T9CHkhyDh+YGbXyEiTC367G2Hal+fEN0uPq2VOTB+IWkuSXXzCe9oxNtLZnCgFr/qdZjJ3TmSSX8GbYkIZZMiPVf74m0D7uvP69VSciewbOMHJ2nybx4gEKCVWZgbNjRg7oVBk1fzHpYg6+atZm5kWxtbP4tJApv/yCEbG7WnxN9uGlRA+bcQUtZZ8rxMABVmuWzOl7imMLU153OYMS/5wPzc3xfRbT62yoOo1olITlk2HdgtXz9uFcsFoCFMbo72tjn6nU1haIH3HfZ9cLQTCu9TGO975iwfXRSaqbWYdhZP8J9RN9LU4KjHttxWL+PYaYR3rUUzyLQj0peO1qf2vr9at954JRBF4Yt9+P2bW2LJbREJlX5hzx7VEe3pF7uL4itHYsehXnaX4coV8QXBihf38+4oApxcNRjKn3JXSX1IOyjU64l9X7FD+SUzUzZjGEuV04axDEeH/IgEwk5DgZYy4tJ3Qi7wnbNOvPQqYG1C/fZ5ZVmlmEXSWaxsY2oVbgho0CTuRAF2vwW2luB6ykZt8q1m3b3L905OzLYbaFDQF+o+GI9Hj4zp8xOTaQVsSxkSlRQNHYQB5tI1wZbZAgW6g9C/xjGc7IGTxBprANzFynsyvFvr3+QvnnhviBumFnBn3YvOCYSXJwoymi4rDrMXjcorzc7M2dzZy60VqEw+YGeqFTnyuc/6HVGKY6CHeg6uyRHvxYNf9O10ZW6+RClQMOmysc0WT+N3KmACTmXL2jkjvGVbY9aEuVRBGnpAuvOUjCAi7bazpScIRcQehhw4Q2C2+oXoJatQvVXpzXMTxaaBQlskjPUEcl5DPtj11bkAISNja48DkdSbLHVAh503uOqPaYTWkYlzbTqKeiNmfK7nCUwhE2ITjnwyG8d0naikZD39TO7nGp4MdwIx5d+Mlrb5R8cfRsg/IfNg04TCKAEjlKAhNp6QSX2S7RRw8HvKFLAJVAq8lSDSvBDCP/d8M7qYUabGDSFcczYynzmCYR/PSmZsIccexmRCwbmNrGmP6uxgi5FNRH70mnd9/S7SKL+Dgu4lXcDHHjZqdHK2DDyP4uC0MekQ5XY+QoTi7j+m9n5+sCNMe9WgNcjh27GnFyAQ+N8sifcmR7rjuDvy3J0YxPM7gzB+qrIbjTCAhW4gnkGs8U8jDWf+GhIUl/6AfcXES5Ygp+caEp1T8qg7q94qeAK6VgP1ncoltxfHoNTwTbaDe3MaZf3zTRdgb7igvBY0xi21Z0lKU2Xo6wRoe0NUSclbCGGrDDe7iR5OsUghvWL7RZeM2HxnETePtlsdYk94ycxU3XGKRhhdH9p7Ef8vm/C3IOn6TioSk5S99hTfuDdk8JdBXkgNIC3v51RNiGm4FagRg2Cdhjnv44JNmHhyhDhJ9FdRitaPig4C4DrTfX+jjJReXgwnj/E0kDcjqQyUiaSwA5VgYnNByWVmM7bnbNUIXy/bEPn+eVru1pYEp5UvY+6IrwGYMvDaQCVBZwz8bJizcPYE6MbQdwO9gwoEcVJMh76sKA2z4LpWktO6VFzMvqGMTc3NIGrDDav0cD6s1IF6LYAMmP5xBb2no9qU/F3eDhSNfzPX9qGsAq6SAdzDIww8j+Hh9T0qaJ6aVxRr1FJjTOLzER35MYpYj9klLXz2/Cs25MWLPBvu5gFP9uyCKovKh57KsNDyxkgT6Qk0HcT6egdRglPXWXcM3uSViJZBivfy7vb5af8eEj+1BMtJiSVpfBVz0LMudJXABGGFnfg48KQMSEYCPFkZL+jKrAGA4tYesV8+LWF4sXojcFW1aSHy7Qhy4xIkfaUR0/xfurxyFBZlmv9J2vtQ9RjpZfwhFGy+/TATw6wUhbZzzBEWI+N9sVx1JN2Xm3NVQeTKj8XmrCtCdvHkbQGbpUCKmM2fQLK/Jyuc6i0Vgl8q7mBi4rCRAj5/s0nP+xWFCjuuc24HZM7/iLdj2alP8cDV8SWu8xGn53xAXpMzHlpg7iisbXUmVHPS+iSNdAYdNksxMrsMJp+Hj+J9TsZ/PvClmoPWbDYbZah/QAv/Js3RgFp60pjyyMeb/gd1yrnc+YUjKOzdqrTcMFn5yB166AB14WWm9evW/2cV0r4MJo9ifB9QNFKWQtfmkjSmZksZI7bGrB5fRblWMMI9wPqFIzciBvmUCmOYqPfPPm6THjw+cc16ojvKpU1zR5ZmgFaBgl31KBfvGkz9kAyZLwV0PSS0I+zA4Oj2VEWtA3CRaRvc5r0xU7tZ9YNzbG2SAs3mOM/SEdygE5DT3FbsZmFsVmQftKhrpZL2CE8r6G0c2xFVWHNIzBbwk2hkrrgqk7ZCHoKXHXM3bRcIiVDGnbtbHgX7vZkZWIhtH9LREk8LtJyREdUFP1hXoapsWrux1ywm8C1tgAV1XybC7WrEQ5jO5vQd6cf4dujBHA1Sg0HXjyjtn8vCnePIA5jbQFfH1AOX9tjNKFfpKaSoql2w0pZB3JcEYjeMFlwfXmFFqV/WdjOwArGMMGAOd0Bt+f9BhkRQNkfXiH0UCaFdpuHPNr+pdmBrBKNtVcC5ACFsb/7wk65fo6fRSZIsMc38MOhVBXhJatI6ycX1jluMKo/z06AFi1qfDm382sSAOkn1wOY6/YUNp0MF9R5+cMxJsasmz0jh/Q47sLZzBJWiKmyizmL1nI7niWDztj0bDQvmNNyy03D68+bmEsfxfSoaf3aJky82EH/kt+3tW94CPDGuAHF7sm8asSQqyx6dJKTMMY/t2ACwhpx/RWsXBoBrWUYQDSTR4nMXykF/K2oWSYcwqwFOFQX33oJMkRnSYBfdcb/lvCkAWQjs9ExIwcCi84+rEa6WDmYPYAM4zhP6bjmWCkT4OEmcKM1fFs9xsrLs5Yd6S5om0JaxjDv8dDwWaknahwpdcOArUr6MxCqOl8wQr5CdS0PXCAswW4j7jbzjdoPwFzyDBpNd40RuHfubDmULaEMtRzn+qZEqTQeAJ/Pi1YpTmENb3rtAIwjPy/L87IVwHF7LvDJOTSlGK0It1bXiL+mm0pHqS1m40z1wqkYIbNAu4l2h1B1dhMl18n0S0f+j/Yi3S/qVfjyiOsJJu286EZV8Kbm0BtsGofMVbtOPHklMfknHHknK4mc9sqGY2yHK5x4qEU+mpm+FTVKV0nCcoAD+PYelTxJCId/XRkYtIfeh1AZS9z6YUhmUz5/H+q0pLaNZBsOIBlAIaxa5c0vKGkq8ZJhCi3f2chj7OcWjSh4UwWuEhfR2RtuDWGFVxhTNqvQRJDKeYnwdB0ez2Q1/AAfcaDDLbQTYHmgcxZcNpB2ieMQuto+zF9ASln1n4h4xjARgNyIONocm8Nu+Qg9TiG71FP3R/qWg25D5V2Ce8tbqGUM+dsbniz0RB8whi1PabgXUCAUwrx/WlTeGZCGmZlZ1DNRRDb4PG829cvkRfoCipF2/tti87DuYfr1+wkkhWUYbRaK/L1OOrM1+cfJibOngptkD88waJBwfMPlSLtk0UtkWM/rMEQo936MZuykLThOZk7w3uJAABmgHcCwOThSCMTfssL+VLlgK9m5McTyDO/7ByqVoANE+UeSkb2GWBKebEBtmPGvAi/dLO0IPWKce7j27G8q9Hm0msaaphE95DqhbtWGGv/YgNrOTsr+1KFfEx+pwN1V4Bdw7HmNlfWLJLhQ4Mhjci+vgNB33VlQmPzNO9T1ghvFdV2auNOuzrINZkhsRLnUHeOUAt1fSooRw5JQDaFD68PHSl0GZIbbu0dNQPkCHIG/35YOuKVxOGDRUf9gdjU2b0VEKJGHaMkiud/hmT+VzGlmPloTsK9gHfIHliW5lHBLtdWnmuxccNi24qRPQWPkCGb7V/1A8gA64c79/qgyp21LwShz9gc4etYSzX0wNOcIZxGNEoMOvffEqbm32OqSqOoZFb8sPXqHO5GCNlsJMPPuAvHNWWCnA4U9RCpJKDwmhtXKtL5sXkha8MN0ayEMWxmcCIBWHtJPGbm3H0X3j28eT/WiTIcXyfKEHeIKVPRgBWZvNeR2lgxec9XornyKg0qbALQvYF01J+gG8VPDaF+lF6v2TZ++PhmrOzahS4rWRGj/hfHe/elF5uTztYN/ZbBVQ2G6TZnnJXcRHGFWApy2AjgmCaKh+RXoR7stjN+aEkcj6iRJZduSa8G3Md1SZKuh8zACaP8O1QkAekPaSikaYZwDC9VTeS9dHbJBg0e1/X1i3j+9dmCam6itAIzlNAfeDKB9jHRz1CZmoxcH8fsjtRqpH2qMllu2UyWefsCbnj0LKyhvD38YxnO9EUKRP1zwm6HNIoFw0UZ/cUbL+oohONtfSJbk/FmJbZhTP5hov2rdsMhx3xEaxjYtm26ppULbI0lNGxEtS8Y2X9B+a0krVsZ8pk5LULli+mCTU7hJehV5EIVW6Vw+/J2uloHuuKgQ49vQoSakTaNIz+hCOyepmdbA58SvW9cFnRv7i+08beebCTSL9ggYB/etdY3HslQu7/ETHBqEmtnrdOjDMjQmymvmVC3t+tCq60nHWIl4GFjg0PoHMhxMkyC+Z8G8tpSyJExU9fn0UMNldfuTi1i7plqjeYSIFaAhS4J6Dt2kpzCDx+ZTek5vIPUMmdJZ/hK8fXZ4jzKrd29AF3YUOCcBRJKMJYIhl0Uw8LWqZgFE07Hsnzgqtmmkzv7ZKNQw4YGXXjXMTmnAb1B0Lb6ft1eh3TgXYU+LXTAro4MW1Udgduuy2ANmxzsKhaSLg/HQ7P9hJjBkRWUZ5pYNQxi+RV+U2fnVrCETQYOkpEkZ3z4UEwse6JJkQQD7Vyl2G0GUBdKzorI+euIpI1WZVhBFjoDkNeK3ZtrhIgYKM9e41Ek9Ip1/f1V9BpLsV0z+RNtWw+fVHYW4PObiHTh5cLvpdlN4gV/Z/GnBdbh6hjF8mp7J5EthiKM3D+hsQ+f3slIJoE0pdc/Cvne/D+0rXs4EtQb0HvRWdo5gxfZsWxGC7k5J+usoAwj9Y+YmvKQtJTiFIlVx2yqmf5sXtw90ocpWPjarOr2G7BeG8NPWMmPKItPp5wcz/8xQXZ2F1RrXw7hM6IGN8FmLJRSlZ4fvbEH7WaXX1ZCGsblnyaR/gHkQlGpkBuvx1yIbETrJuGYqb8kDa2/KrE3dtBaghZG5LcCqkiXeYizMb5iickZV8Prc6X58otFM6kq3S6aiz0rWRNj9feTkYDSIpDkUlNk/PnGtMVH4TgIay2czZl9OxI/Ay2MxO/e8IHiUHdxjw+QjHkhEyETw8jnmJEeLdID5MS0mnWXeUk0p7VsbsiygiuM0N+jAy7JOY8mEvGJ6kiIZVtf7hGZ1lTM/+XFXBU5CFDHOOXm3DbghbH6xwkfcdKB3/FkwEMTYOcyMC6DsVBbz8YFPC/WFluOE/uJqy2Mvz/hQ0Ejsjf/lxBjlYwMYF2xKCYHUGehO0rPnG/XEWdViVody5/GGsbyH2p3ld40GSPcq4Rf9jCr2G9Lb/7P/21f8KCABzaOrTfX7FdCV7gwloIWRrNe8ciTAWkN/5JQ04rgAtAVZq0Re9Jj95PJ5sUsV3fZABZGsO5T6BYhbF1yfcTQpMK6HP6mJL/TkWKDDMKe4XRRLRNmcXJUVbZsakSzQYFtYfSr3mIb+pL0F8dyTAJsMTz6nSo6knfZyn+fxfS6AL3fDK6ikqtzLthlMIfRrlCgzcglW/wYA3Bn/UuyC+/N1/u7RqH27K23SiPe1meLl5nc1pulsIfSs9qLmJx6cmTKgHpc0Czy0nTt+tRxjoYtgh+Mhu34bEjabAAlW1cmwYCbveY+C2U2Y57TCdfHJIY+LXZxqUlocl3BS1CGsbG/Q5SCCmZf3uUUZn0qYnJMxy+9B1FtlnT3IJqXJbcx1rY18BJBeknAzTrtnM4kudR3H4bUID32uZLlSY+6dQZOZVZ5uNtG5dlJeMcl/LIKYabTSxayO55NqJfsJUB7c9bWpVIb2MJE2b8lYbLwWaFjA1ptvcJ0/SCCTYsxeDiUIizoIFXHUs0541mEGTYg2F0smOxqUx+zr9RMG1T98HngRoyxHI716yYdeDnlIffmUa1K1DW1RrOCOGxycAavjkNxs2A0DMw9dTiurfjIj+VGzNTX1BrPCtJQpXboqfn3iHQSFg7NAi1Xe6ZfLvwWk31+M/9HQ5FWSaHmWoAljGGjgQtfBvM/ItLVOliAjZlFj2k4/88og7EzqoKGztgrubnkglcaWBjhfyjn/y7IGVfSvI6z4mI5IktbDbEvNYRYlfWYQ1oaadho4JyNRvA7egWv1JQIdXwmIpZlMa74CJDQin3B4nvxx2aDzLWaGZxhw4EjCZ8mOWEeEzdjVDTUiqCyJ5f8gU5bmkPprqrAmsm6I82VZGmc7WBDgAOqpmxGWoomN+YYai8RPg2yXWWiNPJaYsCLtJYOZBsFMoz6/31BUyR3ydjcOflR3KftMpZDWxl8lZxu3ptJvbIL8WrqoskLmTZmmTvYAKCnr45Lcp6MIPOZIGvFYv4dii+JmxK/Hd62t95vv7pBi9ssfwbasDlAn8HHEXMKyaotVUiT2+d0ndBwDgr5Xzcwc+YLF5sLKytpEr++OvT1UfIWG/AISg3T+vqMR9lceT8DaDMlilxfrTZZ3nsvWoldTi9rKZ6hdusSkuIIkqNEThmewWvKKoAeF4VfN1PWRXeWQ9M6qGWgho0ATnQRpm/ce2aVVtShMZtbXxGFHy2uCKwwa3QV2zNgh95r/QZ59YrHERMG7H7KGZ/tAtoMhWMlltlNjm5WKjhsOqAHnDQih/N/qhG8J2YKay/5QBoG/8X3T6oNZrWp39YQc1ZCG2rqIhUL73TxFsZ8Mv9fJuQYEt9SgtsyiHtzFVolFVuTqTUbMe09NiHQHmfje9cgfm2Aaw9wpAbUHxpLKs+70Fptr/BLQ1wcGztvtxHd3mOjgwt+c0NDTs4Zv9E17krh7SPU0tSuePdv1IOmwn9lDH7YfrszwRszjrcCQ2y+0OXsnh9hHKFIco+i/1g2Xgm8++2syg6ibN+fOrQCvDwjIkeJFMMW6u4Of4uG5BD+pxndzlkYsqwg8kqKKVM+DSZ6bnVFdWAsIvjIAdoaWHE3GWhWKjlsvrBHFfdIS1zTd+fJBP6VH5scnP4XkFcAX+MkMjw6DpiKfVp03FBLvFV17dDtrqTghk0VjiT5GtNxgiTMxzthmPsLRv6+Yvrcqc16+zrOUq0kVdyFKHw4ByXVYGaqws/bEOT45I5nS7YDmoxYVMR9KAd3b06NVBXgmosyKyEuZ+/gb5J0oANlwlRPQu95AA2AyEa69PHEUpGt2fMF3FvNoW0Jbdh04Qhafoho0IUqHklztnAML1ZNpMwCru+z60V1TK6YB92ER58m5GpZurnVY0tow+YKZ3QgtF7y+pqZoe1UzIIJp2OZbU0vqWDhsMBgoZYAc5Gscmx9QA++KjkjZ1QpGZstaOt36FHHAaXZczwLU6w2e9gbfcWeYOvTVl2aghzMuUFCGnLYIKFF1T1X9q7No4gi9vGrjxQ8RyN+73/U6Ni2roojKyEOmxjsCjFjEemPfY4sJOzC+4e378dEWzSPrxOVPVtQ9Lx1DtbKRjqL19RX9KVOv1sYa9gEoasXEeDbCDYzo1r+rKD0tD4Hc2/OfFQZ4pw2JAM8bKIAoCOH0g+xbvTrJLrlQ59cyNvsFKEfyzF7EdTWpw91qXQJZdggYZ9JNWLkgKvI7BYqglml/cLHhkg/XNeQhh42RujyKQ8Z6SVjGpkdw2rp0XPdZdY+1DUWblYiHTZPOKKKB9ogUnB4z0gxl72UtxTt0iKk1+wZbLIjK5qGtbtvYCWq4XdAIS8eUD1GMCCGWn4808Jo7SNZk7tSG8HsI0by7gqud2GYYMos2/apoDHkVEWzafNYQ3OqSjMfTWLZ1i6EWQEXRud2Eu0fCc1niIgm8wahX/VTeeXsuP3h05s1A06VWwxgGH/bEpwlZE9fXyzuhtuhIwh693xv82JXnj9RDozcBD0FIZSWvf8BZFHVm0FKwjsSpH+UwZCejbICE8614GDXcPHTCrww8rVLZ/DdSG/+PfYpRCsDYem14nSjqFsqJWgRiWO1qfC9RV4sb41gXQeZVhIhagwvWBQBWJQkHa6GNC7m4ddm4TUfvrZLjFUuYsNt4q0gDiNdATpy/v/EpE3h/Uc+F2Zow52WT+hEigLF13YNi69ypXxz0WQlTWKc6tdrRsMZJydeMr41kdRKolhxSi45Cw2XhKVGcnUY+7QO5di6JksrYMMk2k+ALY+YOGZTGsYFKK8GRi6nki0CJoymP4THNSH9JKbYcom5QndM77hsJoYqsXNxkEpD6hPOyd/wa7IrAoqsmuetxLUAgBCeCuhe6witFRPENeRHrSAJI+B73KdcSHLOoxi5TtFhItZF1ciwDoVKqB9TRdpMjBT1Sie9um3BVXJH2EEvAz2Umh94MtF/RDo0oAg9/6vHQ2bwXo8Zs3khzB0StgEtjLLvaRZRkPNkwM2SazeaQHFvFO+LtSR9K516UvACpOoGxTNXki1BDnV9p6GG3B5T4fwPeFZ3xXNpZ/6Hx++eBlwOi+8At/aAwwj9x8VeFc//DBG4pciItJXZ/A9BR6V335oCthy2wiXPDLAw3n6PefBresxmmPHxU7eq+zSKEikK8Bd1lE44/qJ6iGFk/oUMgpmOXX9J5t9NCmPJWmXpEHqh0FVTQx/XWdqAF0bfH8MT9amCcmyfMRWrhHtmd5nLk531L8kuvHlfL1M2M4457ygrWMPY/a9TKPcfyzADZOhRinM65OGI9DUZ+/h0X3Gt7UHK+l9MgNXEBaPJMc6GuuIzNgJoeTQg7WSM7LPhvFkP3plUBaQ82zs1jGiVcGducy2NKtReJYwlVPikQyNktJS6NpEu+fVr1QFtn9/M/1EgYzp8bQS+MM7/UEY+dI9s4jPUbaCt4GdcS5W17ekodtvQVSLnMmANYRj1fxpQRc71CU7lmRHsRMY6VPmQO+GXlUVZu56W4hEUZtB78nHp9Y837zQd5KxBDqP+ddLU9gKHMrmRiYE5TFZ9oqnZ5m6HVJIt3eJRCleoYQqXasTJkRz6UtHIn3JhivYfq69sUcamL/G4K9la7nypucGiay0zuMMGAJc0vKHkUlBfThFNUFpHttRfQhicNtRV0ZX/lUc01GidzfTCGunxGB6gMI+49uNEBWRf0btsPCtui1Lxdc36hLR1cxmwEtCwecBhQsMJ1Gc8mH/HRuWpoXgKcvs0GFBy+mgyW4bTePNCzc2cbIQ2bA7QVowJshsMJKLyR89/teJFGi3sK4ZDrOyG5fuPr7/EuxnZ1EZY+4LarzPo80lPXl+bbcHj4fOlkzjBoJCt2PtKgWbRNyUPZ/k+xA5UaVBhDK3WMb6BinE9MmVzazEbefILxs+2tH//b5SO5YDnUBp58p+WgHc7/7OhR0kqAZizs85ADHdUCTlpJ5AChuZwfHH6QUGCyer/O/N/KE8OSltdrAG6XPhawhbGyfZkEkWUdDlgCDmIKej0QdC4fLz8ivreq5uo2LTp2Wy4WanGMCp29479JYHem5zJcGgaERwAGvU9iO4M/kG2INsV8NCfxlxjqn13YalyyGEc7bkcjiNdo7GBpL4Bua97R2R//h8xfFVlh06nEY2SAgcxt3JW50rqGS0yGRt+Sc4K6FCGlg7lgHT1yhJy/CZl0I8e9TrgA2hYOW2o9sxZWlss4jCutievGTmEh+4hlmRqBh81JFwqqEGhtfQRpiIS2jo2oE4VZAlkW79g7GyXKnj1ZD+Bl2N2Cl/h6U3gEXK92Ug8dr96nsXbkhxydUr9UE9arUrjMhfbMrBDHdWptpElvWGHqtg3c+kBfKDYmZsjLgKqQij+nsbaZxfdNglm2Jjggs4kaXlUQd8pEGf1VVm0AzlUMNJWyWhUoEHFLRkd2tYUbdjQ4GsUaHeWIzrgCOmmIhYadG4/Jj2uVIENzpzUuT4Ac0LbFLywgcGhhL4T4KLLIEzx2I+TOB5R47jvi/bRa6hHq2pt2JFsacThbuwDpmJJehIilKkXyjtMUnyHM4fVrZl9y4ZbsVsJcNgYoUe9SDeY8J2gJT1j8LQwc5dWMooeJUJpeg2g6lPSZkrwAhRbtQOF+ke75uLPSrjDZgp9vas+UxQ5n8MYQBNldaHd9wSLBkomI39dIp5rHKwFPmyucERnISO6ujtlUyaQmLfi8PQiYA556Wxb6w4iZ1blBEYZVGHzg10xY+SK+qZ0bRfeO7x1PyZ78D7H14nRMzwKc5sHqOff8G1sH2ADSVvYkKA//2OKWNSuvkh+IeOYhXqH/UDG0SQpYCCEUxwla7JPH3KVRW2dG+Gv/jdyX4xFBD4xquDliBl5fMrPD1ar5wJN5TdslF9b2ExAeyJwcsSEmAXUTIH4FabnHCKvFF4fLNb8TyXF9btjaAVkqJ37KIm0BxppiYEWRw4xP7T0ZdWlufqADlmRyzl15Grd8nDluRI3dReJpi9Oo4DeICztmfZzkdkifp+FsjxfVlKRZjGCVWJR21iwWYlm2Ejga0TH5BDeDUaT/Q4xbhxQqjJYO5ZK6zmaWd5Xsoze1FLMShBD9weoGkrS1WcmyCUbDn1koHkBMAqN9TrNKRUIZGubIJtchFmBF0r0c+2rwUiXk33FRgAks7k8TKbwg5LslkobnmjIApnEBcjWJqFsdfPoCK8MrDD+vkOVkBFpU8EGZrxqKz7yzcoLVW2/Jk3xSy5N8TWEF+mx6AdLIRWZwN8IY04FhKOYiv9GIoAsfNITqZ9shADuRaRFk8OZlSoMo+87vuJQ00/0hOVknIRj010PugKaRd6ytfv6RLI19DWwEcK2Ub/sb0xAWozg0yhIgJkaxtVI+lhDJL0oRLn54hKqcLW1mPKQnNMgoqbWOu9OdHFtYi3Dk5thW8MY6plNZcJCckC9G0RA8Rv8mBFpy5lRz6eqslesuvSgqybk17pGNxvl1zbGuO7qYOBR0udiShdaRY6YHjzlqb37bQjplcsCY8oGplAX7cpjDjXTFpxQ8e6ABtQzK7UVap2+z64XHRW5Yl7IIu8+IW824FxfkMYbRsh2df/ISJuOb58f2o75w87m2qHM8ftPwwk1bIl9+PzOePi4SVnsvIk+NRer2Q+1Txk8lV0osWgTtKHtp5UCDeNlT+gCbn0qOMLLtvTTE2zoZ8PWsgfaK2Jta7s+btruQEAh2KFuLXL+N6l5MZ+HPjIP0H85JL0khFIt25Wy8JoXWWCqGHcWg1xVeyQOehnoYdLrU6UPCEiiz08bwOtDLDzWG3V32en5iwq1kqDbqQ0RklPMNXn0aQNwO6hCm40lFP/XNEROCGO27mfwOgucP69jT1CJb3uTw5iNNmEHmxuc8CHEMBnezf8Q2EGKlfr/E3Y7pFEsWOG5eqVx7YPNZOpm6lUGNNzgXXEJLUNy/5QyyrNEyMQ4HXxEecRUJGgCz6bAQMHFthoCzEpsQ3XaVOmZ6Bn8nv5gi5YtqBg88NBnPMimTgpPdiDLQ6ysXrs2F9HXUOFhJbChkwMV0oQA+vQWCpJU97kybwoU3/GtFHHvd2rTGzjP2gJ4wyYHhyya/2dETm8l4uCCO8HvdUgL3u+DdXwZvL25oaM7Y2Ejj2KjBOgRhlLM/xfpaMB4Jsb2FDzSUIbZcm03mEhR4Hp1Hcs05whUPbiwyUEPnh2n5EzXaAawcjYEziBXqqA0t/GiVGklU1YCtibHMiu5EpsYtDwaUHKhqFTz7wberlgUkwMa4D5A3cWL5lNJIPdALEzmfy9frtXMDqiSWs0N5VPow4YGV1yIGTmiweCWIma1+Seh0jZ8zculeaVazlKwy5ppIL3HhgHHHIJUlwk6MUCE7xCgAqLVSMLtjssmz3yrljfmah2fkQYbNiPoSYAN895pRWTHN8t/7MRr2tz9FWG2tWPz1lgOc+tMgQrDC10rkH5IzhPPM/dWsAFTCmVXUp9BAXBO9O2xK6qTBlNRaczVrCarUn/b5ObASlbFBgbaZgOA1GdMxAYW+8lCxQYgy6CwfwvvnBXoBNz9gI1CGDYaOKYBD/Uai0Au2j0l8tZSo/uvO6w1tmqzAjVsKtBWM/hYf6eKjuTd87SRu9GEhjNZQJRbR5itsgd1vMWTWMImANq3UQ80A5lEZtyq3CS0jqjazB7TCsKwMUDLU3z+f+qLAEpGZrTqs6nOmRlonevbT4tzdUMaFhgH1BFXedzY2o3DrUAJt1qHzisgFzoNGEA61pdd4yxdseD92/D3FjudLTHgRdbVK2UurBIXVYzKm5okrfAYGLl/xKYMavuhL3TGUwOG7N3lHDbpa7OzexrjtWFnUf/j7prYwN4HbB6w+439JeHswSOIy8hA3qLeh/JkytQ4eTATTSEwu8/+ihDc3vnwJhh0Eu5nwQ6dDGhzBJmQPlWmuhYfRJ3r+4l9OYSPixZYGGjghVdXuRWBEzYJ2BULcyEOrabgwzHpcplcG7haLdIofqk6B1tlE6nNAaezG7IW1rA5wImk0AXEyUAK0+dxTzGOlHA5B3eaF91WZMz8pQA3XsrACr3uymj47jgZkq4MJoj6DGIaAqwjGc5oNCniWpUT0Go21qyqLWhqQ2oFb9gEoKNdkskVF8ycrOPFWepyRfMClxtlWkMX7vAOL0OQ+V/ht1CQtqJmqjTchNKXdobUm38P9PrxJY9Y4jDnMLeEOdRmCOAiaEQO6XAcyaIHxFo6ppHLxwHCKzYF7z9ZpDY2cyJlpQnAxgj7XE7h23GyRwcDjlyr2+Pa4SXmxirnGYWX1sx4lreIkqPUbjJJZiVoYXOBLgMURWSfcXQHXV5fozvoJ7sdcsJvAjYqYs+9WaW/w90y7j5iM4ELGUCqbMvBkJmDqGOmLz6RfQ/e5ziDvKV1zlfMll+2PtaEQXPX6gpgDhsIzP8qplRJbdFNY1PGsbTHlHZFYyMaPmypr0/SdILG0tjCpgNQh3Gp71WwODYNufOOibGIj2O6ychyyTIDLozyP5I3kpxB8UJ9cjqZyHBkIAxZc9pjIVMD6he5ylNpqtz6ZdueU1AlDlXNZTOsJEtsHtCmKpbRHekpeZdTopEzeRcaZ8V+9XjIolfH3PbnepdnTR5CWQEdNhTYpwN4eIKR3+lkglRo+F30S/ZoWbWhSbS54cxKCsUGAldUcI904OF56HUe+mgGlKZmp0zvNBXQblcr1rCo1djsbsBKHMNGAdpKQ5sgtOf/nHKkWutRHt6RXz5kWbVEsWDAVIGDnHWMZVURaI3Fl5Vohp4WoFNOelK/TdPxoDf/Q9BRlvcvzmJ8wYNZzdjaStYGXOJcgho2IDiE7HJEleJjOkiUOUY3JLNpfiNRI1ma3VhLxLnYlgLcJ2wycEZjpfW1JwkNkD30Po2iRIrs6Yo+HVCPiQJbwXXMnI5Ks4EubAbwNYooxLMB6rC3elf4SrFvhewNqnXdfjtrqg1JpTa6gk/4TYGYctIa8zAYyNCcErThsYUs0Ot2Geh1dWVdgFKr4w6xA5m1AIfNCn6jWs/xu0yoTEyIHTNyQKcqOyrQrcREkx2stJD77S23N3swYAVg2GCgx4c+ZYLsQRGmIL9gnnsYmwYYu1szktYJz4rBCNX/zxQX5GQkw5FphLDhAHLLIynwYGz+OeNRRE6YwHTWLQUtvOFSvMdmLJRPr15+effLdiPoiCrrqs0D3Jd8wGGE/j3hmsz/LpGLOSym19mKqiXgPc7/LK/prxnaKiG/XGLMQA3j9s/h0XGPHMnEM+eUP9T76bxIw1hOG2rx6ZgvG7hClf4y4CEfw6/xlI7llA8NcC0LxtI8PoUHKgppLKo1zP5UF9eCHNsMJ+pZBt5njNA/0qRX6Cl2axr/rFrCPP2mnTIKX2+tY91fZY3mglwGa7jnTxwzSc4URVTYOfIxSLhQ/pI+pFH6yP0074xJXiLNiVwOTRk0YYR9RyY+5QPSVVwmbGgOI8/6l2QX3p+vw1gGVh0mYkou+aiAfuxDlVnzY228ftbM0dhKxsQ4/PlfBfumA9JQcTNnov1mcXkPjrV6+sw6EqMsrDDmfleF2p3sTI5NGc8TDozFN5Xq2GQ6Ux8LCMNI/T0m+Dfyq5fIMSROE2QpFKU3RkJ4vqTNlOCvbe+5VZsL0/n2Zc2dSVpJmNg8oM+kIL/Bdxu9u5XmPPIcINCPqQKMiZGinkHWpoyPX9PeeNuBr2Hgw2YDgLsIHs3Ep+QEHoCp9u9IIUfG/ek+ZGKaFLlA7VJq/dBlJaVi4wCdUieMdPz5H1NmDp9WXcrp0ZHHXhLX1gNijurIwAybDpzTay3qOWbzvyEbJVwYa777VFAo5aiiBc5o5qyUlEybHz/XfEGuqUHNRsr8go0E+jRI9JrvOR8OzTYBg9szjkzjYKsnO+sUZMVAhHH9R4pH8Q18fq1IAGBMHH3VTyBb6ot3h/TuYQV4fXDkEuJL0IVx/y0x5SE5HUtkw/KSheyOZ3UY/fm/vJirIpcJ1xZabr0tjSuM2+8z+GxieOuS7EaLR2fiK2dQmV59Wx98rZudnRUkYXR+n+kiipzxuzs+CulwiBTuj5LpdCVFlaLqBQ499YSROzj+EnytNONpqRgqLY7g6xhKqewm7hn1XqBGLLsl+bHmLWFjw5mVnhDj8LtQwmuvfq4EHzFT+rrX6bczUHuGF2wdCa7Ntn21EsfQ671ae0ghT8IfwDcy+8QcS4EfwW3N49i6ActKxMKo+a9TiBNfBaKkvpDqwTdsSaIzLGLFWcdI5eirl4UljHHf44JPJpLsQxKLzNJqKbely3cl48ZmPEdfVY+u7V8whr0l4BPVauhEIQTWPgulQV/5dOxrkUQX4BXf++6/os/Je4tKnA032bSQELd/wRj53QBimma2elTF8z9DZF6dOXeUDmw/zyOthN3OL1XCrrY3kJpMUVgBHEbS6/khvHdJOvAgp2acy6ns0/zq2hOpTR1GW0mVGCN/SOHXUGc97BTlhYxjFvo0IAcyjiZJdp54nOh4VuwwfR3B5DbULKINY+0frYF7fMzEQLFwiKx44Md2u1QFAAWvwO3mZni4VqXwam5pZgV2GJkPFdkwicgZg8f0sN7xNGNxKmbBhNNxEQ/XSiVeH7ZcM9Ck2gzj84+TIdWAUwqzoWNelNrsTmHuJxDXLpmu4WUQK/ELPa7L4PvfULKfeEzcmIU+myIt5c9NyVIdZc2yZd6SpNvwLgYrjMJvqdhPFLnwGU39Rj/iZxfeP7x9PyZ78F7H14mKMwhrL1Y7SpMWtRXY54Sq5qY9K4jCaP1jJsMFJdGmgsEzMEAFlVjEIFhlif1zWeAucy1xlOe86kBUAERb6HXcGWCHtPUbMEv1ExnHPBxpTmJPQr7IxqSOT5XQrEQr9gWL78eTzUOV8422BjmMuz/RNxfa8/8R34XIIfAzCk9vIFV2LeP8iuxGUYEb4NWy9lu/fPxgqT10W2d2esQtjL+/kIMZ6UghZgjmUtcY0E7xSptZtOFf3PKhT1piwGVpHL65e7njYS3GO4z1vzdDoRE5nkXw3KR54hQbkneh3g94/PTkqJYp1WmnbaALY/lPEUUPzlH04e1GA1lkS7vaHPrZ4uQ7l6r42Smsw4jSSp7E2Pt+zCY+C0nvOkH2HFefLTIsNpsXt14kpHC1/xK8MKr+VF9+IVc0HvPQHEbmS3Za4t0BF/TphcdqI9fDdKj+N7GchDqNPIzW10IxiGvwQM8ldsohpkLbslZIlb0oW1pB3AaJq63gCuP1ezSe/wnF/amSd8jeWnfxuvhUkg417sy0FR/5cflesiTCdizWY8/bNFqdTx3+MvjDpgBf9UIuI5dQH3U1kwtPdBIbMFwyNSmz6F3Lau2Z8czVZ2k0beNifs4ScnLDzRElqtvZ41LBT+VNHUxuyqaaFQBh5H7rGxPkgk5M/Dzh+wtfgPqrtISitvPtHM2Ei0VLUMIoe73jQdrS5yGiIsSNcTpa07JmocgR8i8BFkbIQ5KDWikYzL8L5DT3CzZqG4UrVyQVwQ/qbg/fnhzJaILs0i7VQyVOpzUKQptBUVnBFcq9MzXiq1YasftBabIK3iP8a0/xp49Y7WxVySjYNJPYIDGqDdJgG6Ph70+396D5lw+XEJ60syy8ydioCLaGzKeVcIVfqp3BE9/j8d0I3qjwDBg9Jas5X6jSfRqUjVa1nhW6uv0lgMOo9gffrpzjyB01gw9bkDMqqHFXFFWyvmaC3H67QeK6Dq2tZEuMYm+JB5fwjFBVBIwr48YQopF4RaDt2ARalcMdp8T5ibodjEl9dG3qcajSkM3GHMeJ1pQJUWSvsZY5dcNXZm2k0h3cc5xFEfSQSpJLOTLnhQfyGp6hz3iQgdcBg4/hxxeaB7CqRPeOzUhDDGNZjyEIEcg5kWmwmq/z6vv6ePcgUbNiTie1xJjbJ7IGNIyOPZSRT6BcChFTnXyknbF4sWckk5HvYOZgtgQzjJ09lNB7duDTjAYmznanTD0IudK12HCooMwtpPBad4Q1td63gi/0smjMruFjbdOb4eMq7bKTCbxYNZH3R1/KXX/PAVndV9LWkOm3giqMpD0NqOLkIImHPg+jEjveP06krV34ci6GT0MKdTLxACutO/h+BdNgb/6HoKMCs+8GgsjJu4rACGNVu3TKPdKlsZIQeSD1mX1iyqg33SMyNWVxEalgM9Od4yHK4uw9JmnuyFBRjxzA+0dW/8/b8DHwyR3PWmAW3pb98u6XOsatVZJUfDd2A6H0JR9KGCV/nMz/jEgfvpWHLF3rB66gWMqOuTsCXhf8XIhy8qm5Yy6YXNBaW6Rh/Lw2USX7CTdLLDwnLoexMgArOW/cev92tvbLIW4tAFZ+urgCYBg7f0ajvyRUMNKjd3dyCN2h2RnSiTRWFlO6++bV8k4K/ZLiCuPe9X4015uHmhqNYi6EmRjbCKtwGtEoeXJTo+pgZXG1Os+ZMKc/bCrJYCU+YWx7N7lhemWaxfRdh5p1+/HMoBkK7rLmg6puLrzO7PIFoMIo9t/pmCpOya4gpwn1EcvUfRaOM7BKXUh4xVD10WKsep6MK7/Kai7irIQx9CIoVfN/hI8rHRjcDOM3bMnjNQv6T69/EGHtSFQr+EIPg4oZjUgrjKhvgOvXEJ4jaTP1sOKRjmmQsoqoUxvVLa5gvFZLUV23mIYZxtXDh3Nn0vNPXaw6gxfbUB2q09bYaiM/YBz9CR9KAYFsnwp6d4f4DsrwzhBwUe/phdqakvNu199Cyf8Bo+wPpR+Sjg9tZDIzI9iugAebwVUP3ppUw4ZSXHnbsi5ilY9YGEG/ryOSkOSMxdyUzy82sdvwpexyUGf+h8fvmhm0KoFWY2stKxELY+Z7NPY51PSBTEaIxGZ5Lr10ziwRMomekkXUFVx5/Ck+q3a5L4MkjEPdm/8x4JJccr2maACppa8z0qya9G3Yrk8WSYfSQ8QmY8xGZ/gBo1SPZEzJBR1Ts2h/qj3sw8N5d6ESvVDWzKDlukRr8QwjU49oFCsOH+lX/ekYePsNfs6ItOUsW3RlibBXDGzbW+9rT+O7OJfBHka0XtAZdIVaRXgrpfeurZesTQN7+FBjCHgTZBVoeRHtNSH4oSGOAM2NgFZQiJ58pHdUkUM5paGcIjtC/TiJ4xE1jof+6vGQlW8NSiLvw9uQ/evm3WsDXR8xFrZHE8XjiBzdUKZG9OFhZYgNj7T18KhPxd3AbEKPH8+NbuSofA2bVSvgw4jaHh+zGelJqTDr8dWdRGdxG7n0Qkitm4j8uq2pGjIbHO1HjKPt+IpHMbx1si8DrFob+vrAHPnlfRZPXXLBQvjwnjzpXtPG1LmcWOhJP2IC2O5MwEf6cIq7OMJagsHrCjklLf3gG8p/VAWz5lb+VnCGcbk9CumPejIhXU7hd9LkcxFFrK7W+jEtLSGr50jADclfAi6MxD2Q+kItafnQVppS65zTaKbfZvMglqfDWFeiwgqiMKp2nw6U9mo9ZFGC3HlER09tCk9SyNffCrFoXl7OPaCxZZeVbhGjYzvwXwWfw0ESTHzFZibGvk6ixbX2Rxu5JfWrB7+90SIvNDNuOetpi/EMI17bMpahR9pUyJGptD6jKsimx6uFBfALtpHKBbP3259fW72/IaW+jdj2CaNhz+kMosiZv/D/NcmwlEJjWQ27sDNcv05yDbe8bYStTyipStVYkj2qbsxxOX5B7YAxxcIpK09JvLlTRSVxavPI1RXQQh0qZBJFlJz81y6HPzdL/IUZChv62VHkFdM+PIs7tU2lvdz+pBWUYWLYw4QulDtKDu/7xcz6ZEyvDf1+Ibe55myBP+/8lcPUEqYwyv4hckHcQox8W+Ld1zjmPs26OGHna19VxWORpagqoDU1aVop7TEWf9eT8NYl+aq/Z1j4psel5jpKR7T1KMgcTZHBF0bkt+E98IAr0hN0iOjDUjqwdElG42upGkqFbTgrYQVaGKP/eI6oq5WvpEMVosDG1nT7NJh4Uj1pGebgtTHwwgj9w/l3Nf8ezMgBjTEzumOAEPyUbK0PP3OiAVneJmUNZtxNLbusgAtj7w8lI1c+j2/hx5vs/crDkVdQ5oakFfvi8SjDOjSVVc6P9qWWOLGJQ+A9Aj/j0uqY04jsMRVqU6e7d2e6DzCj3KN8On26lN0OaRQLljqi+5oi/i2L6yN54c/59RSHG8b7nyec9CR06bGJMbwHuKThUCZTeOY6ULIhnUSb3W+6mm0JZegRScVv4Jf960BRnwdyyv+//26gbUGbhaSXhHzoZzDXSkbRS5bN3ciy4aDCGP8LQFLsz7+TkzH1TJVrX5siwrMhx3z+P0fZKHah5IyVDlxNmiq5Gw4F8IWx/8dUjSA7nNOA3lGEgj1mzItSpVZ6BJCoULDSnonrIxlzDWcKZBjPf0al0MYrUYAp9XME1YdQfmm5/qA8V7YepZfrKDMQw6h+6CihpSQ9vUWEhDFtzJ8NXyxkU/jBpSWJjoldN2BhRP8ZneirIDFVpE+VuQ7y1DKuDmNhnDS0Cit3M9INJzPAwij+Y5mwGYEopAWJPjVdE4+oEpFKDEfOPcX4W1jwv6+/4qKx9b4VKgzj/g+gnhposQ92mqbH4rsM2I518AubS365NrLqYPYFI/QPGQ2T+b9rl1chh5yatx0wwZiFMw+1JcGcQLEItlDPasDWu46gXJEL6fGBGbf0chE5gBIM5SmOWfn4tQYcmEPYEsIw5n5Xa8T61IdnZmAL3y860D9dj4e+fCxdhtVsCF6Ve4Vjw1Jowyj9A6qmUPnvCsGhdzQZV3itaiJldh/8kgoWDpsqHCu3+e0ayQyeMAr/UM5Y8g3K9IiGY0rg93iEEGD5h71THonNw1WpsaNLiUugwih7fWtyQHbHyQCp5bE7bS8T5dctGVbCrrq2MY0yjLU/FTrZkf78nwreEjORhlkJdJh4gfZwDVh7lxUz0EJPTarYT0y6/gkaYg3WcV1GfDmgML7+hI8l6UOPbYLqgN54yZj0J4JnJfkvPUNTkqzfqQ1Z70yAi0EOI+vP5YCHviSHScgRJzpNlsqI7HUymPtRnjUveD0PWznjR8dA/MDVzi8YW/9oF9ZS8FgRXOWfbUi+MaUa6m7oRkGVgwuj66H58jz4tezzAL6RZ1rRtRUf+Sa2rngwEMyTDS273PEjayjDKPs+DRImSG9Aw1EiTFGhUcinlV8Lf/yGZsjnX/pw6TCFJVRjn3hSkZ7+lTNNdVYYZx4n+ojR4xeaByWngbYEMpSlpx4LyQGLxsy02enREB6qdsgkHR7PMjjr++x60SyRK+aFLPKoE903uoG0AjqMxYcsSTpQyg+YMuuwFasdJ3oz/GcH4JDmkJZCGsbkH8rIJ2fylgkzhZ7IOIb0oDXS0D5BmHNoc7V/QazhbueLKzOXfDjG4lpOf9lOlC7XWmLAy+PszfWsrmazBDSMf+0ubmUhF9hS9RouOSzaGTTzCJtLn+Vvs+1sYYxsl065R04HMjGwttKPZ/6/q5GaxaVv/dVNd1El8DaQql2BOoyqPWJhyLwZOR1PKMKhLZnop0DXncE3kKQLn2Njb9W7k4AWkugWxtR2ORtJ7ZAIRZEBsT19V3JAfSOw/RD+NA9alcwwXRuwBCyMtm2FnmI0IgeLYuzdqcAEZD3KwztyT46kNWQ+H1KA5R4vP818817A3Zu0gjVcYw1Pz4f4cS5vzXYgNVBKD8tTvhbNi2J5SsV1OydvBUIYF3tf4vfm/xRC28pJcW0CCf50ytQDF0auFpuQDxTH0vJR0FyfMHctxAriME72wYmO9JPFeeXCzjtp2/3mAeyZgWsz6YkVSMLE1Bc+k6RNOXIN96cibFlh0VgyvxIPapcO05DC5dRDKaB6P5r/yzfL9o4MJNn68ssnA1gqiSJt9DT/D131hyNBvQG999JsHtbyYtX63ZSxgiuMs9dd4fw7aYmAccQwM71Fu3b2E888juVS3zKetjFmXkOCa6pgnwf6RKTJMHBBswzpGbzWp8qnmo5+3OZj1dT7NmpqQmdkN2SBAadz5mnXS6WddEaKekhp9RLxasl9og9bH2qyT7Ru/IOFZaKdbYyH30/m3wUlXQn/NVDXh3cYDaRpdPLmd/4+vf65hXUkHazADGPl2ww5srAL8DEVOXtcKviB/NWj2daH9++toaqcZaaLX2lgYRT8HoQv/o10pFKMm4U9diumz6bwpw0l4POiU04x7xrDFH4w/v23ZAyRRnHST0b0FjMiz9977NCR4PT+xF/zkOQG0tUjDOPbW9+YIBcJDe/YABkS/jyXUN1Gbd30W86xsHqoYYT8IYMSBGoMeAdRrOb/NPvIEzqRgmdpLqiK2vDRkz4Vd82dIToXHRs4y2Hpx3pWHbPggYpYBhlyjG/Dve8bW8hbwRSqqmdcKyGuaORDzfpQbC1Pf3wmImaMpZc4itd0vv9ij4N4yhdzzVwobHSLO+iFUT6GYmxfIo6+5/DySV8O4QOh2Yi1+NrpFL7UUPVD3gjIpcYXhLEdjMHfTzTjsLhhO/9DH7E1K34Kz01IQxjY08cX1PC1WS+bnmAbDzsrgQ2j8XuSQ392xBBb1mU+NU1fpNUUzYtpTor6AgyhynkxYCom+4kXJNBARkgJloulY3rHG5obHY5egCOUkpfe/LueKA7h+SBTxWNGDujUUAeeUHgwzT0pVIlA0HFcS+jCCPuvU6irSOtu/o/i+sB9FtPrhvoT5oWnnIGPC09pAGF8/HkymH8PSR9gBL+CZn2+G01oODMObeyKod/cpbBnagBdHFqCEca1/w4BnLQGA+xYy1PWNpmRYvOCkrO2sYY19ChoMhxS0lbJyA8ezi5mL2+MswV5+l7Qa9IJv/xSF49xE6Trcj/bCq2AkfK7i+3Wk1v4IcqkTFsqYiHNJsofyxhdeM26k1zLEJevBmwyX2Ujor3HiPhTkdxCAEhCcjoasCDxEO3WryE8UdJmSnDDFZoKz5fXi8PuPuNBMyHmNvWt4A2j5Vsz6THByIUvA2om0Nw7aCe7HXLCbwI2enWR8+eP1vLoph91tJE/36MnRL+xvySQDMjvTL9nxOqmLaGyu7/kkV3o78nw7tWnQRZRt9FXPKxADmPxu/M/FJdkN4qSkSm5t6WhqHWttobHhqwkzpUWNwujEgNPaS3XksmNmH+P+VBCheYp3tAWwFGvLwATxt2fy8WEMZd6xaNTw+fU5QSDTaYnrOAJo/J3ObwJ0llIBs3KCjd87jI1mJEOvIS49L2EuunrHR1rDXYY9b+fwIc+leQsgWhm8haYa0QKgKdiFkw4HcvSs+6y+42ftpzUq1kFPjoM4DQgPb3BiJwc1VscyK2YNlfBw0Dq8atrl0g3grmwEuNyDHNkyLXPvYzoALmA1Yp9waDEJx39B8twS4/Qm4czNyt/AZg+YGz/iaQ+2fVuZBIUW9FuPw7NG4ievAVtnIRwgSiFHYy5P06GNNLeN1GEFPl9Cg/g3W7MtWd9ltVq8p7/M1dmHSPxNLowgv4IMKK5rTAyudILGccs1DXTgYyjSZIt5Pt6iqIEXdMJ92r5hMt6S9jCmPivI6nIYSK4Ca38Y1SPZgCvL9mx0hY6ZsJWb/gBY+vbMtF/QLqYFc7jisbSYiOkzYYuYuey82u2HGslXmHs/IJYOOLxUC9gG/DpSD3pUbPVp2h/Lvw3D1AuVlmDG0bet6UKKenLyAxVK4+bdRZWlw3d5iitKnSAWgIUakdPZ6Q1YOaQ+phN9W6ZkfsAYZfw5qgnRVNH1JXQ7o6DSCELo9zP5YycQ6c4NSv5Hh0O6YCTCyZIC/5Glgl9ydZQyXp+2+KYpxJaormxzEohj9HvPako4pj61GLRFfwROYCvujqs6VCzEdw+YuT8vvQiiABH8Gfw7Xwke6Lr2o+O5GUx9vYrkVUsbLvUmUIXRt93k5tEH8jjQx8egal/xiVfVzwYCOa59UjHWyxDDBXZC35DfdKhwWTAhDmpxm3Ge0ekK8OGcl8uRVpDGOper6h2SFVK3jIzhLUifZbx8nHWuBTGRoCHR6WEg1qT9V1WwIbRsAe3NByRA8beQco0J97FjoH24d+KMSO/vG8m6qq6B+qyZxpuGA17wrggu4K0ZiGVCeKLKQPjLNrStmTzwPX8+3oucGWQhPGve8zTT19qQT5C6ueclX3h5ao3byPdYdmXIQnjW/eZVCOW567zlC6npx/AYhp5IW9dB+kgl4UcRrj2GXxKMdfecp35H0OoqRCuAv5LWsH8O3yAxpIaEzGFJmBU2gWzrHrHog25Y/srZ/s/obbkyQ3lHulTjw/HBuwQd6dzOpOL2SUb0rChvqsbDi4bke0TxsBeyIBc8WgAIY2byXSFyU4rGUUFrsF8erf1Hg9oNduSXOF6kl/5b+Ye7qd8iGEM7NeBoj4PKGlT4SGOv+fywQg/bVAnoT4OG7rkUclBK8dNpHGF8a7zv4opVVJfd4zn3xHznJxTCudyRgVphfEtU5PXrscsqqkrUfs0N2VaqccwGTV0kAkTZP7XcIRsPi6EYz99TdKnaxMBbelrA+4NDnis3g1pcsNpBWO42lrA+yZtpRfbmLnK/VOan5aTwWOBp+LHZA8ewfg6UaUTaEm0ff7gLm/XFmcYv/8bPBZOztmIISBr3dBvGYhdMQUPFHCpf/gmVGeO9S+ML4z1bwkWRTT0oEzrctLmMXw3U7jYhyiXSJHdP2pNmYDGs6EMRiUHR5sbwqxADBsH9Kgak9P/2qO+DGdmE5C7S6kH5C0x4E5G5prNZZRhE4BzqVe5tWMhBDM6ksgp+NzzVxdSvSCKlSzF3u/YK8U2aKppoxL7jLqgeDdcn8SipC2DAbL11idtGtBxNkm29XeBIDBlapxETxZl799tfUJh9uajcifqKR3L3udDDeP8D7WWn1Of9OAdUVPTj0FqiT/zKDnsPAG0z++2tmuYNasyN29yTCsPtM/5QMOY/wsekK9KstEAHmRg4AyXXi+51L2mAeIbOl04xuxZ+RO9Twp1GaPkhMZUmDrFJ0Ja63doBcYBfXJh6dO77c9Vgm7bIubcAZHy4Msfcf7/7V3LTiPJtv2V+AEkoDAP3ZFtXgUYOJhTdbulO9i2o3CUwxl0ZKYpMzuf0rqDI3TVOmq11KOe+cfuDqC6bMdOZ5JkQKYdwy5VU3bmYj/W2nvtXVISGA/6ICS2B3FPj+0hDXqPiRxVW7pGdHFs8ytyU9AiB/7jG8XOQJMXlxMY/8JEp9LWasubMJ0Ai6L+r42D6yHXweTXoEfY7SfJ5594wO9FRY0TkyRLf847A4oogv8EugN2hBWJFKHdSbbAnHII8RlQxlBT9X/1kOSzXlGwokj9ExiZp7cwPOHfD7DgCkS3Pwes8xiffoenDieafz4RWox/i0zd2ytlAvRkRSrktpMhRzH8J/hFWBO+xuHUu/gbUXCrntrK6VWSya8SbiqaCV94vmg1IZQctfYoDv+zCHvKnF8Y2AhaFK8eV0fMAeebNDeo3bVNmr7PqxI5HNjxdyTzsg/JNOsexec3tFIDzs6VqabWmvGXL7YOfsQDNV/JvxvT6pL1Sopry2pY7YJg3aPI/Kbqjdm+BsoFKumyzN+oe9MjpbX3ovETukgPrhlwUez9CVY9nB1BT8UWuIyXWMMArA3y/vvK0StOyu8UHc62d8qyZOlnYbOR+HvkMVOs/EWAv9uauEPzER/eLT5Bs5XEWY8/mcNal2neGYouJUw/N+sIixTrfyAFhKzBgwEQk2YkzKbTrubx4/Lj4eQvHfXTewpa0ywt+78i8qWLOY09Sgq4hI5UmH11d/IbcbHSbDQ1eCTm902oU5ZvOeHoMO2+8Mrb6rWoC+q7BPf1LoaNg6grzFt6cUQ7Np9lhBHtCb+LUyrN6eZFmSdIyoe+BdmUUhOu+2qI6fSMD4mrqNQ1+qI82sspdnqKN1sgo1SCSx6BZlcQDdTIghJ1RGnqvET1EPRCkcDL5T/gs7VOTvmLgTQHKyd/SUIiSEmC7U/sWphqtgPdtKIe02CNToPV8V3xZX7eNLi1TukE5xD1MW5c4iPkmhwnIweyX7m+VDK8rRqF6yS0URTutRoOx6zNoy9K21eW6hrfCMj5iBbxEf5xquxZ0vRY5ArmalpJLcAYSdHCuMcD1uI3fUWQtA2zf/kdflMwu8RPGw5VnEqFrQDOfCSbQRlFvl5y41dwpILJv0GOCKvPtvlgz2cwp2etZxaAqwezlzH8CZmyqmSEE3RRZOs+BNhlswZE9lBjC0Rwz54rd0JWak3+NAO1wY2EXrYmoBpFmTdfLKLmp4jXFpfmhn0DiJrsXFjnU88474WVvg+XZBO1rPM/TuIWRaI+LiI11LMT7FzYksPJn+zw0Hncyjmh4XDK0cviToj8rXWKfd2HkeixY66VtMPZKWgZ6rifOJThFIX4hwywx0DAlKpMW8aRIBfZc4Oia6/xcQWs3gMNHaHGtnOZ48XenPFup6xOBtWFnAOlfGuDIml/igf98ZCdqkDdSmFzHO0+DPpGg9pXAY/Cee//pW8VfPRzEv2oie8W6K451wS9yR8215awHrz/+GnFyCytG2vuePJ7RekQL5+/qonYoESCn42r8aHkw+EzfTaLqVgHks8vEXy8De9Et/+qe005E+nzokoZOofFibWyyruTvEpJB80+vgV1Lzi7uOnwwFbf52E2zYqIoKtk8KpdqeVREDzDOwU1cnh7KCSrx5gJiIZBDRXb2Hvi6pbsZtMLp4VWk79dgCVKLbhSHREIAw1bLbiyj6++eqWznAha0uTnBEWUCoDFyhAm/5GmIo+lwO9tbwi38YuGHWXv132GvzX16iEqSQ7wmnl+hFHqwE8qDvHRfGGH6gsENm3REhLmy6o2HwkpK9odev+M14GIovfr+PO1MBe9sE7Xa/txh2ud2dMfH3FP8rCjVXzjB318mT6Ftk3SBluFkwfWAj35DdiRGE4eAsJnKmU9ZGXpLp8TZwBG8adtpTvAnpaPiHLLeLYQnhnv5cqyUxqRfDm981wwXZsUx9rs8yEw44dNXcVsR3EU3YBlFDudVN/SC2jX4YXylTSQdYIzilFt8IA1+0LecWmfwUzsJpt6jPiQ7BIkdHPP/b/7tRI/ZlZA0qTI02ZfizBSIWup+B4G4tl2YAZcF3I8vBUwUPOOBO/naOYwihWZPH1gm4MgxbmecjMye6aGkz8C6Noc/owX0BwCX7UunhN9W6URKZeuV3CCOXJOW+h7bCAhUiPRzV60TQ9hVK/lXFCfeRotG5YoLvafAQj2ieMP6ynK76IveYQvx7jOzuMJ67WnpLoMq75JjIb3zn4N4pLnsutfMMzfaMPaWqj7Oy8Wdpskb6m27vAwZhLilrUrcJEeP1CD2HURhJKPWQtEZA6xrp0LSSxmno0tVeCVRybylmQuQbZiracTkFGCQAuk6A6SFEwCW21Tv2iDx3R40ccwc8Lrw4bDkj8fvjwtO4UuSg14ypEX98q2z7Y5sRmFSXfGZm4jyEJrFAozl41lkVJnlWs0J/ijZIF/xOYrBuxaDKkCrQU65MK2NH4pX1soAJ8XN8sU5zzW5rBG+rRwCNZa+Os6eVCsAX01tvNp+u3Cly2jV+zatB9pzA4xSifYN3Mbil2ESguboj1sMvxFjb6O5ffqrPCQViWvluUs3ZxgjRIEWqLbBy7Zz9w451HsRpGxbGftiWOpQhWXO8BVefjfhd3BB0oUOMQnyOr3nBhLa2Gpdgdy3lAv+xRHdeo0r386rN4o/WAfhkoCq3+Fse3UTnobzEpSAY/y0m1+/Pa9UeYkqVKawSmYYW+2r8aUFTI94n3GRXf2nPBqg6zK4cwF0LZI7aCHSGMNJYh1zEVi6GdEGjvGQFflDrQQDbS62oETkJG2LSN8n+d8TNyvO+IRfJmn1T4pmUVoX1pI+cg1BypKMjjFGiLELMhZKzYnlu5sFq0JN1JgHp2DV5vrkWlWq4mwpN26FyHMU2jT8CKPbsZSPN4DiKVd5zcxQN0E82HroodfvqKo8pcmnCCL4v+v+0Iqdsr7FFnWUt+naqeAhc3mt2rCym+YF48p+iQma/ahB0ajZA0RhX0BHeJacAM7K3F7L+YXT45AQgQhaMgto/v4tYRYo4jXk9h0jGBParTAmCrOMBDTQSy+Cb8fqF46YsJbKWYEFEWpGqseEbCDMLS5roXTP9M8f/VClidUHWGMIlSf75fvm5NKge2asRBms9vobzgo61I48kyrO+GoRjGtJxyf+JhhgX9DOAAtTJ3tO/z6PMMekw9z5QSZizBXo5jWCynMIeh9NSIuUTQVBr9IjymInfFxhNHjQpu9zaUs0fzBudeAjaLIDoJ7hU9b3VIHJ+aOkhfgwl5be1oOLf1qnb968hoQ1pJBSF89DBCD4X33fhyEA5uqPeM3CLXPoEO4KwiIO2tPNz4LNtJ2Uub5iwAuBtJqFAd3LgaKHSs9gshC4UKoTUHy51hG3KCV3/C05c/dpHi4HEzcaka/3WTM0Q7I3a5iV1wQ9xKzYm6WFF4AuA9rTy7MlRiMzHU1scqYyx/nPiRjjuJ/Mc5JCFn7TvQIASsr6j6JQaQ0/r3TyZ8ybSQ38QDPcoS66iZXF+d2ahRHfA5RHwKY/J9krU48sKWtaXlhmjrBJ7N2rWN8FxnmvumybjlA5rmTKYhRFPEZhKFa4AFfj79xra1ZNdFRWUStMlJzhajzHlc/cLVNEb9N0NJY9oGOJr/ZrFyKh/IxfO3FA9a+lSIDL1dKlBUxEulRNoUy0p8DfxBM/jNkB5J9RByFoR3BrrUa83lbyCv4Co+H7DoSgm5ukaG0pqN+LjI3zqix26aEuCcUO8DHN8J8aDNui7WsBg++iPwwWx6Jocq9phO00XbdoqfYRWchyn6soEwvqJhRuCH7+NEjzQe1aZhRIsIZVwFrgHi+rzlbn5klA/bp+zGe6XnvGadlbz20NEWbi5mQbUoyuDbXL1hzZAovbU+FZOXSjjX0eJedapBqlGEBYZlpDh/spkFHGnZgIyoCdoL/aZtEXgK2DqwNhjY7Mp9EzK8ZT+2+LPbp2KJDXsnE+qS2IVkkWM3ZkGS+dpsSCY6go7G6ZU9g45JYoqprfCkwb9JRl2vHQkKGmd5CNfhtl8esfU51lFMppeBACsypDRjgyx9A0CPWQuntvTBAzE7+6g7SoefFqDJCzEUG3aEY3UuItBhgvSXM0HhGfF3349xGy8uBLM94zGGL4tcOzAsxWZNnBVYLa7R7tl5Lrcgqcplg5SY3XBRlOxSbdgVj/PmswSUIe2I3RYjC/9lcWpeSdyFQb1yebdXe/CzBEh5ZcVGD7VB82rPkOfmXHIEmDPrO+Ajs81DGZojVh5MH/QqBIO+q1ebbH75YmeTpBHcUn/YT/ix21FF928zqWsVSxaGFufmdmMWYS+A0ynhtxR8qeC3CKPIMu8uv0GcXPd6zl5VJff1M4beUrH2aN2X6GaEKVmYLYEXRZQ0NPSy7ggifD7Ufei6sreSrA/ZJZLves7S48lzFDLIoOqz+DYNPE4ZmuseCVQPbsHkz7oPQzGXn5l+XYw7IB6wpWFHDsv8NI8GO8IsQaZCu7utd6E0ehljaM3wLTSWGHZ2hyq+IiuSdRIuG3S7FvLYAv34cPl4SmPyboPYX+XjU5YjrLJ0ljTk/ELScOKOmaU94GOs4YFcwWGvDgLB6X4i0U3y/w1sIPdZ8Jp2GGkX4fzQTPgNgxvI9spPpR/P95wMZwdS+5ZXYHXe0RZK7bQIbW1V0ueArdinK/4jryR+BGCrWvhXE4c4U0v81zqM50fVhq9xEbHWrNCego+j/jwOTPOJfYjucpYpMXfyNZm3sH+D7Q37DyLZbGpnJB7YpjFFUf7MPWmKquIRITH63+f79xw8mRorhE24qHU9+n5/fbqhuP859Yn0JluqqrCk5qc8oxv948tCNlGbYNBG+LoCPTKpgHlpX+MVYW3UxFkBaeba79nTVvaggtvMOUmZCFFvFXJns4LJLMf8XYRc0Owd8GXaTaQg26JHgylT5J1oElbDyf5lTlQdcFsBRgsAJjExv31CYEG37lpT67Ejo52C3JKjzLUHxqKP0giOhRhAI9onrUAR2pLuEeL46+65NveGYWYni2w8VaymYWxd9wR6lEJxyESnMpwMYxsRK3RUXQ2tCY/zmN2EdNpqF4My3n1MwowSCtu59xU7vNL4fiq6Fsh+mQDODQFnMlbEbKJTS2NwueUjzyXMGbKTnBuBb0Oyam4t3vGe3oYd8zAOl9Hy5Nj30+IY02hOFW2LM+TQ6DTlKN7iEW8728XHdWGBr4/cLO8r22vv8aMch03YDdopuD95hinZlaDYX7sl7tI939xf8HOxgoIZi8mA3pqYgma/cPmv+rQ9pFG7RgNveKzngVjGlLoAbJR/Uh6DZIUTEGTN6ipt3u2lpdHdts1ZoYHNJ5CbgbEp/X+1+YEGJRppqKD3GfPl0Y2BuGpIdw8jyDa3LtXYfOtDJC6rlGLRdTTONBeAiLy7iO7zts1OQsbSdj23q7EeuXAysQmWn0nNnq5gVFwCNYmlP8Vsrtj8mfN2bfS6fb5BNr889WfA9lrd5KbTlmXWscqHvQE+vrSeNcI9Dts9ZE/QIJLGr+Z2QnU2X+0KLMaQd59kzpWCBYa3stX6VMeeAzaitk+bI+PTGDFtM1bHAdowBhDKqPed35tMaQ/ggy2rwsge36qZPJ6GN4mnP4gGws3HQtZvKBS6i377gD58ysV1tmFW103QCMoqZNatPXWzsFGvjM9cgI2KqmzxVcSkgjNiRFHcilcvYM5+rfEhbcXrMCcgoNvbR2kwYhfMEBoTAmXBt57J+kcHmoIzA8u55TrBFUa8n/FHNPAUtw1ARS+mPLmfzabLN9YhHUYa4tVtCeCWtNfnUmBdZpDlLT+FXVwwTHbHq9M+eCLhlAHSqbrOsmdCgencOthBcrSYHuwBbFAfb5hgpzjmM7J0m7BS7WFlJnnCJQpm98z4Mb00L8Plxrymdnl2BUr+yUxhOQEfOaquwz65Uh+uIzJRa3PQjiys7lJxHd0r12LW6yz3ZuDw4qzJF5gRqFPXffKz48eVeYnSi5mZndk6mJYDDK9aU8de8OXQprVw85GYht0EpAftC3Shze5qwPXh8j3DzPC87PYgB9yKD+2w1sPYyXTNhNsO3nDNIo/j/Y9B6zD5BfNMnXNCSFICG6mMSwm+fArfttU2a0igb3HxSfS3utpNxRwkCV2NMqNeaj0RE7A5r/Ae+2EPbnzH7BKwe9SWPnqi3xbON1XB199hzZvZe26B0ggYPvsJQIJJ01I/tgY4k+F3ixw2HKo7SlPbdtY1l7xxWMbUmjgzVNsi57ViaruFgzI3CaRdySTC7egwf6cPbiLIy+m8UibLV5N8W4IxSDc64Yu0+9Imd9RT+ra5V7F0fVzOYLegTKAHhs5BfsMfqsaMAfw4xmMZ5L6RRdiiUiXQi1R2hpIZCKUhbsr0AJ4hKGN2OJw+saQxBBWG3QQ5q7COKhoq1VNhVd6lw2qDHuP2gxrLhi1IIzsVASTAHw8A+5lqXMJo8zK8yXRyesgZXNzrVmWovqfYqW3O54i4uTtBGiQT7MBI9Vh/gF1XSFgmSiLQL/FcFsHOB71Ok58eEgFY20PmpRzfI26S0grO4a1YGDlWMz0lJSZyuPozlcztpGfGBjNgZDDIMD3lGY6WgRokF2ARIxFoQCBtjDXxkAf+bHZu+wnnK9lWqVLC7trlNIuzdJ4k8oeGK0FhfJweKTiYPevIwfFxL+SXmtj5whRC099DxK+hbpdLu8yRfe823BlWrObyPnu9WXXVDWfEuB+vrpMJex/9ZBWN2hH+bmB9KIc5mzG0XYK2WqH/m9ddw6OiSEue8Hff3l5qINLI+O+LG33HM/hHj76TdGbQfzbiD+X2BqaXixbEsYZwjH76e3KlKsarur3FmjW+ki8uJmVeDWDLEHjvm3QGlP5EzktcqiniA/QI7VlF4G6eNgGO1WCgGn+8Nv0uM82k161jH+sYHKthd4tNT7FgEXbilvKoa5m/j48VSbRCH3Npl1/hnkFbBbRfsJrTlsoJbsD7l0ZYdbbS1EMLCnLzjOjC7A3ZTanz32DGGMrKKe2mk23FidVuBbFvlqSIHGXeTdO84kFKoiNXN7yy1knCOaMOqxcDtUBHXZVsQdJ88Y7JcXN9Z2yzW33tju6xp16NvFn01ap6yjQEQM+819qTS9pBPaWdzBEKaq8sJvr3NmsdeFbBHmzC3lDZzuVfqu7daRn+PrD1u0hxv3ki3U9ZIV9m1PwdQ2yGPa/+EONsXakhe175qmJWZ23sxT6a85CxQsZFtY6Pm0PxvQW/h2bo07WF3i5wN13Gg2FEshqAn/0u0FKkjlVk62N2Cebsdl52ET6DFmUuu08swCkOThTSiIcghQewWTc+5NJXPJ0F4jM1irEaNwx3ca8FOVRASnliJFVrWaFZshVbbKGs0W0VOLhFnG+QgXH08VnGHNVSML8YOameIsvmh3pcxH4mDIrlZOJdH9HLp9z6gzQBtk5QaGhp6ko+ZSYTUyOUlaBGyNuCDWDsyH0bMqw1ZJ0aKPjxlvlDZILeCrWcy3mrk6faOhr4YslYH/zgH2uay7BsendpySXh4uL3WmPnDNgk3iS1owM7x2xNwO8DIZUv3L0ukRcNsO3l45GOAH7HHQ/YErpApzW7xbwSRAMkiFYH8LxZyzvA13yrzWEMCaq8q3VaP+Ui+a0bOKR0E9+pRSp38iiXuvQU5+szB+0JuY9MTH2XD3P/8Pw==\", BinaryEncoding.Base64), Compression.Deflate))),\n    Source = if ProjectRoot = \"\" then Snapshot else Table.SelectColumns(Table.PromoteHeaders(Csv.Document(File.Contents(ProjectRoot & \"/data/processed/summer_transfers.csv\"), [Delimiter=\",\", Encoding=65001, QuoteStyle=QuoteStyle.Csv]), [PromoteAllScalars=true]), {\"record_id\", \"player_name\", \"from_club\", \"to_club\", \"announcement_date\", \"transfer_type\", \"fee_status\", \"quoted_fee_gbp\", \"quote_basis\", \"from_league\", \"to_league\", \"position\", \"source_url\", \"has_reported_fee\", \"is_permanent_fee\", \"announcement_month\"}),\n    BlanksToNull = Table.ReplaceValue(Source, \"\", null, Replacer.ReplaceValue, Table.ColumnNames(Source)),\n    Typed = Table.TransformColumnTypes(BlanksToNull, {{\"record_id\", type text}, {\"player_name\", type text}, {\"from_club\", type text}, {\"to_club\", type text}, {\"announcement_date\", type date}, {\"transfer_type\", type text}, {\"fee_status\", type text}, {\"quoted_fee_gbp\", type number}, {\"quote_basis\", type text}, {\"from_league\", type text}, {\"to_league\", type text}, {\"position\", type text}, {\"source_url\", type text}, {\"has_reported_fee\", Int64.Type}, {\"is_permanent_fee\", Int64.Type}, {\"announcement_month\", type text}}, \"en-GB\")\nin\n    Typed"
            }
          }
        ],
        "measures": [
          {
            "name": "Transfer records",
            "expression": "COUNTROWS(Transfers)",
            "formatString": "#,0"
          },
          {
            "name": "Reported permanent fees GBP",
            "expression": "CALCULATE(SUM(Transfers[quoted_fee_gbp]), Transfers[is_permanent_fee] = 1)",
            "formatString": "£#,0"
          },
          {
            "name": "Reported fee coverage",
            "expression": "DIVIDE(SUM(Transfers[has_reported_fee]), [Transfer records])",
            "formatString": "0.0%"
          },
          {
            "name": "Unknown fee records",
            "expression": "CALCULATE(COUNTROWS(Transfers), ISBLANK(Transfers[quoted_fee_gbp]))",
            "formatString": "#,0"
          },
          {
            "name": "Permanent fee deals",
            "expression": "SUM(Transfers[is_permanent_fee])",
            "formatString": "#,0"
          }
        ]
      },
      {
        "name": "HistoricalSample",
        "columns": [
          {
            "name": "player_name",
            "dataType": "string",
            "sourceColumn": "player_name",
            "summarizeBy": "none"
          },
          {
            "name": "from_club_name",
            "dataType": "string",
            "sourceColumn": "from_club_name",
            "summarizeBy": "none"
          },
          {
            "name": "to_club_name",
            "dataType": "string",
            "sourceColumn": "to_club_name",
            "summarizeBy": "none"
          },
          {
            "name": "transfer_date",
            "dataType": "dateTime",
            "sourceColumn": "transfer_date",
            "summarizeBy": "none",
            "formatString": "dd MMM yyyy"
          },
          {
            "name": "transfer_fee",
            "dataType": "double",
            "sourceColumn": "transfer_fee",
            "summarizeBy": "none"
          },
          {
            "name": "mv_at_transfer",
            "dataType": "double",
            "sourceColumn": "mv_at_transfer",
            "summarizeBy": "none"
          },
          {
            "name": "fee_to_mv",
            "dataType": "double",
            "sourceColumn": "fee_to_mv",
            "summarizeBy": "none"
          },
          {
            "name": "position",
            "dataType": "string",
            "sourceColumn": "position",
            "summarizeBy": "none"
          },
          {
            "name": "age_at_transfer",
            "dataType": "int64",
            "sourceColumn": "age_at_transfer",
            "summarizeBy": "none"
          }
        ],
        "partitions": [
          {
            "name": "HistoricalSample",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": "let\n    Snapshot = Table.FromRecords(Json.Document(Binary.Decompress(Binary.FromText(\"zV1LbxxJcv4rCV18WRL1rmrf+BAp8SUuqZU8axiDZHeSnerqSroeHDUNH/Zk+GcIczB4GBi+GIu9tv2/nNVN7XSLGV9WZbc8Sy44C1LiTERGRnwR8UXkP/7Lq/ucz0T5Y8Gn4tXfs1cXYjbl5avfsVe3pZr+OMybm7/+bJ+XQ5Grgrc/rtX6Dy+vjxffLnlR3epfOOL14vuB56c7XrbjhWs/vhXLnwaBt/hofzh9+JHXP379I+2Pfc/79cf6r/yo/63Th8Vf3A2C9pv3qpK1VEX7vXM5upUiH7Xf53fi218WxK/+9XfshcSns1zygp3f8Pv7+ZNZ8nMt9FD1FFvLrCX3TWL7mQfFDiix/d34W6n36poPJ5TMnlHmd0015YVgh2J6M3/KKbEPVVlPm2JkEnzdGKhTD2Kj+FGGxA9DQvpoN8rWPrehi71cfObFSJTsbcUnZkVciJ+GvKpzYdLEmXwQ5b1SOaGJIN7xBpQhRLGrIQReFq589FNFYlTF6+JRsSNRFvMvWiGPZl0cjEVeCaMPONf36EDWM0oRibMiBrQeEn/tYztO4VyVd1qYK3Unysqsh72qVgX7IPPcqItVNZlVoW+HZ1RFmDiqIt5MFZFRFZdjmcv7e8EOVFPLYqzM6li/BX2dhfaVvtaIWR2ulvHCVdoUQNyKPJeqZnutj6j0LzJ7CFXXU3akSlHVjlcj3fHN3hIrII1JBWTbsYATNf9Z+wUdKORnAhmI4lYOjfdgr9bhpZbP0dNw9INFmDSiAz9IAyQ5ffSZn/pRkMXPX7cRJ06akWD7QhtDcTfm0/4R80rwnJ3zUSlHlBWEADIEqWuk8GIYKWxGYVbHUa7KFjd9lGVNRIozoV3CpKlE4Ro2aWXgsBlRyvB2s8GvZqG/DvpqIzBqY7/ko1zMWOvo1DIgvNTHV6zYVxGLWBG6KALckHRVC1nS74aY/cQP2hwOpZq2aMqsgat9dibk/aO8c7wgC1X45rAZRI5xIkxXP144TRdn0QlJAa9pQQ9hGy4pi/CRGmIqWuiEajtXYa+oldS5xXEpxaO2BSJgrseFvnhhETT8yKwAnFuFtG8YBKGXJn/9+gJAYUvIzGFD/w2tC23asho7IUkbdPAX6bUZOvjP6MCsiwRAh1VFeD3vhBlHHZSyqnXIUBpWFzwfEUDyWy/wjTZOmgdR1E0Fs27CQ/g4hHq0i/D7QQgdZE0aOBTDvM0q5JDwjx81emRvluDiBZAqdSDlZJAIAYD0k8TNMwaDeOXjRZBwg5PnSlbzp4odcK0Hygr2S3k3rpUROdidY0b5Bh+mVgBKx1Gy8vHCGtxc5ZWairxhZ82ETxqzHt4WtSgdlLBwCn5gVkLofA16lhnMLvFaA4RSsfetF5BEOoUKLu91riWKZwxOogQCOXrQB2S07GGYbimhvORNzi7V3Q2BE9dcnCEY/KGm8JG/lHxgltwVKvYW2+z9TrnUvk1jXbd8wWLw3qK2ZL71qxZtOHOflDwIozhJB56/+D89o6BvhkezmWpu2L5q+GhEWP+ZhgJGy+9URSCqSlgJMXX8fVGhPzA7ff0f2VQLSNymB0RNDcW/Lrde54tGlzcYOMnu7w56l1DMnv5Nc6fY64n+LROq2H6kf8vktimN5aNuyXJgrKIMXMtHQQJjHrZ+sw94w8tyxk55QQCg9UN+kRXoX1Ww86aQwzGO/mYrcC0kejGEQRgKEl0HnSUVMyIf+MQ/9/f9QbAoExgvP5Y8pHPCtSqa37PfQoAeff81wj9VudJHyQvCB8LrQHfd2vOnegxYCyD0+9nL0I9FN3cVOmZAq+fcu0TiLeupiVEBsEKSAASwiScwZwGo0UwUyvbynTcyhylQRqRAq5e7n+Q9/X9ojvonqpoodvzAy5FcOnET/CErY7a4H9IlACw58v7fSn4obkXbA+mHd9A560SgVkaYay0AgUp5BpvLINinvRNcs8jLIHfO7xpZEnFOn/VQYx1zamfB+AP6sDOY3CDRX7h222mbU5v9stHe7biR+sznP1MwD2Z3ljpHQtd3sPQgwQnWglzvBokZ8R6VophIwUaCnajirl+o71YAJewf1jgy+sZ7vp8mUerFWRaEcW81mMO9Bv71WH6qWj2cybu6nx5s1b5lHdjYN85iVPoEju8lzLHdBTPEO2z+94u+yR9yPlYP8n/+jcA5UmlDqaWZVWWRv8V8/k5AyB853oYXnt8F5p3wkSqY9vBDijGAeqUWqOvT2U6GO4MeJbe3m/XEeGbnf8jLn2TBLuZ/mf+XQ+PHmugF4OJD0cnOT1vcXPvcRqLXobT5ui0FmSu8lgiYghgQpW4RMBn0zG7MsPaDLO9kzh4WrdBPBJ3sWjW1znHvCeltNvDMljHbQLRs6hCZHiV/sJsFPoL4NheYGrVx1siKXTfzLyV1FTajDUULQzArwl9yRwhDCOjLkPpxqNW4/NrTF5rVsFfW46Zk51oWwiEgZq0tBnh0xpt5qPETJ6QSonCA8n63xs9HUbUciSN1ywui9A1xsaUCHNA0icxDsZBkiwS73osesO0imKPhWaMBL3tjIQRYeuL26heEhTgRpD2jj9GxTSHm+HAhW55MxS7nTyTrmiyD4xThOUFyUALoh2/EDDBfh72mbCl1omDvNUZq+HT+RBXDaP55B84MQgxYHbRNhOsf20kV9op6rIoZO1bliORZotTRFi+eWwR/Q5ZBjCSIe872ylI+8hue8zvCWe7V41xod8EO9Hf7O8wWRmQE6RZrg+QavggUx4rnEyHuafdgvhun4wft5Tg7feAlr6uJFkQSWrjg92rZRu5RJY5bBLUkdfQTnUyfvd1BhPNnFx9xxatpowPH/M+f8udUyWQH2kiKmiQPgUQKFA7TQYZiJn0h0hT6Bhc63Qc5rFXJ3lVyOhaEZyCjxYqB9ENPaTZwQQ3+7iANeiZRhEPsMJqyCADXaijFiBtT6XWPSeGmwNgwSCF9DGQT64zjnjZgRgwnOjawQx0zv1CMQkyj28t3LnhVldAlmOFjCguLyBC2YwdXSsd3AhmsdgYcwmFGVM/SBJ08yKN71w2JBum+KD7xqSzYtagm1MwJ7pgAvxfTPBksOcDJ3gDiZJeDPxUPWgOHgu2XzYzqmX9U+W1105QunSM/ppvGKawjgwCQZKsfvRn2RL9QDidMi1qLKafo5dd1U9d33NwztvpBpArcPwd+cBue792Ulxrjl1PVUBRi2C23dQ8Xns9cTcWCgwShr+Mzt5O6xH0a/x1rWFTzSiNIJHpKOX1Xupy3TpropwdzAWm/nC1GlEUzJfmyoqhvdeLk5gzTncBBCaCkHCarnz1Lq2ZjOGlyqYM/28t1UkCVUFA8tI2iBRHNHcKKILlD3u46EAq3UmSe/6m4Ezk7lK1XmP9CJEYWIr2lxh4BVIiNAmCDrZiB/mfFWkg0/+WuIe1gg4rJsqwcONhBL4f4nVi0YD67ywgBkQr9Jn7AbP1vcznVtnsxkvrbZh1YWkuOM+p/S87wnNfjllB70BRj4v5rsPQgHEjkaPAyjdBALjL/cAMGmVkFHVqMgEn362AFWUE2J0aQQ0fSCrzdQbYJic6sgr1cVuRIutaPU4v5eYTKnBwFcJ4MnD/eVmGvExIKeB42vBZTUcwobKSashDTtunq6BF8KleE22tA0djf/njd+7E+74qdCZJuR8dE65A+2GXzvXTgFh6v5n+5EW3vnRPcM8C9sBnColQYmA3BR41WQLD2IjiG7dZcO+CVmMrSbcCyC8ucwEYe4h6AMlmaJL3hEVE2AqUy2F211UmWjVXjeNFqKtiDVq5Tg/4DZebzXtAsDnUi4Eay6DBVscyTzbURKD6dJ/fzeeZJQp3+1PNfCvbH5kbqAEDNU1lr5BZgHNOUeiw9CIg+RgNuk4Xns8mYzxaDFaNyRrGPxnwyrnnJDndNuuiyesBMsse6QPd/K1XyQzWVhZyw60d1o6rHnFPTdXTV2Mq+C+kZMyw9yIp7s2vMTuD1jSjFcCzZ60ciKzooZ1Wtb8Ilz/nQhXu9qJCaC4XJIHTLjYLepHuCYzUcl/xWp8YTOSUOnpylBo1in776CZwzQFcfkyfcYv6VnPGRDutjmmpnmzlA8Q+sVUhS1CgGhh/2HKUjTv6c6xSInaumIMjllo11uD2eEu3xJEVEU3T6wUbbmIidCp1Y9miwvBMMCOjMMHEbvtB5cbxWL+89dmS+Dh/kpO0cHM/m/z3RfpFIBq7vVVnLwhgLumACc300SRBvAJQIssFW6KbzP7UVcg0CVMlrt+KwhTmU0h2DBHcN6XuRbGXEcrmr7kI8UEcO8j8QBiKaJ5PEA0Q0BvnvIFsh3fdOBcz5j0bEQ3bQDJtS5NQesg12qwRIDwgBBBmhh2A3DAO0q892/80O8VgV8//gGglf8anatilQ5PvEtTGyFYLMP/AHya7lVBWEvAD4WpcrLKGf2fO7NUrbdVt4B50ji3Q2FaUcsjPeOncCClupkx3wkE8kxFgfAV0L6l39MZv+cgbzCG/aQJHPAoq8BV3AwRQAKPIwX8wtG17GggNeDMnBC9uqHUtJqEXFDo4AxIRs9bM3FjLHxNcjWbQQ+YA/kOsWXFi0yyFs34yBIsgfAxpIg5XPray1XhYGhuxa5byYEB7B0iSwOsiI3kyZRCgyIkjk9a2MmAHhwfh58QS7bHJZyaFZBWgg0wIIB4ugaKyLJLBhBoJisJV9S+dKH9pUjNhpM2q+x9qhGGTGoSOFOvI32EhqdgKXUpSl2Hm9CI4Tttfc6B/MODWYjmzBMn6T0UTaJExBh4DsFbXN07VmUc/mqXlAfxkeLsWIapRsgJNjuk6odeB4H14uaXAbKRgLMWXXtShzSR0/7Bh04JRSy1mx8MAVxr2p1MQilvlTOX+aztgJH/5zI4hCyXXNR4JdiaLg0ogNuuxsphqmSQiHMkFojNd4JH3BgVkhb/MZZ3/kN7wsZgQ2sIRGPGZDEeoSuIQyAvO5feWmemYTzk7QYoYSUGo7kMgGyAW4wuStNEq60QcBdwZAwiWx3gwJodTI8W2lTHwotEBvGvmpopjEFjvvMGqppU+oW+/KnPGijQbzqTb5dP6kdI78QI3VWXYUdNrBayRQJc8Lys2KCOmLP4i8/jQBeh3lgj530RTkLkpIn7Ns46IohAkkywBEaNlR75YYnolixn5QFP6Ba0hBgSCil/Jg+ZEP6LuUhzj49xrxNjN2MVLw5auzmdnsbdkA9PpuRKm2Q/LrPgr9tfdAjTkAthtZlcY4tbhrSMYMPVi6l+/8no8qyTFnhGgS+CgPgNcgWP3YRnXg69T5ay0qNWndvu7zd+h5ny7DRdSmksSHyyloh6itYeBF6fPXnsogNtTzQrJ3OTVlAirI1mHDiB65S+CTFSg2+t+BRNNhPfneATuX2l6cTCGkHzxKPMdWeuD3rp4TXkGWPNfp4eUnbQkUNMZ9ZIsdgIHr1ZPu5xY2WkdBUAnPVVNVvKWS3lCLeq0Tx2/rWo45jpSBOVOGugBZojdY/dzKPoqTtnLYLq1v11q9EUOyhgoKJl3WdycUt+A72YXbjssLbQ/sVMz/k+ytw1eOutHvXS4IghCWLSWOlLNFBYm94S1MIJZT2Lb8ISANNtdgTfikq/Re0u1cUuhzng8V8QbcH0Uha3a9c2lsLHZYYkzySqDM9BTyNlFSy7iVnNhgTA8YWIYNwQupWGiKVZBu553cdksVO1bF4/xLTtHqLrWBu1DKW0gYkDgAWjcldbjpXiYqUygakbM/tJP11OQ9aCfjZe0p1ULF8Q9Aob5Cm2/4smem7seiZBeTpqBGzICnt9dI3LwbGCno2y80X/Z39fzLgyRyANLebQtWQnpyxOLZwK4h/D6B7eiJJ9u+9ggOFXXq1gZBp43tLsgPEKksi/pc2iWL7hi7EDVhDHSRzGL8y3a5g/F/L+RL7Oib8pFq2LuC3FgJRo2/TQ/IBMB4J+JBCGokwAH6We9E2Oz3j0pBgDrLCIkl2gOAG8OHekBxOIscnuci6DKPpWSnqqiotXuWrK/D/noX4UFzNHopui21MVdH90XBPo4lFeVRfmcR26cHyOIMdUaAv/MyuKTWjT33XjSFPn11PxWyoB9/B5VR277e5WYNY3k8zlApEN35l4+TuRW/rtq1izqtI6fKgb+zpvggn4vhME1EGYF1sNyl3HHF78eSXKtwJsTIrfK1nJ4wAn6L+GB8Cu/ackF/PyheCPZRVpQDhLuGulTCqVwvhjM1yPt7od+XH0J6wOXauXPtO4iyH05zETMmpet9MVy1uPpk55rs0W60Xtrp6wUJdoSsllXw5wlbcmO181NlWg/GvC9OlxSh3jaQ6mBgMAK3KHCiyjvtAgjUS5Nl7Rt3KWZU7Pp0T/+sx8yP6MQLQ+u17KMjpPdL0FYZMEGQeesjBP08gDn7u1BFS4wZNYIqc7tvWIrpznjsOjfVs55JLFfVPk+wY9kGcALyuLODn9mQxqkhLDYy+55lTeKpriYnpuRxFff6Dbt+e0myoBDIhwIj/9YvvhFNrRM1LvQdVyTtxX11Fnp8OI4R55HE+O0DrBvtRyGq99bOHn6KuENiH4LE3nVKbCsVjRa8FfogW0MgQb6V72CF+oADheUPaVuIojRMsijwvThIwq28UvX2puRjOWXnN+QuOeoxSrsNgFVyFh3QNpDhAj/UgW8OeHu81JJ85MXOfov5JwTqt2+PsL9bSDpFt/dpF4/1oF2rbu7heYcUGCKmy56d2nsuSgAIYGsP0x+JUv8h9l6V5MT8RvvGA3p01iI8SICDDRhh5vN/Lz+17Bd2JeSn1nqoGhAgAXXo/SXE0FAcoe0BIDx4/R8rJ1apPC/VOy6leJzygtovaN2qZNsqt6x+m+EwnBpDDnIbcPjrQ82s3TFJ0WNRDbBLKYxaNh7jqTE6PvrrtbDtZMLPb1CUgp3xIX8UNVUcpiizlmmxFOQGeEQEOMTtbB8/b2uhImfvclk5r1TqtFclovvgWAlkN8zbHSQhHBdyo4faH7eEo2O28AjeZbBYA5oo3mCYkti1KaeKfdTnKohVm+6sAA8ABDw2FJGmkBkrYy7Zw+ksFxoq5hNK8HXH51IeJcpjASwN074gjSFF2O1dS+0UJ22BtH2XQdYlmiJrckIZ3V6zN1+FwDGbztLVdLpnt8BcMD/mNxom5OxEVNR4NdzJjwtmAb12Mw5Q0RDhpKhnyQxtGjpqn/D7TAEEsHC0Cz/CPDwRwzkSdBU2yB3BVLlib2Qx5PeSHKbBxRT3frnrMJG3pV7xmRZ+1r5xTUl+dMCuNYbQ7pI9G7FTSc1cRvpNzIB46lw1d+1rnmeNpBpFmDTRoWdOWoHv9F6Tp/WwVj3YUgN9vxRTOjiWsjB6gw7vvOtMyZwu+Gi7CKidRMlGpVXkFTUcBh10OiZ2B8tm6lgMB4kQWA7W1s705pASsVGoB17M2O8brUlqzhYwZy0xArlGD+5ZoLsMwfrrRb2cAzFy2ZKKDsYy/0nkBG98k1efPfqdmthDCAHkj8HLbXyOybNOnOdPiD5I7qTtspmUcAhQbOQQQkimtb/RQDxe1W4iK0eKXcv8gVo2sBmlgroEMGNE59/3/hPp8vypkq0B6PhIQQQrk9i2ldL8ii2WHaCDtbXkPV8poYbtZbHziQt2KomJGZpP0SkghKCrDtVATpban+1yyxuPeS4KB1793ph+wBa8W4qlD1LSCLLYX/lfz6K6uctk3U5J9NlWKymk9IQfRNKDIYr+WybIRSvLRbwHvCxF6fAiSbeVI2TNBPsAEAgCWCZwbLrzRqvi7VCHgi3uZ0flsu919122z7RldPZeyM9ClhQSxKT6k2t2rd1gQV2FNlcMqEr6d4oGjgP286cbXtVS48I3PM+pbAkuYFpb2Uc1m11CYy9Y4FQ3anJRsVPVFCMSE4iHNlFmRwfmmNiFZ0y01X6reEiurbe9YgeLaCt9+J69dhwZyR29/QzALPS7ppq2DOtDAVfQrB9zr5lKaufab+QRqRcMrVOlBCSwrx8iW6v46oMe0vrHdtKD5xfbLlsFUBsmkPVbKqfeju85xYOtZkbEEwX/rn1FS5+Q9fznvoC48/I9h6tPV437ejyCcCrLh3Znwpl65GQmcP3BJPZKlmSWmHqb5/8t4BFc+vmfyzvRsk71nx2xM16SG/jAOOnLRru5IhYQ5fJo4Lh5NIi2wya44rctmeBMkAZP7ltbYxpRZ2+29mgAx0oojxf2fZLA3Bc4nuW3bdZ315Qj+qHS65/0LzLz6VfZyObiT0YsII8GaJSOjPD+7iDtvUrJnPGe8lxfdXY51scq78k3GYhpsm67UYx5XwTnSMFqlG0RyGzvEZKe3bpWN6DTfSw1uuDbwfXWZiCmTnaocy1yXfPTe1h4VOvYEjHkSJTtDiAGxuYogthm4TyCk5Motd1OCvO6GLUL1QlD5/m0TfiNN7xDcSeiVyhGcF4QYPl0sP70ZK/TJyjk5/yznGowpy38VOZT3ju8W9L55/6v2dFDRYCBmsi4M8CtsNthnyxq9OE8NqCX6UYpinKgxBfGsNfjdhcOVC7YwuapF6jdxwfBQEkERyfJbUmBdn4bZXXEgxMyVxU7FeWEYkha9kxbg2AMvCF8eg4kuF4EafRuJd8jfkMP0dp4opbViYvijrntESWOzW9tA2ihqtsayWOxmCWWil01dU0TRqmtAqs7N8geoJEmiPUA7kU8iFY+trJz/kT/s2qj3YheLQFpAF0mzuhbgSgyKFamOFY6zlfk4tNyuv6YlwUfUjcEbOC3D9xSJbAIzlojDxG4N4YJV/l1qeCxKkcO+0a6bNqlXiqL4EAqyBZexkrrdfin/wM=\", BinaryEncoding.Base64), Compression.Deflate))),\n    Source = if ProjectRoot = \"\" then Snapshot else Table.SelectColumns(Table.PromoteHeaders(Csv.Document(File.Contents(ProjectRoot & \"/data/processed/paid_sample.csv\"), [Delimiter=\",\", Encoding=65001, QuoteStyle=QuoteStyle.Csv]), [PromoteAllScalars=true]), {\"player_name\", \"from_club_name\", \"to_club_name\", \"transfer_date\", \"transfer_fee\", \"mv_at_transfer\", \"fee_to_mv\", \"position\", \"age_at_transfer\"}),\n    BlanksToNull = Table.ReplaceValue(Source, \"\", null, Replacer.ReplaceValue, Table.ColumnNames(Source)),\n    Typed = Table.TransformColumnTypes(BlanksToNull, {{\"player_name\", type text}, {\"from_club_name\", type text}, {\"to_club_name\", type text}, {\"transfer_date\", type date}, {\"transfer_fee\", type number}, {\"mv_at_transfer\", type number}, {\"fee_to_mv\", type number}, {\"position\", type text}, {\"age_at_transfer\", Int64.Type}}, \"en-GB\")\nin\n    Typed"
            }
          }
        ],
        "measures": [
          {
            "name": "Sample fees EUR",
            "expression": "SUM(HistoricalSample[transfer_fee])",
            "formatString": "€#,0"
          },
          {
            "name": "Sample median fee EUR",
            "expression": "MEDIAN(HistoricalSample[transfer_fee])",
            "formatString": "€#,0"
          },
          {
            "name": "Sample records",
            "expression": "COUNTROWS(HistoricalSample)",
            "formatString": "#,0"
          }
        ]
      },
      {
        "name": "ValuationSample",
        "columns": [
          {
            "name": "player_name",
            "dataType": "string",
            "sourceColumn": "player_name",
            "summarizeBy": "none"
          },
          {
            "name": "position",
            "dataType": "string",
            "sourceColumn": "position",
            "summarizeBy": "none"
          },
          {
            "name": "sub_position",
            "dataType": "string",
            "sourceColumn": "sub_position",
            "summarizeBy": "none"
          },
          {
            "name": "age",
            "dataType": "int64",
            "sourceColumn": "age",
            "summarizeBy": "none"
          },
          {
            "name": "current_club_name",
            "dataType": "string",
            "sourceColumn": "current_club_name",
            "summarizeBy": "none"
          },
          {
            "name": "league",
            "dataType": "string",
            "sourceColumn": "league",
            "summarizeBy": "none"
          },
          {
            "name": "tm_value",
            "dataType": "double",
            "sourceColumn": "tm_value",
            "summarizeBy": "none"
          },
          {
            "name": "fair_value",
            "dataType": "double",
            "sourceColumn": "fair_value",
            "summarizeBy": "none"
          },
          {
            "name": "tm_to_fair",
            "dataType": "double",
            "sourceColumn": "tm_to_fair",
            "summarizeBy": "none"
          },
          {
            "name": "minutes",
            "dataType": "int64",
            "sourceColumn": "minutes",
            "summarizeBy": "none"
          },
          {
            "name": "goals",
            "dataType": "int64",
            "sourceColumn": "goals",
            "summarizeBy": "none"
          },
          {
            "name": "assists",
            "dataType": "int64",
            "sourceColumn": "assists",
            "summarizeBy": "none"
          }
        ],
        "partitions": [
          {
            "name": "ValuationSample",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": "let\n    Snapshot = Table.FromRecords(Json.Document(Binary.Decompress(Binary.FromText(\"vX1Jbx1XmuVfCXjRq8rAnYfekdRgS6QsiLINZ6NhBB/DZJjxIlhvkE0Vel2oRf+HSuSiITQSjeoCCo1G75g/rM/3KGf6xR0Y8RySE0jZIimbh99wzjfd//JPX9y21V29+qGrlvUX/7n44qxZXFd1W3zdNuv6i38ovrjt182m6Tv64NFmUy1u6HfX24sffvuRN83V9ab4rumu6hV9vLra/WlC0z8stqtV3W1+WLT4ql//Rcf0r+2Ks22HfyN9VltXV9vdh045/fNm+cO7qn34Ha7Zw1/0gR+rZvWbDznPlGJalp4rxe3HL930P9Dn0Wew0nqpjHZKM++E9Lv/qGXTbTf1mj5BWufot676ql0//Jm772G9btabh89QX/y3fygCsJ6uWnzHxZdV1Vbd5Xi0ToDGqv7Ds371c7W6/C1eJonXWdUtruv1pl4VJ83mbh+x58cBZIKlIdPSe6e9LjW30gsRYsZL4Z3lkqvdr1oNIfOO70Em/QAyH0XsrFr3XfF8Vdfdz30/AbLpBvZ1e7e8bf5xWxdn1WpdN21b74P27E0AmtZJzJT2xnMGYxJGCOFidiatsV4wfAYX0jkzBI0xu29nQ9BMFLSXd21TwVUuqtvb+w9zmJlLovamrloAdrlqLvfRenoeeqVLm5gSgmnHfCm9ZdbGTcxoazmzUlrGXGBiRuybmJKjTOy0wh9SF99Xy6r93fb18BOKIvXspDiuVou67bvqUahy3ghLQVyyphRWKh5FCgHOcW+MZz6MXvoB3b/hJIY4cR0F6ruKvqvij9X9/4KVPF3Wq7shXmfN5Y9N3V4mrYuM5Tef86t9sSRqr6tVsy7Oq6bb/OF5vVribx71yoyZSeOVt5qVQJAx5WNeicDPtXZAz3JhnQ2iP9vHbwhfHL2n3fu+eIYUdv+n7rJ+Pxdy6Xh2cl2367oqnp08Gvt9DjDHFXeqVEIpyXgMMLilg28Kp62BbboBYEpwth/GhojFw9iL/pqiWNW9r5YXzVyA8SRg5yfFs1XdXGxXV4/xiwy9kJpzxTgszMA7TSLuMwbMlFcONhYYmGJqHy82dFAWBezbBtyo2a6LFyBJ/Wp8MDutf4zlyjS5mBT1VQYsAADjMqU1UoJZxGIZA90yDlTMg4fYYTRT+Lr9aKaGYMW52FG36bsggE0nFI+AdFxvEL+Oq7YHuXhIxlm0cmCB1VrvWQkKaz2PWxaDzSkmQCu4dt4HpuUHzDVAK25aT+oFKGvxplkEJP9QR7RJ4I5Avzp81YjIxUUaL+EM6ILmJbirYzIaurwU2hjlGRiaZiIMXVLv4aXHwfWsvqxXzaIvvq3ad/XqcjbQ5iFimXgvHIOZSVAIy6SI5kd8gCEbSA/GZbUWQ8y42MdsSFpBWVIOSUTsvF7W3V3/KT1zqjbKEAoQBIRr60rrtAE1jeZHAd7qHWgFR5wTAXG1AyML5GSCUbRt02+KI9CJFVTSXCamkrC96jcboHxdLQtoBOD3KHA2rY+EFeCwipUAVwoXBQ4RTHBjQMMEafUhcPgds8/4R+F2vL2p7npwypvq9xtZmn9NiWI8Y2AKrMooUSowK+4iKRIQOoG8oI3WRkgbMn6wuEcIBY8zfvyMIb/PFi/rrms+QxB7sX2H3wODGYL21dsANJnDTCIyWQQx/Cp0NPILxCloAKW1F+bBb/dMy+WDWFxLvrx+R/Ww4uW7alVt1jeg4M0EI0vwsLSNHaKOcnwM1mMdvBHoGMFi5JWX4CFMg9NrZBHthzULMVSXQTBLpMwXkOF1cVr/XFON7FM65rc/Hhfnm+1mc1WtBiEsZPpZsJiWTCL0Awguo54JegEdQGJcSG5Z6Jl6wMdGUv0n9x/Wzer+Q/Gk304p8aTQSquig0wsx8rk3z8UsDGLHPq3/+ND0xJiUA4bV+A5w4/5/i9d8cftRQNqcTlJSj6pf6y7dfOu/nQcNpckuQEOSpVcWdiajrILEH7PjVVSGebskI5J/6AC/oaaGYAmo6A9b7ZURESaBGZ9N0NpP80rjjbt/YcN0eXLeiyFzfglx3dsjbalNx6CJxr9Jf3lnfQcUp2JQIIPa4lD0FwUtNf15aovXtWbT8peJxR2TA4lhHiQqxLkyrGHgn3AvyCLNEcAA08zPixUGL/PKwKmH6cVzxBGyCFP7//9dlol7AFG6qHEvFEmIZtUe/2VjMVRo1BvRcmk5p5HWSusylv6sNVKORFkSLCOfBgD0PHyDtj3dUAnDo9eaRObm1dwZzz1jqjjEVdJ4BXWw1k91JDySgRhzJh9XjH0yHjsP9oiSbZN3RVvF9f9tlref+hmjP/zVMhsHjhptCsZR3DXKZWE5KA8iD/szQZdJKf3Y5kYlQBeIP7f/6krjlpw2dBL521WHpIBsm5KhWjv4KZWUK0s6qYK+cEKiAUBZ/bD0o9UckBkx0mAZ30L5+l2Jb+rbaDKD8EtozHPizOEtEX/qHfmnNNqB9rvSgf9CAuK5kvFuEXgMxpy1JkgEzD1CFjxEv+bu4q6uxVU30W9eujrz+OZabZxii9Z3fb9KG6WqfxwhDQoa18qqngZE+VmTjEaJQA904wH5VioqH3YhuXFOM04rzriGW/xk28/SzB7Vf+8qNabti6+6ZpNffn7YNPaIkESO9PSxhtKzkgtYZVsJzGHQgAidb/mP0yg8fx51q+uqIbdg2mt52MdGV67q55827Rt9ShimZIsB08TkOUlciNXIioCrFVUIEN2NY5/rCfudUnEvggIOUecqr2p1svtuvjy/v/81G7nGVlJs7Tz85PiVXXbPxh1tviTI7bag6oqyHJL7e+ogYGLAFEaZgFPs+G0ihkqzXH8/6xv1hDmxUnVLOrLQAQc7pqzdHmzCVNbKYWxJSiE5SzOa6ECyHeZpZRhh16pmN23saC1lFDnV9ddvS6Obtqm3y6uP63SHJ0vMx1erplyzCvkS2Wkik6Q7cQ4CBs3nGkXzKpAA+QDf6qS0W3rtjjtF9WmbueM/fOUZEW6ksEVgBDSlAxofAxQQUkW6srDewW80nsZhH3YXzbsJ/pKF+CUT9+/r9r3/TbEbMZq7NwNX5ALiCoEfuRCL12UYezGDbiTgittJA8KjMYNAn/QwYy3x1/093/ui11B49NS2AkBLMcqpGWaSVk6SHRj41OdoPnIC5KQUmEpVupHunBxVnHU1s0vxfNqtbj/yyRtnuuQpKfIdmOwBVPFaQ0ae7Nd1wNlHpawM8VYjkwHgWQRyrxN1BehpZiAZqdJC6FMoJM8z9cXExVs4PYLHOWsWkBitg01Y+dCLx3MJnH/nCyXYFvcIScKxLIEiaV6v4dWggvD4ELcVD4FxBUTeeRss1DpRDmtYJZLlgKmBesBHI65GHnlJcgp84BTe2W1DoBiajAONTSweNx/CRm+LI4u67t6OSHqTycVx/1qi/+aqnjSrzbLjyz5wJ4SlKTj0qnSaKdlQotrDf6gBU2QOe+GrUseTKcPe0pxyzrCd9z2xfmGJp8n+eKh3HVaIy7DLQR3XjnqWirAFm3EKcY5s9RXYtxxFwxGOZUvksUJ2VdX/ap4e91UV584Sx7Tb/3Yry5HVf0zUHFvlRG+pKaHiQd87cBvocA9M066gOdLPmgoiSFWCaL/IL+fNxcX6z98d91sJs0T5DV4pnQxfWYl450c3JUJkFh4oDSpYR/oAscN2ArtQwSGNuiZBDQj7p1PevwhzU1x/r6/6Nfv22pSEjgUvUn5MqsvIRrBHixNphsZ52eeSSEVzBKZUXk9rGMraQfIBXaXMLzmBqLpRbVd1VfN+2o2mpEuZBxtrlvIgEVx3LQX1UBsRhJoZpQFqkmCsvoSBoXQFo1tAth6pFACzjoTNAD0YExqnG46g8Yk2Vevuqq7rCdVzHKwiSRsNG5UfAlPHVllzNEOxiS4ly8lE/GZKaWVdMwiVkKkg/0GUc7kqxlx2fSsbqEGXi3rxbRGXQ6wtHtOZh4ZxJijOTut4aFQR3GxqQzjcFLLOESDcYGEEmwfsyGljWN2uoUOeAL1NKHJlNDmj+imseuDmRQAOU77DKqEY1qtoqZllOGMhtW5EsaGpuUGDeBgZF3EA9lRt7nuu7viOXhAOO85YyFjcr0/wziYgwoSFgFM0LJDFC+AJSi+IUVwGdR9xEcO8vfAbwd4xec8X/Tr621VvGyWy2bG1pJMz0pNMjKZxQwMTCgQWmlFfIBFSKBqpNotkgQ7N9Lp/Zgf5Mo4Zgj6cMR1cd5v2znmyjI5cr3uF031Hn9AXZzfIoA176riTb8c6M3Y5GcGOdqqoeVebSAJRLxkJpQWFPid9NDugbkZvq83x9X+vwIl+6UAyW0uZov8afRO6nZTUbP82+bqcX7Bc4AZLxQ34K0I+vHCP9gFVLy21AQWQgbxTAwqQENbi4f9l9f3H26vaaPw7fV2VS3nAi0d1iZNF7sMZMqDU9kSEspqEZ2covYl1bKhSIXxgYl5fcjg+k5tvqjX24CLzSs2p2umTOGfWWEV9FApwC6siqIlpGS0b2KhEqyWgTgXAwIbtOMSg/6r6rKt73aVrL79/XPY6RLQIfNSOZKBj1GvDU5Ja6hRzIxWVFHjgnHYWFAFEma4Oz6uSf7l9qovnt4Aipt5Vsc//SAG0whhXujSg8/7ePnHarMTSCAaEAQ6cEhtBzN54zzy6Xpz/+Gi6orT+rbaTlgfP2RI6nxTIeC/qbuuasIYFrGwXJ5ECLNMIU+CxUoTrQNJiSgGOqY8MqIONi8R2h65TpBZhD6ti2f3H2bbKMmAtqX1KDq3URyNMDORCfuKBlaMKiF8oHSiJQzQfTij9sopKv+E4/4sv06Yqv10d3VL44RtPctAWWZs/XBWlinQMsWtRJwq8WE68hCDTknurTTWesWCmqP4WNVI1xzjtna6hY4pnlTFyXbi5OyBO/f9si+4fzCOfKs8E8+kt2BZBIlVzEc5LO2TaGe9YZo760KCMWiVj1NMTze0cX+0vK0ut7PppVx5sa4v12M1ZqZIxiCpEchcSdnQJziGc7AtoQ3QtSpsAOhB7SLoMsVds+qQL7/eVvDC1QzrhJku05QOQC7yU/0G6bKkORYW5xZSOs8NIhkCFn4JIr9x+944suX7MFPwqn73OYqJc4+wMwG6Bb+ilXEEs+ipAkmVMcudkU5KESZMnY/+cZ30urqti+fb+u4zbN7vZhXx+/jCk2f7cE0bXWEwH6dojRw25OJl693wHTKpMohjLryzItl+DAuObCVI/7brgVezrFb3f57P0tKlxcnVshzz5+DylhYl6N6WjJIMMFkocuglT+MbKugwSSazuCXaJC/w65oGWbrP0/19CvZP87EjwlmOWnC6dqFNSROd0sSpBRKppd0Sz5ECAvIPmrtf8Blyi7hS2qnxs2pTdf27ZjEHLctMxo4/TSNEBiuBvxgYLBfem3gvidOkj+FGeK1dsBhH3HY/TY4LYkd3d/32ojjut9XltAXMjE9mjm2dfg3ITsfdcMt5Iyfb4qWl+yEmmiuVJ8bPoCsd9FTQ7xUfJ5D/Bliw4BvF61XfNbQIs61vPu1A7Pg11SxOzHGqVyhnWKJeAZyMFhow4hOYGfIvMSwijruB8axerUBZ3/b43mapiqXJ6qSRqBxYdH7Sc1FaDUoh4402D4vTNNUIJaB1wCS0H8wqDqV3PDe+qWjf5uS6Xt3MOD6QDltT76xkliBITTuvJLKfck5FCxbOO20R4o3jxkobmNhwMCpYV43b2P2/zHtgJaO+N3QYdFMVx48XqHM5EUnRKYQt+hvpokNkSnlQVM9pzAy/Bv0jrvfdcdzMwEsEk674/q//1l7+9d9+fzs33WmbUsrP7Nez3xhcWDIcYmKHZ1SGGjHeGXpe96srUKuz5qbabqrL9xMi+iGBahqJT8tq2qK33sPlSF/HKTxDJLc00IPQboIFcWEeYwvxgtf5ot9sirPFWxp6qua6MinTVyYnbB6lRQ8oFa2rachnL62Obx4pWuQFZdXcS2eDsj2i1mCRcuh4cX51Vv3SLJvd2dfjugkJ/LyV+xknXj1UjrccnFRyriWLByvGaVtX0x4lpcbAzAbXGoKJ18SqbtuvCLHvmtXms5whmGuczoNLSSZESTd6tHcRmUjBH8g6SoaQRj5QiR9X7JMVwpRKvP+wuv+wvMOP/iaoEc7YUZtKHdJBHhHMGhpAsdSKlfFahNXQ03SpmfrhcN+hhblBIAs0ddwtz+uuuwOPv9u2kwqqn+9WbsYzHfKd9qw0hv5ORUcDFLFUB1tUUptIF3J4C3BYKUwtH13UiGNt+9CFngu5zODOjAHNETvX8D/vhZUJ1CztBjInvIDODjSjFvsVnGE4ezQHPL26It9p5uKsudQ5vjSRvnLnHaNNeV3Spow3cVEEmYlkIT3SpxScB7c61eASbLDpllDa1TV85rKZJokOK0pP7Eamy/ieChIMQc1zEDAbb3pLTZV+uCVTzvtwkB/ZI2tmccCOVzsRiVCzgVaZVJQ+dK7ud3QlbRJBu1viVdSzpbvCUQSZpRkLTyPrNG8nw9FqMxjlHCWTTq4Jvf72ujiutkvafplYc80TkLTAfHNcnNbN7fvmUV/NBDjjKIsinwoB8/JxxsYF4qDGL1CgPLgRSwtf+4xt3DmfZyvQgma96IuTvlvUzf3/uP/zDLe20jRknoOUgAz5k/MSaVSnFLlkcFHIbk4VMs4DyILnDQaIxYsXR90a9lW87Krtjz9+SqSeNhQQF/gq+iHd/Lh9fKUrPZbozY6L8dICFSnit5u51sTWaO9XGBeMJSJZ7M+njOMer5rFTfFd327qZRXebZ5XR03uHKXfG/EGXE0L6t3SpGY0gdIMFLPa0YaSZCaQBEw8Ut+Imxgdh60318Xb6q4Nr87Pv5t6jlxQb+7/9e+Z4JRSQ3Fe3pZH5aNump5VhMIEr/Cy5Fbp1KUVsDvGmbKKqd2Zt0Ap2ENGfF7R7avX4QbE4UkgTULGD6mkh+7AKriEFkcSsLuTMzGoaNXecY/8aenhlsg01D5hCxa64o23N1AHq03xqnpXraZcJzjkMOW0PS6ThotZhH1XauoV8WiDhBmhqCoklDXSKRMkADZ4RmOo2OM1/9fVRdvTHG9HX/bJ5cBBNzCSQ3ce/Ir2G+CRLjWswpw0tDNI7UqwjsAjpVT7XGPcHbdvm5tNvyqe393/x009U3MpfZhgQh8uvWuD+A9OjxxAH1acxeeGEf4h1iUAEyxyLVANsqYYqoJEEqia9fUWQqqb8exRusbNy2fn3xZnVdO9Lx5mKg8ks5prAzDoARLSnvFu3O5AIDiJo8M0PBgdA4/Zj2OjiMZX62V1/z/b4mXfhZPW82fNb87xw1mvt307iGPTUiSdm1FwSAsmS+WhaIqE5FR8d7EfWYKFw5yPFIXi02Nvm2W/ub4rvqurSctcD2F/mnkd8hZceqLTA07wf10qvzvVmRi8YJoLprUwdAQ1uBprBwcKhn2BePQnXtHe/2/qXNdtuAIx/zDUVx2VbM+atuoeNbN0k9wrJ6DcIZikcCbRFdAC5EN76+G5YLUBnR2+ejBELN6t+/gc3Em1jAx0zl8RmuOCp1fGcOs57aRq5XSUtyoBPW7AWCFGYWiRDQh1gH292F4eWqk9tIky6e2pjCaHIKdp/ZJqsULFXjajgU4H+iAM/NFrFbQ3hyd8Rl5aOe3xXb3vgRtI2XrRT7tIvGulTL1HMH6uIBPGlCAwPMIY1GMi9NOCIBXMgO3Hxfu9GobZn8AY4hU3so+nos6ruoUor28mnu9MJ4DMJMbJyBiWhYt5bngpoLZpeCWFF0iFdVYZF2mg+8HCyLiiz+t6U62K8+1f/3vz13+eK4alzWtKzM9FMeYUnTklFmuMjt9VFJpmWzS9l0rlxyCKDQ53jptOfFJ3zfvim+6yejcDzc+oo0kXj9KTnF7uDszzEppHOenihQoJCeAAJmAVNvBFOTynIoKeZuJOVEvyu0faautmiv5O9IDTdjVtkCXDJqR/0EXGSvFxLiwgE1TS9k5BFXHvguuAoBoDjj8u1D80S84u6u1yhkpFOl79pl0+dgg9zfHp8pPnhIm1dIIyhpf1zhi6GCvpEY1wJMOaR/BK9DAbfBttcXTZ307SkYctB55UV21TrRqwvXbRPK6L0s0k6RjCvS25t4xzH3VIRpe34LZ05w6xLmyW++GtzgFk6XfzugZsAuF38VnE95P6ofDaF0dt9e7+w/pxHpbxTYQm5kwp6YYbj5d4OIOtMQ4fhESX4VC6H2zvjnvh4Gh1WRXP7//fxGt3ed6abmLO80Cjl0Y5EIrdo1Mm3nzzhjMJlm9IpJtgxEwMzCzY3kpQ/d321vN+Od9OTXo55Lue3s2EorilFZHv6ADV6iPty2+KZICjiVdNr6dK2uWNH4WiO+tQUopu33kXRLUhHRt6aBy5c3BvOhGIMLPezHNPNy0oj/u2v+qq4lnfby6qFqkTH6Vyv380vMkM4SC6pUhhUmknvpNKQslaTf8DxMFdFSmHz0CPQ++rtlkih766bKpwBW7Od5UmLCRl+nDEq7izJd1M4SLxrhIUEtc0eKAZKGtQg2WPdC4Trd5ldVk8afAz/6RNkelUIz2qDrRA+ZUoiXmRXIo6JRKEIac0jHkXzhIYm99GTfZ5+7Yq/li19c/rabM/SQWe6yTNosAlWCqkUSmMoycdEpJSSdpWBVgcJC9IlsM71+OabqTBi91c9lzBP1OuoFWbfrvq6mW/3Vw/al855s+c17tZFbpwzeNtcUkPGkgpgawO2+J0kHIPsHHvGpxsV9QEe9F3nyNfTposzoyVCXAwaSzdSlf6Y3coiPPWaEePRBvpTPgiuzCDqti4SuLrpsb39Yeny6atd++NXPxUr4J3QD/FdNkhxf7M6AroFU2vlHBDrxLvAnGDaObBaWnf14ZHYrnPP3CTXYZ7sd1ctff/+vtzQFpuTjw/lvZP4XYvsJRCW3CHuL3x3ZVOTu+YacvCawScD+7QjKsq0mMa8zbfMu90HT7AmAludNJCW0E3fLzRcdGpQdwAnNrthDEVaE47eIB2nHR6ef/hXdMVT6qubz7DLYejF8XR9heKD486ZiZ5CnpoXfsS0oh7HluaoORpqDlihbC/rt/vlRdNfisuMWLc3BDVeLlab/p3kYrsvOtf35wXp/ViUT9qWZneiED0RxAr6UDux42kIAsIRRUghCrnPvLVPaTY4Aj9kOwn3+ja1B1NlHeXq+3tbOE/45vP666vipMRA565oC8YtSOpi8tT+ogb0DYGxi8FPUsevnNg8ifo423xry5W1XWzpMmLq2o1LZjlIctcvJh+IDBta9zTO127sxYOAjt+vIdbpZil8Ra66hwiZ7PIpbZMaqhjYAexvP2p2czW7c0+q3G+KYvX1Xa4aThpW4J7beBhdJbAiXhjiTNnFS3w0I0VHhxTD0jtOC1OK6wA7ekVSFLxlN6J2Kxn3IxOAzfeSdMzeHTZwhtT+t0DQFGpyYxWTNNRRQaL48FaNGDLv0USL9G+bX76qeqa4k3d/ESVrNlSZnqgbOr+XIZmcJrFlvTG4I6iRfOmVppOriullVAy0j4ZTK+Mu6n7fU03Vr6vVsu+vdvefHqiMe3IVrpcRiP8WvCStkZ0vFMOW2QOkBnDkUXDTmawOj3K0k7rn5vdzf6r7We5WPA7qo2/HtuKwacZdKigB/boilT8KDE9guNhmowjccZeKcmXauPZ9Lxa3v/f4qRfT8sGB78SffKErjq2/Wox/pmlGGCKjlO6kp5uFCJ+zpMbxQTN79G9QB8c76ctsT3AhuPFcYP7OIx9BLo265H1jI9OfwEtkxM4xJEXJb0E6qSJtlOQFHbHPC3jTurw4Tg1sLSRzxKuNtfbVUHcfy43TVfUvrlsunpdj+1zZuY/YWDaSGqlC2ZV7AwevUei4JFWQaDS6YhAc6rBva1xT2u86Ltqd5/yeLu6gRoKCpHzyqgD9pkyggqwSSM1JQSSVvF7u7QK7GgqW1ko9vBdLzmIaMPhlrihPa8uVrAUKm6BtMeeDZ3x5YgJc+yZrgCjQ52c3vMCpbCJeUZwYDqNRNPXlgWbmYiCg6rQOAF6sl1c98WX9aq7/xOo2izv3mf2MQ/ZluDpdQkIcfAvorgOBDaeBmivH/9HwxuMhS1ON9zMHDdC9aKv/nF7/5cO2qbbzXBMMbNDdufekJRaVeuLfru6Ko7adTUseUy6iE3Qcec0bI5r7+Iz2pLWOKkVaumYWWBzSCSDBbpxrYKHVhTJg+XFnDXvTHT7slrSxj4S6fm3j4U1n8ZM7Z4iLBk9usHjvU7mvXpYTrRcOxcc9w8Mblz19vtts+mL8+37bdi7Sxvaeb3ou0synOZmbEibcnsxTWkZvTVCA0IMijzumeBtynu5SxTGR/pQg5fjhntM8YD29Xa9rLq6eALjuv8w6VGXtFumS0MHnd1l6cTJhKDxxdI6GFr0GDYNJdAHYX+a9ueGSgBeOTjvOe460Nt62xUv+/52WSNtTtPsn+Ox7Yx+otgPVUSvkDipEo+6aLrGCL+VTEkTXJEVHx9RTj8gFJ+kbSDZ6RWcupm2PZHsqaeFwEEZIENtIcYduCmdi0WETwzVWkuPxSEPCOVkZOdc7Ze9hwkg7qNvd9NBb/vl/Z8m7BlOH92YNH6ckZtACvTMlZrREmH8KQRuzO5dLyekVeEYAlXJ95Aat816/FDsnvha3PQG55RhvRypYAJKyFGxR1GHIE4qnLVQmAhfxlkRqCU56NAFh7oSfQEqnb2uml8mXchIEP55N+XSgNEFT2OEKv1ufzDxfpfzmnnp6Zg/qdEhYMPrSUE/OO6EDywMuatufq4eYtCnbj2NP8eSDlvOW+853ZtyVGpMhS1HL4Qa8Fr4Y3j5gfN9aTlELK4sX183UHr9Zfgoyad4i3byRbgkqaB3CMFJVQmq77hnUSuzjiHEO0uPcPx6Ym+v5yQPsrJnzZqe8T1at20V7n3NK5Henj8vuPO++LL/EQZ6XTfLx+ws55oGaY82f2k/gMfnZ/ERGJig5pRxIjyGLew+aEMKG28DPJCK5/f/vgz1+Py1suMVZYu+K/4TcINLH7UXTd89am45D4VUREArHbFZyaNFRrB7GtwzoLLSKRaehNN55OJ07Hw3OE2LhlfzHerK8Ndn23bXFB7x0FIGLkU39HRJ51S9VfEhR7sb5qZlHU1LwEO4hjxs3Gmzt3ctLbL1NAY8H1xpB/178jy9G5pYLG9mIhpkIw2daUWWFm84SQp29BKTUXQmewiZG1yeHTcJ9Kq5oaR5TIH5UxKyWc4M4luEQVlTwq6c1IllE07dEaHgkIb74O1GyVl+ET91tGax6KkBPO3S7GHd8r+dszy7/w9Kmt1VW11eVI+/SZse03CeAziuicpSNItPTwklYYAeIhxyPLyNpAeactxO2PdVVzxp+iXFst/NZDOXa0aTsfR2jqOlEVJG9mH8IrpUzuiu/06iK2FFeE3EDMr8wZAZgtd//f8=\", BinaryEncoding.Base64), Compression.Deflate))),\n    Source = if ProjectRoot = \"\" then Snapshot else Table.SelectColumns(Table.PromoteHeaders(Csv.Document(File.Contents(ProjectRoot & \"/data/processed/valuation_sample.csv\"), [Delimiter=\",\", Encoding=65001, QuoteStyle=QuoteStyle.Csv]), [PromoteAllScalars=true]), {\"player_name\", \"position\", \"sub_position\", \"age\", \"current_club_name\", \"league\", \"tm_value\", \"fair_value\", \"tm_to_fair\", \"minutes\", \"goals\", \"assists\"}),\n    BlanksToNull = Table.ReplaceValue(Source, \"\", null, Replacer.ReplaceValue, Table.ColumnNames(Source)),\n    Typed = Table.TransformColumnTypes(BlanksToNull, {{\"player_name\", type text}, {\"position\", type text}, {\"sub_position\", type text}, {\"age\", Int64.Type}, {\"current_club_name\", type text}, {\"league\", type text}, {\"tm_value\", type number}, {\"fair_value\", type number}, {\"tm_to_fair\", type number}, {\"minutes\", Int64.Type}, {\"goals\", Int64.Type}, {\"assists\", Int64.Type}}, \"en-GB\")\nin\n    Typed"
            }
          }
        ],
        "measures": [
          {
            "name": "Valuation records",
            "expression": "COUNTROWS(ValuationSample)",
            "formatString": "#,0"
          },
          {
            "name": "Listed value EUR",
            "expression": "SUM(ValuationSample[tm_value])",
            "formatString": "€#,0"
          },
          {
            "name": "Model estimate EUR",
            "expression": "SUM(ValuationSample[fair_value])",
            "formatString": "€#,0"
          },
          {
            "name": "Model gap EUR",
            "expression": "[Model estimate EUR] - [Listed value EUR]",
            "formatString": "€#,0"
          }
        ]
      },
      {
        "name": "DestinationLeague",
        "columns": [
          {
            "name": "League",
            "dataType": "string",
            "sourceColumn": "League",
            "summarizeBy": "none"
          }
        ],
        "partitions": [
          {
            "name": "DestinationLeague",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": "let Source = #table(type table [League = type text], {{\"Bundesliga\"}, {\"La Liga\"}, {\"Ligue 1\"}, {\"Outside top five / unattached\"}, {\"Premier League\"}, {\"Serie A\"}}) in Source"
            }
          }
        ]
      },
      {
        "name": "AnnouncementDate",
        "columns": [
          {
            "name": "Date",
            "dataType": "dateTime",
            "sourceColumn": "Date",
            "summarizeBy": "none"
          }
        ],
        "partitions": [
          {
            "name": "AnnouncementDate",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": "let Source = #table(type table [Date = type date], {{#date(2026,02,13)}, {#date(2026,03,16)}, {#date(2026,04,17)}, {#date(2026,04,22)}, {#date(2026,04,23)}, {#date(2026,04,30)}, {#date(2026,05,05)}, {#date(2026,05,08)}, {#date(2026,05,15)}, {#date(2026,05,20)}, {#date(2026,05,22)}, {#date(2026,05,23)}, {#date(2026,05,26)}, {#date(2026,05,27)}, {#date(2026,05,28)}, {#date(2026,05,29)}, {#date(2026,06,01)}, {#date(2026,06,02)}, {#date(2026,06,03)}, {#date(2026,06,04)}, {#date(2026,06,05)}, {#date(2026,06,06)}, {#date(2026,06,08)}, {#date(2026,06,09)}, {#date(2026,06,10)}, {#date(2026,06,11)}, {#date(2026,06,12)}, {#date(2026,06,13)}, {#date(2026,06,15)}, {#date(2026,06,16)}, {#date(2026,06,17)}, {#date(2026,06,18)}, {#date(2026,06,19)}, {#date(2026,06,20)}, {#date(2026,06,21)}, {#date(2026,06,22)}, {#date(2026,06,23)}, {#date(2026,06,24)}, {#date(2026,06,25)}, {#date(2026,06,26)}, {#date(2026,06,27)}, {#date(2026,06,29)}, {#date(2026,06,30)}, {#date(2026,07,01)}, {#date(2026,07,02)}, {#date(2026,07,03)}, {#date(2026,07,04)}, {#date(2026,07,05)}, {#date(2026,07,06)}, {#date(2026,07,07)}, {#date(2026,07,08)}, {#date(2026,07,09)}, {#date(2026,07,10)}, {#date(2026,07,11)}, {#date(2026,07,12)}, {#date(2026,07,13)}, {#date(2026,07,14)}, {#date(2026,07,15)}, {#date(2026,07,16)}, {#date(2026,07,17)}, {#date(2026,07,18)}, {#date(2026,07,19)}, {#date(2026,07,20)}, {#date(2026,07,21)}, {#date(2026,07,22)}, {#date(2026,07,23)}, {#date(2026,07,24)}, {#date(2026,07,25)}, {#date(2026,07,26)}, {#date(2026,07,27)}, {#date(2026,07,28)}, {#date(2026,07,29)}, {#date(2026,07,30)}, {#date(2026,07,31)}, {#date(2026,08,01)}, {#date(2026,08,02)}, {#date(2026,08,03)}, {#date(2026,08,04)}, {#date(2026,08,05)}, {#date(2026,08,06)}, {#date(2026,08,07)}, {#date(2026,08,08)}, {#date(2026,08,09)}, {#date(2026,08,10)}, {#date(2026,08,11)}, {#date(2026,08,12)}, {#date(2026,08,13)}, {#date(2026,08,14)}, {#date(2026,08,15)}, {#date(2026,08,16)}, {#date(2026,08,17)}, {#date(2026,08,18)}, {#date(2026,08,19)}, {#date(2026,08,20)}, {#date(2026,08,21)}, {#date(2026,08,22)}, {#date(2026,08,23)}, {#date(2026,08,24)}, {#date(2026,08,25)}, {#date(2026,08,26)}, {#date(2026,08,27)}, {#date(2026,08,28)}, {#date(2026,08,29)}, {#date(2026,08,30)}, {#date(2026,08,31)}, {#date(2026,09,01)}, {#date(2026,09,02)}, {#date(2026,09,03)}, {#date(2026,09,04)}, {#date(2026,09,07)}, {#date(2026,09,08)}, {#date(2026,09,09)}, {#date(2026,09,10)}, {#date(2026,09,11)}}) in Source"
            }
          }
        ]
      }
    ],
    "relationships": [
      {
        "name": "destination_league",
        "fromTable": "Transfers",
        "fromColumn": "to_league",
        "toTable": "DestinationLeague",
        "toColumn": "League",
        "crossFilteringBehavior": "oneDirection"
      },
      {
        "name": "announcement_date",
        "fromTable": "Transfers",
        "fromColumn": "announcement_date",
        "toTable": "AnnouncementDate",
        "toColumn": "Date",
        "crossFilteringBehavior": "oneDirection"
      }
    ],
    "expressions": [
      {
        "name": "ProjectRoot",
        "kind": "m",
        "expression": "\"\" meta [IsParameterQuery=true, Type=\"Text\", IsParameterQueryRequired=false]",
        "description": "Optional repository root, e.g. C:/Projects/football-transfer-market-analysis. Blank uses bundled snapshot."
      }
    ]
  }
}