let
    Snapshot = Table.FromRecords(Json.Document(Binary.Decompress(Binary.FromText("zV1LbxxJcv4rCV18WRL1rmrf+BAp8SUuqZU8axiDZHeSnerqSroeHDUNH/Zk+GcIczB4GBi+GIu9tv2/nNVN7XSLGV9WZbc8Sy44C1LiTERGRnwR8UXkP/7Lq/ucz0T5Y8Gn4tXfs1cXYjbl5avfsVe3pZr+OMybm7/+bJ+XQ5Grgrc/rtX6Dy+vjxffLnlR3epfOOL14vuB56c7XrbjhWs/vhXLnwaBt/hofzh9+JHXP379I+2Pfc/79cf6r/yo/63Th8Vf3A2C9pv3qpK1VEX7vXM5upUiH7Xf53fi218WxK/+9XfshcSns1zygp3f8Pv7+ZNZ8nMt9FD1FFvLrCX3TWL7mQfFDiix/d34W6n36poPJ5TMnlHmd0015YVgh2J6M3/KKbEPVVlPm2JkEnzdGKhTD2Kj+FGGxA9DQvpoN8rWPrehi71cfObFSJTsbcUnZkVciJ+GvKpzYdLEmXwQ5b1SOaGJIN7xBpQhRLGrIQReFq589FNFYlTF6+JRsSNRFvMvWiGPZl0cjEVeCaMPONf36EDWM0oRibMiBrQeEn/tYztO4VyVd1qYK3Unysqsh72qVgX7IPPcqItVNZlVoW+HZ1RFmDiqIt5MFZFRFZdjmcv7e8EOVFPLYqzM6li/BX2dhfaVvtaIWR2ulvHCVdoUQNyKPJeqZnutj6j0LzJ7CFXXU3akSlHVjlcj3fHN3hIrII1JBWTbsYATNf9Z+wUdKORnAhmI4lYOjfdgr9bhpZbP0dNw9INFmDSiAz9IAyQ5ffSZn/pRkMXPX7cRJ06akWD7QhtDcTfm0/4R80rwnJ3zUSlHlBWEADIEqWuk8GIYKWxGYVbHUa7KFjd9lGVNRIozoV3CpKlE4Ro2aWXgsBlRyvB2s8GvZqG/DvpqIzBqY7/ko1zMWOvo1DIgvNTHV6zYVxGLWBG6KALckHRVC1nS74aY/cQP2hwOpZq2aMqsgat9dibk/aO8c7wgC1X45rAZRI5xIkxXP144TRdn0QlJAa9pQQ9hGy4pi/CRGmIqWuiEajtXYa+oldS5xXEpxaO2BSJgrseFvnhhETT8yKwAnFuFtG8YBKGXJn/9+gJAYUvIzGFD/w2tC23asho7IUkbdPAX6bUZOvjP6MCsiwRAh1VFeD3vhBlHHZSyqnXIUBpWFzwfEUDyWy/wjTZOmgdR1E0Fs27CQ/g4hHq0i/D7QQgdZE0aOBTDvM0q5JDwjx81emRvluDiBZAqdSDlZJAIAYD0k8TNMwaDeOXjRZBwg5PnSlbzp4odcK0Hygr2S3k3rpUROdidY0b5Bh+mVgBKx1Gy8vHCGtxc5ZWairxhZ82ETxqzHt4WtSgdlLBwCn5gVkLofA16lhnMLvFaA4RSsfetF5BEOoUKLu91riWKZwxOogQCOXrQB2S07GGYbimhvORNzi7V3Q2BE9dcnCEY/KGm8JG/lHxgltwVKvYW2+z9TrnUvk1jXbd8wWLw3qK2ZL71qxZtOHOflDwIozhJB56/+D89o6BvhkezmWpu2L5q+GhEWP+ZhgJGy+9URSCqSlgJMXX8fVGhPzA7ff0f2VQLSNymB0RNDcW/Lrde54tGlzcYOMnu7w56l1DMnv5Nc6fY64n+LROq2H6kf8vktimN5aNuyXJgrKIMXMtHQQJjHrZ+sw94w8tyxk55QQCg9UN+kRXoX1Ww86aQwzGO/mYrcC0kejGEQRgKEl0HnSUVMyIf+MQ/9/f9QbAoExgvP5Y8pHPCtSqa37PfQoAeff81wj9VudJHyQvCB8LrQHfd2vOnegxYCyD0+9nL0I9FN3cVOmZAq+fcu0TiLeupiVEBsEKSAASwiScwZwGo0UwUyvbynTcyhylQRqRAq5e7n+Q9/X9ojvonqpoodvzAy5FcOnET/CErY7a4H9IlACw58v7fSn4obkXbA+mHd9A560SgVkaYay0AgUp5BpvLINinvRNcs8jLIHfO7xpZEnFOn/VQYx1zamfB+AP6sDOY3CDRX7h222mbU5v9stHe7biR+sznP1MwD2Z3ljpHQtd3sPQgwQnWglzvBokZ8R6VophIwUaCnajirl+o71YAJewf1jgy+sZ7vp8mUerFWRaEcW81mMO9Bv71WH6qWj2cybu6nx5s1b5lHdjYN85iVPoEju8lzLHdBTPEO2z+94u+yR9yPlYP8n/+jcA5UmlDqaWZVWWRv8V8/k5AyB853oYXnt8F5p3wkSqY9vBDijGAeqUWqOvT2U6GO4MeJbe3m/XEeGbnf8jLn2TBLuZ/mf+XQ+PHmugF4OJD0cnOT1vcXPvcRqLXobT5ui0FmSu8lgiYghgQpW4RMBn0zG7MsPaDLO9kzh4WrdBPBJ3sWjW1znHvCeltNvDMljHbQLRs6hCZHiV/sJsFPoL4NheYGrVx1siKXTfzLyV1FTajDUULQzArwl9yRwhDCOjLkPpxqNW4/NrTF5rVsFfW46Zk51oWwiEgZq0tBnh0xpt5qPETJ6QSonCA8n63xs9HUbUciSN1ywui9A1xsaUCHNA0icxDsZBkiwS73osesO0imKPhWaMBL3tjIQRYeuL26heEhTgRpD2jj9GxTSHm+HAhW55MxS7nTyTrmiyD4xThOUFyUALoh2/EDDBfh72mbCl1omDvNUZq+HT+RBXDaP55B84MQgxYHbRNhOsf20kV9op6rIoZO1bliORZotTRFi+eWwR/Q5ZBjCSIe872ylI+8hue8zvCWe7V41xod8EO9Hf7O8wWRmQE6RZrg+QavggUx4rnEyHuafdgvhun4wft5Tg7feAlr6uJFkQSWrjg92rZRu5RJY5bBLUkdfQTnUyfvd1BhPNnFx9xxatpowPH/M+f8udUyWQH2kiKmiQPgUQKFA7TQYZiJn0h0hT6Bhc63Qc5rFXJ3lVyOhaEZyCjxYqB9ENPaTZwQQ3+7iANeiZRhEPsMJqyCADXaijFiBtT6XWPSeGmwNgwSCF9DGQT64zjnjZgRgwnOjawQx0zv1CMQkyj28t3LnhVldAlmOFjCguLyBC2YwdXSsd3AhmsdgYcwmFGVM/SBJ08yKN71w2JBum+KD7xqSzYtagm1MwJ7pgAvxfTPBksOcDJ3gDiZJeDPxUPWgOHgu2XzYzqmX9U+W1105QunSM/ppvGKawjgwCQZKsfvRn2RL9QDidMi1qLKafo5dd1U9d33NwztvpBpArcPwd+cBue792Ulxrjl1PVUBRi2C23dQ8Xns9cTcWCgwShr+Mzt5O6xH0a/x1rWFTzSiNIJHpKOX1Xupy3TpropwdzAWm/nC1GlEUzJfmyoqhvdeLk5gzTncBBCaCkHCarnz1Lq2ZjOGlyqYM/28t1UkCVUFA8tI2iBRHNHcKKILlD3u46EAq3UmSe/6m4Ezk7lK1XmP9CJEYWIr2lxh4BVIiNAmCDrZiB/mfFWkg0/+WuIe1gg4rJsqwcONhBL4f4nVi0YD67ywgBkQr9Jn7AbP1vcznVtnsxkvrbZh1YWkuOM+p/S87wnNfjllB70BRj4v5rsPQgHEjkaPAyjdBALjL/cAMGmVkFHVqMgEn362AFWUE2J0aQQ0fSCrzdQbYJic6sgr1cVuRIutaPU4v5eYTKnBwFcJ4MnD/eVmGvExIKeB42vBZTUcwobKSashDTtunq6BF8KleE22tA0djf/njd+7E+74qdCZJuR8dE65A+2GXzvXTgFh6v5n+5EW3vnRPcM8C9sBnColQYmA3BR41WQLD2IjiG7dZcO+CVmMrSbcCyC8ucwEYe4h6AMlmaJL3hEVE2AqUy2F211UmWjVXjeNFqKtiDVq5Tg/4DZebzXtAsDnUi4Eay6DBVscyTzbURKD6dJ/fzeeZJQp3+1PNfCvbH5kbqAEDNU1lr5BZgHNOUeiw9CIg+RgNuk4Xns8mYzxaDFaNyRrGPxnwyrnnJDndNuuiyesBMsse6QPd/K1XyQzWVhZyw60d1o6rHnFPTdXTV2Mq+C+kZMyw9yIp7s2vMTuD1jSjFcCzZ60ciKzooZ1Wtb8Ilz/nQhXu9qJCaC4XJIHTLjYLepHuCYzUcl/xWp8YTOSUOnpylBo1in776CZwzQFcfkyfcYv6VnPGRDutjmmpnmzlA8Q+sVUhS1CgGhh/2HKUjTv6c6xSInaumIMjllo11uD2eEu3xJEVEU3T6wUbbmIidCp1Y9miwvBMMCOjMMHEbvtB5cbxWL+89dmS+Dh/kpO0cHM/m/z3RfpFIBq7vVVnLwhgLumACc300SRBvAJQIssFW6KbzP7UVcg0CVMlrt+KwhTmU0h2DBHcN6XuRbGXEcrmr7kI8UEcO8j8QBiKaJ5PEA0Q0BvnvIFsh3fdOBcz5j0bEQ3bQDJtS5NQesg12qwRIDwgBBBmhh2A3DAO0q892/80O8VgV8//gGglf8anatilQ5PvEtTGyFYLMP/AHya7lVBWEvAD4WpcrLKGf2fO7NUrbdVt4B50ji3Q2FaUcsjPeOncCClupkx3wkE8kxFgfAV0L6l39MZv+cgbzCG/aQJHPAoq8BV3AwRQAKPIwX8wtG17GggNeDMnBC9uqHUtJqEXFDo4AxIRs9bM3FjLHxNcjWbQQ+YA/kOsWXFi0yyFs34yBIsgfAxpIg5XPray1XhYGhuxa5byYEB7B0iSwOsiI3kyZRCgyIkjk9a2MmAHhwfh58QS7bHJZyaFZBWgg0wIIB4ugaKyLJLBhBoJisJV9S+dKH9pUjNhpM2q+x9qhGGTGoSOFOvI32EhqdgKXUpSl2Hm9CI4Tttfc6B/MODWYjmzBMn6T0UTaJExBh4DsFbXN07VmUc/mqXlAfxkeLsWIapRsgJNjuk6odeB4H14uaXAbKRgLMWXXtShzSR0/7Bh04JRSy1mx8MAVxr2p1MQilvlTOX+aztgJH/5zI4hCyXXNR4JdiaLg0ogNuuxsphqmSQiHMkFojNd4JH3BgVkhb/MZZ3/kN7wsZgQ2sIRGPGZDEeoSuIQyAvO5feWmemYTzk7QYoYSUGo7kMgGyAW4wuStNEq60QcBdwZAwiWx3gwJodTI8W2lTHwotEBvGvmpopjEFjvvMGqppU+oW+/KnPGijQbzqTb5dP6kdI78QI3VWXYUdNrBayRQJc8Lys2KCOmLP4i8/jQBeh3lgj530RTkLkpIn7Ns46IohAkkywBEaNlR75YYnolixn5QFP6Ba0hBgSCil/Jg+ZEP6LuUhzj49xrxNjN2MVLw5auzmdnsbdkA9PpuRKm2Q/LrPgr9tfdAjTkAthtZlcY4tbhrSMYMPVi6l+/8no8qyTFnhGgS+CgPgNcgWP3YRnXg69T5ay0qNWndvu7zd+h5ny7DRdSmksSHyyloh6itYeBF6fPXnsogNtTzQrJ3OTVlAirI1mHDiB65S+CTFSg2+t+BRNNhPfneATuX2l6cTCGkHzxKPMdWeuD3rp4TXkGWPNfp4eUnbQkUNMZ9ZIsdgIHr1ZPu5xY2WkdBUAnPVVNVvKWS3lCLeq0Tx2/rWo45jpSBOVOGugBZojdY/dzKPoqTtnLYLq1v11q9EUOyhgoKJl3WdycUt+A72YXbjssLbQ/sVMz/k+ytw1eOutHvXS4IghCWLSWOlLNFBYm94S1MIJZT2Lb8ISANNtdgTfikq/Re0u1cUuhzng8V8QbcH0Uha3a9c2lsLHZYYkzySqDM9BTyNlFSy7iVnNhgTA8YWIYNwQupWGiKVZBu553cdksVO1bF4/xLTtHqLrWBu1DKW0gYkDgAWjcldbjpXiYqUygakbM/tJP11OQ9aCfjZe0p1ULF8Q9Aob5Cm2/4smem7seiZBeTpqBGzICnt9dI3LwbGCno2y80X/Z39fzLgyRyANLebQtWQnpyxOLZwK4h/D6B7eiJJ9u+9ggOFXXq1gZBp43tLsgPEKksi/pc2iWL7hi7EDVhDHSRzGL8y3a5g/F/L+RL7Oib8pFq2LuC3FgJRo2/TQ/IBMB4J+JBCGokwAH6We9E2Oz3j0pBgDrLCIkl2gOAG8OHekBxOIscnuci6DKPpWSnqqiotXuWrK/D/noX4UFzNHopui21MVdH90XBPo4lFeVRfmcR26cHyOIMdUaAv/MyuKTWjT33XjSFPn11PxWyoB9/B5VR277e5WYNY3k8zlApEN35l4+TuRW/rtq1izqtI6fKgb+zpvggn4vhME1EGYF1sNyl3HHF78eSXKtwJsTIrfK1nJ4wAn6L+GB8Cu/ackF/PyheCPZRVpQDhLuGulTCqVwvhjM1yPt7od+XH0J6wOXauXPtO4iyH05zETMmpet9MVy1uPpk55rs0W60Xtrp6wUJdoSsllXw5wlbcmO181NlWg/GvC9OlxSh3jaQ6mBgMAK3KHCiyjvtAgjUS5Nl7Rt3KWZU7Pp0T/+sx8yP6MQLQ+u17KMjpPdL0FYZMEGQeesjBP08gDn7u1BFS4wZNYIqc7tvWIrpznjsOjfVs55JLFfVPk+wY9kGcALyuLODn9mQxqkhLDYy+55lTeKpriYnpuRxFff6Dbt+e0myoBDIhwIj/9YvvhFNrRM1LvQdVyTtxX11Fnp8OI4R55HE+O0DrBvtRyGq99bOHn6KuENiH4LE3nVKbCsVjRa8FfogW0MgQb6V72CF+oADheUPaVuIojRMsijwvThIwq28UvX2puRjOWXnN+QuOeoxSrsNgFVyFh3QNpDhAj/UgW8OeHu81JJ85MXOfov5JwTqt2+PsL9bSDpFt/dpF4/1oF2rbu7heYcUGCKmy56d2nsuSgAIYGsP0x+JUv8h9l6V5MT8RvvGA3p01iI8SICDDRhh5vN/Lz+17Bd2JeSn1nqoGhAgAXXo/SXE0FAcoe0BIDx4/R8rJ1apPC/VOy6leJzygtovaN2qZNsqt6x+m+EwnBpDDnIbcPjrQ82s3TFJ0WNRDbBLKYxaNh7jqTE6PvrrtbDtZMLPb1CUgp3xIX8UNVUcpiizlmmxFOQGeEQEOMTtbB8/b2uhImfvclk5r1TqtFclovvgWAlkN8zbHSQhHBdyo4faH7eEo2O28AjeZbBYA5oo3mCYkti1KaeKfdTnKohVm+6sAA8ABDw2FJGmkBkrYy7Zw+ksFxoq5hNK8HXH51IeJcpjASwN074gjSFF2O1dS+0UJ22BtH2XQdYlmiJrckIZ3V6zN1+FwDGbztLVdLpnt8BcMD/mNxom5OxEVNR4NdzJjwtmAb12Mw5Q0RDhpKhnyQxtGjpqn/D7TAEEsHC0Cz/CPDwRwzkSdBU2yB3BVLlib2Qx5PeSHKbBxRT3frnrMJG3pV7xmRZ+1r5xTUl+dMCuNYbQ7pI9G7FTSc1cRvpNzIB46lw1d+1rnmeNpBpFmDTRoWdOWoHv9F6Tp/WwVj3YUgN9vxRTOjiWsjB6gw7vvOtMyZwu+Gi7CKidRMlGpVXkFTUcBh10OiZ2B8tm6lgMB4kQWA7W1s705pASsVGoB17M2O8brUlqzhYwZy0xArlGD+5ZoLsMwfrrRb2cAzFy2ZKKDsYy/0nkBG98k1efPfqdmthDCAHkj8HLbXyOybNOnOdPiD5I7qTtspmUcAhQbOQQQkimtb/RQDxe1W4iK0eKXcv8gVo2sBmlgroEMGNE59/3/hPp8vypkq0B6PhIQQQrk9i2ldL8ii2WHaCDtbXkPV8poYbtZbHziQt2KomJGZpP0SkghKCrDtVATpban+1yyxuPeS4KB1793ph+wBa8W4qlD1LSCLLYX/lfz6K6uctk3U5J9NlWKymk9IQfRNKDIYr+WybIRSvLRbwHvCxF6fAiSbeVI2TNBPsAEAgCWCZwbLrzRqvi7VCHgi3uZ0flsu919122z7RldPZeyM9ClhQSxKT6k2t2rd1gQV2FNlcMqEr6d4oGjgP286cbXtVS48I3PM+pbAkuYFpb2Uc1m11CYy9Y4FQ3anJRsVPVFCMSE4iHNlFmRwfmmNiFZ0y01X6reEiurbe9YgeLaCt9+J69dhwZyR29/QzALPS7ppq2DOtDAVfQrB9zr5lKaufab+QRqRcMrVOlBCSwrx8iW6v46oMe0vrHdtKD5xfbLlsFUBsmkPVbKqfeju85xYOtZkbEEwX/rn1FS5+Q9fznvoC48/I9h6tPV437ejyCcCrLh3Znwpl65GQmcP3BJPZKlmSWmHqb5/8t4BFc+vmfyzvRsk71nx2xM16SG/jAOOnLRru5IhYQ5fJo4Lh5NIi2wya44rctmeBMkAZP7ltbYxpRZ2+29mgAx0oojxf2fZLA3Bc4nuW3bdZ315Qj+qHS65/0LzLz6VfZyObiT0YsII8GaJSOjPD+7iDtvUrJnPGe8lxfdXY51scq78k3GYhpsm67UYx5XwTnSMFqlG0RyGzvEZKe3bpWN6DTfSw1uuDbwfXWZiCmTnaocy1yXfPTe1h4VOvYEjHkSJTtDiAGxuYogthm4TyCk5Motd1OCvO6GLUL1QlD5/m0TfiNN7xDcSeiVyhGcF4QYPl0sP70ZK/TJyjk5/yznGowpy38VOZT3ju8W9L55/6v2dFDRYCBmsi4M8CtsNthnyxq9OE8NqCX6UYpinKgxBfGsNfjdhcOVC7YwuapF6jdxwfBQEkERyfJbUmBdn4bZXXEgxMyVxU7FeWEYkha9kxbg2AMvCF8eg4kuF4EafRuJd8jfkMP0dp4opbViYvijrntESWOzW9tA2ihqtsayWOxmCWWil01dU0TRqmtAqs7N8geoJEmiPUA7kU8iFY+trJz/kT/s2qj3YheLQFpAF0mzuhbgSgyKFamOFY6zlfk4tNyuv6YlwUfUjcEbOC3D9xSJbAIzlojDxG4N4YJV/l1qeCxKkcO+0a6bNqlXiqL4EAqyBZexkrrdfin/wM=", BinaryEncoding.Base64), Compression.Deflate))),
    Source = if ProjectRoot = "" then Snapshot else Table.SelectColumns(Table.PromoteHeaders(Csv.Document(File.Contents(ProjectRoot & "/data/processed/paid_sample.csv"), [Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.Csv]), [PromoteAllScalars=true]), {"player_name", "from_club_name", "to_club_name", "transfer_date", "transfer_fee", "mv_at_transfer", "fee_to_mv", "position", "age_at_transfer"}),
    BlanksToNull = Table.ReplaceValue(Source, "", null, Replacer.ReplaceValue, Table.ColumnNames(Source)),
    Typed = Table.TransformColumnTypes(BlanksToNull, {{"player_name", type text}, {"from_club_name", type text}, {"to_club_name", type text}, {"transfer_date", type date}, {"transfer_fee", type number}, {"mv_at_transfer", type number}, {"fee_to_mv", type number}, {"position", type text}, {"age_at_transfer", Int64.Type}}, "en-GB")
in
    Typed