let
    Snapshot = Table.FromRecords(Json.Document(Binary.Decompress(Binary.FromText("vX1Jbx1XmuVfCXjRq8rAnYfekdRgS6QsiLINZ6NhBB/DZJjxIlhvkE0Vel2oRf+HSuSiITQSjeoCCo1G75g/rM/3KGf6xR0Y8RySE0jZIimbh99wzjfd//JPX9y21V29+qGrlvUX/7n44qxZXFd1W3zdNuv6i38ovrjt182m6Tv64NFmUy1u6HfX24sffvuRN83V9ab4rumu6hV9vLra/WlC0z8stqtV3W1+WLT4ql//Rcf0r+2Ks22HfyN9VltXV9vdh045/fNm+cO7qn34Ha7Zw1/0gR+rZvWbDznPlGJalp4rxe3HL930P9Dn0Wew0nqpjHZKM++E9Lv/qGXTbTf1mj5BWufot676ql0//Jm772G9btabh89QX/y3fygCsJ6uWnzHxZdV1Vbd5Xi0ToDGqv7Ds371c7W6/C1eJonXWdUtruv1pl4VJ83mbh+x58cBZIKlIdPSe6e9LjW30gsRYsZL4Z3lkqvdr1oNIfOO70Em/QAyH0XsrFr3XfF8Vdfdz30/AbLpBvZ1e7e8bf5xWxdn1WpdN21b74P27E0AmtZJzJT2xnMGYxJGCOFidiatsV4wfAYX0jkzBI0xu29nQ9BMFLSXd21TwVUuqtvb+w9zmJlLovamrloAdrlqLvfRenoeeqVLm5gSgmnHfCm9ZdbGTcxoazmzUlrGXGBiRuybmJKjTOy0wh9SF99Xy6r93fb18BOKIvXspDiuVou67bvqUahy3ghLQVyyphRWKh5FCgHOcW+MZz6MXvoB3b/hJIY4cR0F6ruKvqvij9X9/4KVPF3Wq7shXmfN5Y9N3V4mrYuM5Tef86t9sSRqr6tVsy7Oq6bb/OF5vVribx71yoyZSeOVt5qVQJAx5WNeicDPtXZAz3JhnQ2iP9vHbwhfHL2n3fu+eIYUdv+n7rJ+Pxdy6Xh2cl2367oqnp08Gvt9DjDHFXeqVEIpyXgMMLilg28Kp62BbboBYEpwth/GhojFw9iL/pqiWNW9r5YXzVyA8SRg5yfFs1XdXGxXV4/xiwy9kJpzxTgszMA7TSLuMwbMlFcONhYYmGJqHy82dFAWBezbBtyo2a6LFyBJ/Wp8MDutf4zlyjS5mBT1VQYsAADjMqU1UoJZxGIZA90yDlTMg4fYYTRT+Lr9aKaGYMW52FG36bsggE0nFI+AdFxvEL+Oq7YHuXhIxlm0cmCB1VrvWQkKaz2PWxaDzSkmQCu4dt4HpuUHzDVAK25aT+oFKGvxplkEJP9QR7RJ4I5Avzp81YjIxUUaL+EM6ILmJbirYzIaurwU2hjlGRiaZiIMXVLv4aXHwfWsvqxXzaIvvq3ad/XqcjbQ5iFimXgvHIOZSVAIy6SI5kd8gCEbSA/GZbUWQ8y42MdsSFpBWVIOSUTsvF7W3V3/KT1zqjbKEAoQBIRr60rrtAE1jeZHAd7qHWgFR5wTAXG1AyML5GSCUbRt02+KI9CJFVTSXCamkrC96jcboHxdLQtoBOD3KHA2rY+EFeCwipUAVwoXBQ4RTHBjQMMEafUhcPgds8/4R+F2vL2p7npwypvq9xtZmn9NiWI8Y2AKrMooUSowK+4iKRIQOoG8oI3WRkgbMn6wuEcIBY8zfvyMIb/PFi/rrms+QxB7sX2H3wODGYL21dsANJnDTCIyWQQx/Cp0NPILxCloAKW1F+bBb/dMy+WDWFxLvrx+R/Ww4uW7alVt1jeg4M0EI0vwsLSNHaKOcnwM1mMdvBHoGMFi5JWX4CFMg9NrZBHthzULMVSXQTBLpMwXkOF1cVr/XFON7FM65rc/Hhfnm+1mc1WtBiEsZPpZsJiWTCL0Awguo54JegEdQGJcSG5Z6Jl6wMdGUv0n9x/Wzer+Q/Gk304p8aTQSquig0wsx8rk3z8UsDGLHPq3/+ND0xJiUA4bV+A5w4/5/i9d8cftRQNqcTlJSj6pf6y7dfOu/nQcNpckuQEOSpVcWdiajrILEH7PjVVSGebskI5J/6AC/oaaGYAmo6A9b7ZURESaBGZ9N0NpP80rjjbt/YcN0eXLeiyFzfglx3dsjbalNx6CJxr9Jf3lnfQcUp2JQIIPa4lD0FwUtNf15aovXtWbT8peJxR2TA4lhHiQqxLkyrGHgn3AvyCLNEcAA08zPixUGL/PKwKmH6cVzxBGyCFP7//9dlol7AFG6qHEvFEmIZtUe/2VjMVRo1BvRcmk5p5HWSusylv6sNVKORFkSLCOfBgD0PHyDtj3dUAnDo9eaRObm1dwZzz1jqjjEVdJ4BXWw1k91JDySgRhzJh9XjH0yHjsP9oiSbZN3RVvF9f9tlref+hmjP/zVMhsHjhptCsZR3DXKZWE5KA8iD/szQZdJKf3Y5kYlQBeIP7f/6krjlpw2dBL521WHpIBsm5KhWjv4KZWUK0s6qYK+cEKiAUBZ/bD0o9UckBkx0mAZ30L5+l2Jb+rbaDKD8EtozHPizOEtEX/qHfmnNNqB9rvSgf9CAuK5kvFuEXgMxpy1JkgEzD1CFjxEv+bu4q6uxVU30W9eujrz+OZabZxii9Z3fb9KG6WqfxwhDQoa18qqngZE+VmTjEaJQA904wH5VioqH3YhuXFOM04rzriGW/xk28/SzB7Vf+8qNabti6+6ZpNffn7YNPaIkESO9PSxhtKzkgtYZVsJzGHQgAidb/mP0yg8fx51q+uqIbdg2mt52MdGV67q55827Rt9ShimZIsB08TkOUlciNXIioCrFVUIEN2NY5/rCfudUnEvggIOUecqr2p1svtuvjy/v/81G7nGVlJs7Tz85PiVXXbPxh1tviTI7bag6oqyHJL7e+ogYGLAFEaZgFPs+G0ihkqzXH8/6xv1hDmxUnVLOrLQAQc7pqzdHmzCVNbKYWxJSiE5SzOa6ECyHeZpZRhh16pmN23saC1lFDnV9ddvS6Obtqm3y6uP63SHJ0vMx1erplyzCvkS2Wkik6Q7cQ4CBs3nGkXzKpAA+QDf6qS0W3rtjjtF9WmbueM/fOUZEW6ksEVgBDSlAxofAxQQUkW6srDewW80nsZhH3YXzbsJ/pKF+CUT9+/r9r3/TbEbMZq7NwNX5ALiCoEfuRCL12UYezGDbiTgittJA8KjMYNAn/QwYy3x1/093/ui11B49NS2AkBLMcqpGWaSVk6SHRj41OdoPnIC5KQUmEpVupHunBxVnHU1s0vxfNqtbj/yyRtnuuQpKfIdmOwBVPFaQ0ae7Nd1wNlHpawM8VYjkwHgWQRyrxN1BehpZiAZqdJC6FMoJM8z9cXExVs4PYLHOWsWkBitg01Y+dCLx3MJnH/nCyXYFvcIScKxLIEiaV6v4dWggvD4ELcVD4FxBUTeeRss1DpRDmtYJZLlgKmBesBHI65GHnlJcgp84BTe2W1DoBiajAONTSweNx/CRm+LI4u67t6OSHqTycVx/1qi/+aqnjSrzbLjyz5wJ4SlKTj0qnSaKdlQotrDf6gBU2QOe+GrUseTKcPe0pxyzrCd9z2xfmGJp8n+eKh3HVaIy7DLQR3XjnqWirAFm3EKcY5s9RXYtxxFwxGOZUvksUJ2VdX/ap4e91UV584Sx7Tb/3Yry5HVf0zUHFvlRG+pKaHiQd87cBvocA9M066gOdLPmgoiSFWCaL/IL+fNxcX6z98d91sJs0T5DV4pnQxfWYl450c3JUJkFh4oDSpYR/oAscN2ArtQwSGNuiZBDQj7p1PevwhzU1x/r6/6Nfv22pSEjgUvUn5MqsvIRrBHixNphsZ52eeSSEVzBKZUXk9rGMraQfIBXaXMLzmBqLpRbVd1VfN+2o2mpEuZBxtrlvIgEVx3LQX1UBsRhJoZpQFqkmCsvoSBoXQFo1tAth6pFACzjoTNAD0YExqnG46g8Yk2Vevuqq7rCdVzHKwiSRsNG5UfAlPHVllzNEOxiS4ly8lE/GZKaWVdMwiVkKkg/0GUc7kqxlx2fSsbqEGXi3rxbRGXQ6wtHtOZh4ZxJijOTut4aFQR3GxqQzjcFLLOESDcYGEEmwfsyGljWN2uoUOeAL1NKHJlNDmj+imseuDmRQAOU77DKqEY1qtoqZllOGMhtW5EsaGpuUGDeBgZF3EA9lRt7nuu7viOXhAOO85YyFjcr0/wziYgwoSFgFM0LJDFC+AJSi+IUVwGdR9xEcO8vfAbwd4xec8X/Tr621VvGyWy2bG1pJMz0pNMjKZxQwMTCgQWmlFfIBFSKBqpNotkgQ7N9Lp/Zgf5Mo4Zgj6cMR1cd5v2znmyjI5cr3uF031Hn9AXZzfIoA176riTb8c6M3Y5GcGOdqqoeVebSAJRLxkJpQWFPid9NDugbkZvq83x9X+vwIl+6UAyW0uZov8afRO6nZTUbP82+bqcX7Bc4AZLxQ34K0I+vHCP9gFVLy21AQWQgbxTAwqQENbi4f9l9f3H26vaaPw7fV2VS3nAi0d1iZNF7sMZMqDU9kSEspqEZ2covYl1bKhSIXxgYl5fcjg+k5tvqjX24CLzSs2p2umTOGfWWEV9FApwC6siqIlpGS0b2KhEqyWgTgXAwIbtOMSg/6r6rKt73aVrL79/XPY6RLQIfNSOZKBj1GvDU5Ja6hRzIxWVFHjgnHYWFAFEma4Oz6uSf7l9qovnt4Aipt5Vsc//SAG0whhXujSg8/7ePnHarMTSCAaEAQ6cEhtBzN54zzy6Xpz/+Gi6orT+rbaTlgfP2RI6nxTIeC/qbuuasIYFrGwXJ5ECLNMIU+CxUoTrQNJiSgGOqY8MqIONi8R2h65TpBZhD6ti2f3H2bbKMmAtqX1KDq3URyNMDORCfuKBlaMKiF8oHSiJQzQfTij9sopKv+E4/4sv06Yqv10d3VL44RtPctAWWZs/XBWlinQMsWtRJwq8WE68hCDTknurTTWesWCmqP4WNVI1xzjtna6hY4pnlTFyXbi5OyBO/f9si+4fzCOfKs8E8+kt2BZBIlVzEc5LO2TaGe9YZo760KCMWiVj1NMTze0cX+0vK0ut7PppVx5sa4v12M1ZqZIxiCpEchcSdnQJziGc7AtoQ3QtSpsAOhB7SLoMsVds+qQL7/eVvDC1QzrhJku05QOQC7yU/0G6bKkORYW5xZSOs8NIhkCFn4JIr9x+944suX7MFPwqn73OYqJc4+wMwG6Bb+ilXEEs+ipAkmVMcudkU5KESZMnY/+cZ30urqti+fb+u4zbN7vZhXx+/jCk2f7cE0bXWEwH6dojRw25OJl693wHTKpMohjLryzItl+DAuObCVI/7brgVezrFb3f57P0tKlxcnVshzz5+DylhYl6N6WjJIMMFkocuglT+MbKugwSSazuCXaJC/w65oGWbrP0/19CvZP87EjwlmOWnC6dqFNSROd0sSpBRKppd0Sz5ECAvIPmrtf8Blyi7hS2qnxs2pTdf27ZjEHLctMxo4/TSNEBiuBvxgYLBfem3gvidOkj+FGeK1dsBhH3HY/TY4LYkd3d/32ojjut9XltAXMjE9mjm2dfg3ITsfdcMt5Iyfb4qWl+yEmmiuVJ8bPoCsd9FTQ7xUfJ5D/Bliw4BvF61XfNbQIs61vPu1A7Pg11SxOzHGqVyhnWKJeAZyMFhow4hOYGfIvMSwijruB8axerUBZ3/b43mapiqXJ6qSRqBxYdH7Sc1FaDUoh4402D4vTNNUIJaB1wCS0H8wqDqV3PDe+qWjf5uS6Xt3MOD6QDltT76xkliBITTuvJLKfck5FCxbOO20R4o3jxkobmNhwMCpYV43b2P2/zHtgJaO+N3QYdFMVx48XqHM5EUnRKYQt+hvpokNkSnlQVM9pzAy/Bv0jrvfdcdzMwEsEk674/q//1l7+9d9+fzs33WmbUsrP7Nez3xhcWDIcYmKHZ1SGGjHeGXpe96srUKuz5qbabqrL9xMi+iGBahqJT8tq2qK33sPlSF/HKTxDJLc00IPQboIFcWEeYwvxgtf5ot9sirPFWxp6qua6MinTVyYnbB6lRQ8oFa2rachnL62Obx4pWuQFZdXcS2eDsj2i1mCRcuh4cX51Vv3SLJvd2dfjugkJ/LyV+xknXj1UjrccnFRyriWLByvGaVtX0x4lpcbAzAbXGoKJ18SqbtuvCLHvmtXms5whmGuczoNLSSZESTd6tHcRmUjBH8g6SoaQRj5QiR9X7JMVwpRKvP+wuv+wvMOP/iaoEc7YUZtKHdJBHhHMGhpAsdSKlfFahNXQ03SpmfrhcN+hhblBIAs0ddwtz+uuuwOPv9u2kwqqn+9WbsYzHfKd9qw0hv5ORUcDFLFUB1tUUptIF3J4C3BYKUwtH13UiGNt+9CFngu5zODOjAHNETvX8D/vhZUJ1CztBjInvIDODjSjFvsVnGE4ezQHPL26It9p5uKsudQ5vjSRvnLnHaNNeV3Spow3cVEEmYlkIT3SpxScB7c61eASbLDpllDa1TV85rKZJokOK0pP7Eamy/ieChIMQc1zEDAbb3pLTZV+uCVTzvtwkB/ZI2tmccCOVzsRiVCzgVaZVJQ+dK7ud3QlbRJBu1viVdSzpbvCUQSZpRkLTyPrNG8nw9FqMxjlHCWTTq4Jvf72ujiutkvafplYc80TkLTAfHNcnNbN7fvmUV/NBDjjKIsinwoB8/JxxsYF4qDGL1CgPLgRSwtf+4xt3DmfZyvQgma96IuTvlvUzf3/uP/zDLe20jRknoOUgAz5k/MSaVSnFLlkcFHIbk4VMs4DyILnDQaIxYsXR90a9lW87Krtjz9+SqSeNhQQF/gq+iHd/Lh9fKUrPZbozY6L8dICFSnit5u51sTWaO9XGBeMJSJZ7M+njOMer5rFTfFd327qZRXebZ5XR03uHKXfG/EGXE0L6t3SpGY0gdIMFLPa0YaSZCaQBEw8Ut+Imxgdh60318Xb6q4Nr87Pv5t6jlxQb+7/9e+Z4JRSQ3Fe3pZH5aNump5VhMIEr/Cy5Fbp1KUVsDvGmbKKqd2Zt0Ap2ENGfF7R7avX4QbE4UkgTULGD6mkh+7AKriEFkcSsLuTMzGoaNXecY/8aenhlsg01D5hCxa64o23N1AHq03xqnpXraZcJzjkMOW0PS6ThotZhH1XauoV8WiDhBmhqCoklDXSKRMkADZ4RmOo2OM1/9fVRdvTHG9HX/bJ5cBBNzCSQ3ce/Ir2G+CRLjWswpw0tDNI7UqwjsAjpVT7XGPcHbdvm5tNvyqe393/x009U3MpfZhgQh8uvWuD+A9OjxxAH1acxeeGEf4h1iUAEyxyLVANsqYYqoJEEqia9fUWQqqb8exRusbNy2fn3xZnVdO9Lx5mKg8ks5prAzDoARLSnvFu3O5AIDiJo8M0PBgdA4/Zj2OjiMZX62V1/z/b4mXfhZPW82fNb87xw1mvt307iGPTUiSdm1FwSAsmS+WhaIqE5FR8d7EfWYKFw5yPFIXi02Nvm2W/ub4rvqurSctcD2F/mnkd8hZceqLTA07wf10qvzvVmRi8YJoLprUwdAQ1uBprBwcKhn2BePQnXtHe/2/qXNdtuAIx/zDUVx2VbM+atuoeNbN0k9wrJ6DcIZikcCbRFdAC5EN76+G5YLUBnR2+ejBELN6t+/gc3Em1jAx0zl8RmuOCp1fGcOs57aRq5XSUtyoBPW7AWCFGYWiRDQh1gH292F4eWqk9tIky6e2pjCaHIKdp/ZJqsULFXjajgU4H+iAM/NFrFbQ3hyd8Rl5aOe3xXb3vgRtI2XrRT7tIvGulTL1HMH6uIBPGlCAwPMIY1GMi9NOCIBXMgO3Hxfu9GobZn8AY4hU3so+nos6ruoUor28mnu9MJ4DMJMbJyBiWhYt5bngpoLZpeCWFF0iFdVYZF2mg+8HCyLiiz+t6U62K8+1f/3vz13+eK4alzWtKzM9FMeYUnTklFmuMjt9VFJpmWzS9l0rlxyCKDQ53jptOfFJ3zfvim+6yejcDzc+oo0kXj9KTnF7uDszzEppHOenihQoJCeAAJmAVNvBFOTynIoKeZuJOVEvyu0faautmiv5O9IDTdjVtkCXDJqR/0EXGSvFxLiwgE1TS9k5BFXHvguuAoBoDjj8u1D80S84u6u1yhkpFOl79pl0+dgg9zfHp8pPnhIm1dIIyhpf1zhi6GCvpEY1wJMOaR/BK9DAbfBttcXTZ307SkYctB55UV21TrRqwvXbRPK6L0s0k6RjCvS25t4xzH3VIRpe34LZ05w6xLmyW++GtzgFk6XfzugZsAuF38VnE95P6ofDaF0dt9e7+w/pxHpbxTYQm5kwp6YYbj5d4OIOtMQ4fhESX4VC6H2zvjnvh4Gh1WRXP7//fxGt3ed6abmLO80Cjl0Y5EIrdo1Mm3nzzhjMJlm9IpJtgxEwMzCzY3kpQ/d321vN+Od9OTXo55Lue3s2EorilFZHv6ADV6iPty2+KZICjiVdNr6dK2uWNH4WiO+tQUopu33kXRLUhHRt6aBy5c3BvOhGIMLPezHNPNy0oj/u2v+qq4lnfby6qFqkTH6Vyv380vMkM4SC6pUhhUmknvpNKQslaTf8DxMFdFSmHz0CPQ++rtlkih766bKpwBW7Od5UmLCRl+nDEq7izJd1M4SLxrhIUEtc0eKAZKGtQg2WPdC4Trd5ldVk8afAz/6RNkelUIz2qDrRA+ZUoiXmRXIo6JRKEIac0jHkXzhIYm99GTfZ5+7Yq/li19c/rabM/SQWe6yTNosAlWCqkUSmMoycdEpJSSdpWBVgcJC9IlsM71+OabqTBi91c9lzBP1OuoFWbfrvq6mW/3Vw/al855s+c17tZFbpwzeNtcUkPGkgpgawO2+J0kHIPsHHvGpxsV9QEe9F3nyNfTposzoyVCXAwaSzdSlf6Y3coiPPWaEePRBvpTPgiuzCDqti4SuLrpsb39Yeny6atd++NXPxUr4J3QD/FdNkhxf7M6AroFU2vlHBDrxLvAnGDaObBaWnf14ZHYrnPP3CTXYZ7sd1ctff/+vtzQFpuTjw/lvZP4XYvsJRCW3CHuL3x3ZVOTu+YacvCawScD+7QjKsq0mMa8zbfMu90HT7AmAludNJCW0E3fLzRcdGpQdwAnNrthDEVaE47eIB2nHR6ef/hXdMVT6qubz7DLYejF8XR9heKD486ZiZ5CnpoXfsS0oh7HluaoORpqDlihbC/rt/vlRdNfisuMWLc3BDVeLlab/p3kYrsvOtf35wXp/ViUT9qWZneiED0RxAr6UDux42kIAsIRRUghCrnPvLVPaTY4Aj9kOwn3+ja1B1NlHeXq+3tbOE/45vP666vipMRA565oC8YtSOpi8tT+ogb0DYGxi8FPUsevnNg8ifo423xry5W1XWzpMmLq2o1LZjlIctcvJh+IDBta9zTO127sxYOAjt+vIdbpZil8Ra66hwiZ7PIpbZMaqhjYAexvP2p2czW7c0+q3G+KYvX1Xa4aThpW4J7beBhdJbAiXhjiTNnFS3w0I0VHhxTD0jtOC1OK6wA7ekVSFLxlN6J2Kxn3IxOAzfeSdMzeHTZwhtT+t0DQFGpyYxWTNNRRQaL48FaNGDLv0USL9G+bX76qeqa4k3d/ESVrNlSZnqgbOr+XIZmcJrFlvTG4I6iRfOmVppOriullVAy0j4ZTK+Mu6n7fU03Vr6vVsu+vdvefHqiMe3IVrpcRiP8WvCStkZ0vFMOW2QOkBnDkUXDTmawOj3K0k7rn5vdzf6r7We5WPA7qo2/HtuKwacZdKigB/boilT8KDE9guNhmowjccZeKcmXauPZ9Lxa3v/f4qRfT8sGB78SffKErjq2/Wox/pmlGGCKjlO6kp5uFCJ+zpMbxQTN79G9QB8c76ctsT3AhuPFcYP7OIx9BLo265H1jI9OfwEtkxM4xJEXJb0E6qSJtlOQFHbHPC3jTurw4Tg1sLSRzxKuNtfbVUHcfy43TVfUvrlsunpdj+1zZuY/YWDaSGqlC2ZV7AwevUei4JFWQaDS6YhAc6rBva1xT2u86Ltqd5/yeLu6gRoKCpHzyqgD9pkyggqwSSM1JQSSVvF7u7QK7GgqW1ko9vBdLzmIaMPhlrihPa8uVrAUKm6BtMeeDZ3x5YgJc+yZrgCjQ52c3vMCpbCJeUZwYDqNRNPXlgWbmYiCg6rQOAF6sl1c98WX9aq7/xOo2izv3mf2MQ/ZluDpdQkIcfAvorgOBDaeBmivH/9HwxuMhS1ON9zMHDdC9aKv/nF7/5cO2qbbzXBMMbNDdufekJRaVeuLfru6Ko7adTUseUy6iE3Qcec0bI5r7+Iz2pLWOKkVaumYWWBzSCSDBbpxrYKHVhTJg+XFnDXvTHT7slrSxj4S6fm3j4U1n8ZM7Z4iLBk9usHjvU7mvXpYTrRcOxcc9w8Mblz19vtts+mL8+37bdi7Sxvaeb3ou0synOZmbEibcnsxTWkZvTVCA0IMijzumeBtynu5SxTGR/pQg5fjhntM8YD29Xa9rLq6eALjuv8w6VGXtFumS0MHnd1l6cTJhKDxxdI6GFr0GDYNJdAHYX+a9ueGSgBeOTjvOe460Nt62xUv+/52WSNtTtPsn+Ox7Yx+otgPVUSvkDipEo+6aLrGCL+VTEkTXJEVHx9RTj8gFJ+kbSDZ6RWcupm2PZHsqaeFwEEZIENtIcYduCmdi0WETwzVWkuPxSEPCOVkZOdc7Ze9hwkg7qNvd9NBb/vl/Z8m7BlOH92YNH6ckZtACvTMlZrREmH8KQRuzO5dLyekVeEYAlXJ95Aat816/FDsnvha3PQG55RhvRypYAJKyFGxR1GHIE4qnLVQmAhfxlkRqCU56NAFh7oSfQEqnb2uml8mXchIEP55N+XSgNEFT2OEKv1ufzDxfpfzmnnp6Zg/qdEhYMPrSUE/OO6EDywMuatufq4eYtCnbj2NP8eSDlvOW+853ZtyVGpMhS1HL4Qa8Fr4Y3j5gfN9aTlELK4sX183UHr9Zfgoyad4i3byRbgkqaB3CMFJVQmq77hnUSuzjiHEO0uPcPx6Ym+v5yQPsrJnzZqe8T1at20V7n3NK5Henj8vuPO++LL/EQZ6XTfLx+ws55oGaY82f2k/gMfnZ/ERGJig5pRxIjyGLew+aEMKG28DPJCK5/f/vgz1+Py1suMVZYu+K/4TcINLH7UXTd89am45D4VUREArHbFZyaNFRrB7GtwzoLLSKRaehNN55OJ07Hw3OE2LhlfzHerK8Ndn23bXFB7x0FIGLkU39HRJ51S9VfEhR7sb5qZlHU1LwEO4hjxs3Gmzt3ctLbL1NAY8H1xpB/178jy9G5pYLG9mIhpkIw2daUWWFm84SQp29BKTUXQmewiZG1yeHTcJ9Kq5oaR5TIH5UxKyWc4M4luEQVlTwq6c1IllE07dEaHgkIb74O1GyVl+ET91tGax6KkBPO3S7GHd8r+dszy7/w9Kmt1VW11eVI+/SZse03CeAziuicpSNItPTwklYYAeIhxyPLyNpAeactxO2PdVVzxp+iXFst/NZDOXa0aTsfR2jqOlEVJG9mH8IrpUzuiu/06iK2FFeE3EDMr8wZAZgtd//f8=", BinaryEncoding.Base64), Compression.Deflate))),
    Source = if ProjectRoot = "" then Snapshot else Table.SelectColumns(Table.PromoteHeaders(Csv.Document(File.Contents(ProjectRoot & "/data/processed/valuation_sample.csv"), [Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.Csv]), [PromoteAllScalars=true]), {"player_name", "position", "sub_position", "age", "current_club_name", "league", "tm_value", "fair_value", "tm_to_fair", "minutes", "goals", "assists"}),
    BlanksToNull = Table.ReplaceValue(Source, "", null, Replacer.ReplaceValue, Table.ColumnNames(Source)),
    Typed = Table.TransformColumnTypes(BlanksToNull, {{"player_name", type text}, {"position", type text}, {"sub_position", type text}, {"age", Int64.Type}, {"current_club_name", type text}, {"league", type text}, {"tm_value", type number}, {"fair_value", type number}, {"tm_to_fair", type number}, {"minutes", Int64.Type}, {"goals", Int64.Type}, {"assists", Int64.Type}}, "en-GB")
in
    Typed