export const TOP5=['Premier League','La Liga','Serie A','Bundesliga','Ligue 1'];
export const sum=(rows,key)=>rows.reduce((s,r)=>s+(Number.isFinite(r[key])?r[key]:0),0);
export const median=arr=>{const a=arr.filter(Number.isFinite).sort((a,b)=>a-b);return a.length?(a[Math.floor(a.length/2)]+a[Math.ceil(a.length/2)-1])/2:null};
export const permanentFee=r=>r.transfer_type==='Fee'&&Number.isFinite(r.quoted_fee_gbp)&&r.quoted_fee_gbp>0;
export function summerMetrics(rows){const positive=rows.filter(r=>Number.isFinite(r.quoted_fee_gbp)&&r.quoted_fee_gbp>0);return {count:rows.length,fees:sum(rows.filter(permanentFee),'quoted_fee_gbp'),permanent:rows.filter(permanentFee).length,positive:positive.length,coverage:rows.length?positive.length/rows.length:null,unknown:rows.filter(r=>r.quoted_fee_gbp===null||r.quoted_fee_gbp===undefined).length};}
export function filterRows(rows,filters){return rows.filter(r=>Object.entries(filters).every(([key,value])=>{if(value===''||value===null||value===undefined)return true;if(key==='search')return String(r.player_name??'').toLocaleLowerCase().includes(String(value).toLocaleLowerCase());if(key==='dateFrom')return !!(r.announcement_date??r.transfer_date)&&(r.announcement_date??r.transfer_date)>=value;if(key==='dateTo')return !!(r.announcement_date??r.transfer_date)&&(r.announcement_date??r.transfer_date)<=value;if(key==='ageMin')return Number(r.age??r.age_at_transfer)>=Number(value);if(key==='ageMax')return Number(r.age??r.age_at_transfer)<=Number(value);return String(r[key]??'Unknown')===String(value);}));}
export function group(rows,key,measure=()=>1){const map=new Map();for(const row of rows){const k=String(row[key]??'Unknown');map.set(k,(map.get(k)||0)+measure(row));}return [...map].map(([label,value])=>({label,value})).sort((a,b)=>b.value-a.value||a.label.localeCompare(b.label));}
export function sorted(rows,key,desc=false){return [...rows].sort((a,b)=>{const x=a[key],y=b[key];if(x===null||x===undefined)return y==null?0:1;if(y==null)return -1;const d=typeof x==='number'&&typeof y==='number'?x-y:String(x).localeCompare(String(y));return desc?-d:d;});}
export function csvText(rows,columns){const safe=v=>{let s=v===null||v===undefined?'':String(v);if(/^[=+@\-\t\r]/.test(s)&&typeof v!=='number')s="'"+s;return '"'+s.replaceAll('"','""')+'"';};return '\ufeff'+[columns.map(safe).join(','),...rows.map(r=>columns.map(k=>safe(r[k])).join(','))].join('\r\n');}
